### ISSUE TITLE
Problem with mass-assignment during UPDATE

### ISSUE THREAD

**Issue by aureliusm** [dimsav/laravel-translatable#102]
Hi,

I have the following situation.

I'm using latest laravel-translatable with Laravel 5. Everything is set up correctly, but when I try to update using mass-assignment, non-translated stuff gets saved OK, but translations are not saved.

This is the array I pass:

```php
$tree_item = array
(
    [id] => 20
    [parent_id] => 1
    [ordering] => 2
    [published] => 1
    [remarks] => 
    [created_at] => 2014-10-23 08:02:36
    [updated_at] => 2015-02-25 10:01:36
    [sl] => Array
        (
            [id] => 14
            [page_id] => 20
            [locale] => sl
            [title] => O nas123123123
            [description] => 
            [slug] => o-nas
            [visible] => 1
        )

    [en] => Array
        (
            [id] => 15
            [page_id] => 20
            [locale] => en
            [title] => About us
            [description] => 
            [slug] => en/about-us
            [visible] => 1
        )

)
```

and this is how I save it:

```php
$object->update($tree_item);
```

Thanks for your help.

**Comment by dimsav** [comment]
Make sure you set the `translatedAttributes` property.

```php
// models/Country.php
class Country extends Eloquent {

    use \Dimsav\Translatable\Translatable;

    public $translatedAttributes = array('name');
    protected $fillable = ['code', 'name'];

}
```

**Comment by aureliusm** [comment]
Thanks for helping and pointing me, but the problem was not in translatedAttributes property, but I forgot to set those field as fillable!

I thought that they should be set fillable in the child "PageTranslation" model.

Otherwise, thanks for a great plugin!
