### ISSUE TITLE
No Eloquent ???

### ISSUE THREAD

**Issue by ivanmijatovic89** [dimsav/laravel-translatable#106]
Is it possible to i use Eloquent with your package. Example:

Country::where('name','=','USA')->first();

column name is in translations table...

**Comment by zoransa** [comment]
Unfortunately it does not work like that but you can query 
```
Country::with('translations')->find(
CountryTranslation::where('name','=','Germany')->first()->country_id
);
```
this thing you can easily extract to function and of course add App::getLocale() in where if you are making something generic that should only return results for locales.

**Comment by dimsav** [comment]
Translations are nothing more than an Eloquent relationship.

According the Laravel docs, you can search by translation name like this:

```php
$country = Country::whereHas('translations', function($q)
{
    $q->where('name', '=', 'USA');

})->get();
```

**Comment by marcus1611** [comment]
Can I use this package with Analogue ORM?

**Comment by dimsav** [comment]
@marcus1611 I don't know, sorry
