### ISSUE TITLE
How do i sort the data using laravel-translatable. and the data to be sorted is in its translations table?

### ISSUE THREAD

**Issue by dipeshrijal** [dimsav/laravel-translatable#107]
when i try to sort the data using the field present in the translations table it gives the error saying the column not found and it i use the db joins it says translate() method not found. how can i solve this problem? any help would be appreciate. Thank  you

**Comment by dimsav** [comment]
You can not just sort by the translation because it is in a separate table. To sort you would have to merge the translations with your main table. See an example [here](http://stackoverflow.com/questions/23530051/laravel-eloquent-sort-by-relation-table-column)
