### ISSUE TITLE
Whats the point of CountryTranslation@fillable if its not used?

### ISSUE THREAD

**Issue by Antonimo** [dimsav/laravel-translatable#109]
In your code: Translatable.php line 186

you check ``` or $this->isFillable($translationAttribute)```

this checks the main model, I need to check the fillable on the translated model!

So I can do:

```php
$input = ['code'=>'il', 'name'=>'Israel'];
Country::create([ $input, 'he'=>$input ]);
```

On the same note would be nice to check the root level for translatables and set them on the default locale

**Comment by dimsav** [comment]
Hi @Antonimo,

we use this as a hack because the Translatable trait has no access to the protected properties of the translation.

You are right maybe we should make this more clear in the readme file.

**Comment by dimsav** [comment]
`name` is a translated field. It doesn't belong to Country, but we still put it in the fillable property of Country.

**Comment by Antonimo** [comment]
may be instead of ``` $this->getTranslationOrNew($key)->$translationAttribute = $translationValue; ```
use a more direct approach
``` $this->getTranslationOrNew($key)->fill( $values ) ```

**Comment by dimsav** [comment]
You are right, this might work. I will check it and get back to you.

**Comment by dimsav** [comment]
Thanks for your feedback. This change is coming in [version 6](https://github.com/dimsav/laravel-translatable/wiki/Update-guide)
