### ISSUE TITLE
It would be nice to set the path of the translations model

### ISSUE THREAD

**Issue by RonnieVisser** [dimsav/laravel-translatable#110]
Hi,

Imwould like my ModelTranslation.php files with a separate directory within my models dir (eg. \Models\Translations). Currently this is not possible.

Maybe it would be nice to add a config parameter for the namespace of the translations model.

Regards,
Ronnie

**Comment by dimsav** [comment]
Hey @RonnieVisser !

I updated the documentation in the readme file. Check the section [configuration](https://github.com/dimsav/laravel-translatable/blob/master/readme.md#configuration).

You can put your translations wherever you want but you have to put the custom translation name as parameter.

Let me know if this is not clear.

**Comment by RonnieVisser** [comment]
Cool thanks!
