### ISSUE TITLE
Add possibility to cache

### ISSUE THREAD

**Issue by RonnieVisser** [dimsav/laravel-translatable#112]
Hi,

I was wondering if it would be possible to cache the translations. In my app, when an overview is build of 200 records, 200 queries are fired to get each translation..

thnx

**Comment by dimsav** [comment]
Hey Ronnie, have you tried [eager loading](https://github.com/dimsav/laravel-translatable/blob/master/tests/TestCoreModelExtension.php#L189)?

**Comment by dimsav** [comment]
Closing this. You can cache whatever you want in your app :)
