### ISSUE TITLE
how to use in eav model style ?

### ISSUE THREAD

**Issue by oguzcicek** [dimsav/laravel-translatable#114]
Hello , i have 2 tables . cars and car_properties table, this properties table keeps all properties , 
this table like :  `id , name , value , car_id` , my data like : `1 , color , red , car_id` 
I want to change this values according to Lang.  But i couldnt decide this package can handle my queries.
And how can i setup this structure ? Thank you for comments !

**Comment by dimsav** [comment]
It depends what you want to translate: Cars or Car properties?

Why not keep all properties in the cars table and get rid of the extra properties table?

**Comment by oguzcicek** [comment]
i have 30-31 different properties :) i keep basic 4-5 properties in Cars table , but i think i should keep others in Car Properties table or my Car table will be crazy

**Comment by dimsav** [comment]
> It depends what you want to translate: Cars or Car properties?

**Comment by dimsav** [comment]
Please give some info. I can't help you otherwise.
