### ISSUE TITLE
Use fake attribute names to act like actual attributes?

### ISSUE THREAD

**Issue by barryvdh** [dimsav/laravel-translatable#116]
I'd like to automatically get/set some of my translations in an admin interface, which just use the field names to create the form and fill the attributes after posting.

I'm not sure what the best way is to handle those translations. I was thinking about use a accessor/mutator to get the translations automatically. 

For example, a `name` attribute has 2 translations, `en` and `nl`. Instead of `$country->translate('en')->name`, could we use `$country->{'name:en'}`? (I chose the colon as example, as it's probably an unlikely token in a database)

Rough implementation would be to simply split the name on the token to detect the language:

```php
public function getAttribute($key)
{
    if (str_contains($key, ':')) {
        list($key, $locale) = explode(':', $key);
    } else {
        $locale = App::getLocale();
    }

    if ($this->isTranslationAttribute($key)) {
        if ($this->getTranslation($locale) === null) {
            return;
        }

        return $this->getTranslation($locale)->$key;
    }

    return parent::getAttribute($key);
}

public function setAttribute($key, $value)
{
    if (str_contains($key, ':')) {
        list($key, $locale) = explode(':', $key);
    } else {
        $locale = App::getLocale();
    }

    if (in_array($key, $this->translatedAttributes)) {
        $this->getTranslationOrNew($locale)->$key = $value;
    } else {
        parent::setAttribute($key, $value);
    }
}
```

**Comment by dimsav** [comment]
Sound like a good idea. Can you do a PR with tests?

**Comment by barryvdh** [comment]
Sure. I've added a PR in #117
