### ISSUE TITLE
Translation fallback

### ISSUE THREAD

**Issue by danieljausovec** [dimsav/laravel-translatable#118]
Hi.

I had created table with "useTranslationFallback" and set it to "true". Is this the right way?

**Comment by dimsav** [comment]
Hi, can you paste some code? 

Hint: Please read the [readme](https://github.com/dimsav/laravel-translatable/blob/master/readme.md) file for installation details.

**Comment by danieljausovec** [comment]
I have read installation details, but this doesn't work for me.

Example:

CREATE TABLE IF NOT EXISTS `bb_news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `useTranslationFallback` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
		
$news = News::create();
$news->useTranslationFallback = true;
$news->save();

**Comment by dimsav** [comment]
Unfortunately this is not how you can use `$useTranslationFallback()`.

1. Remove the column `useTranslationFallback` from the database.
2. Add a public property `$useTranslationFallback` in your News class and set it to true of false, whatever you want as default. 

```php
class News {

    public $useTranslationFallback = true;

}
```

By the way I updated the documentation today with more examples. 

Hopefully this helps.

**Comment by danieljausovec** [comment]
Thanks for more examples and your help! Works great.
