### ISSUE TITLE
Can not save when lang includes an dash

### ISSUE THREAD

**Issue by WilsonFpz** [dimsav/laravel-translatable#123]
Hi 

    $data = [
    'code' => 'gr',
    'en'  => ['name' => 'Greece'],
    ];
    $greece = Country::create($data);

'en' worked, but when I changed the key 'en' to 'zh-TW', it failed.
Please helped, Thanks.

**Comment by dimsav** [comment]
Please check your configuration file. You should define the locale `zh-TW` into it.

**Comment by dimsav** [comment]
```

    /*
    |--------------------------------------------------------------------------
    | Application Locales
    |--------------------------------------------------------------------------
    |
    | Contains an array with the applications available locales.
    |
    */
    'locales' => ['en', 'es'],
```
