### ISSUE TITLE
Update data doesn't works

### ISSUE THREAD

**Issue by Mdpproduction** [dimsav/laravel-translatable#125]
Hi guys,
i'm trying to update my data, but when i execute update doesn't works. Why ? Any suggestions ?

**Comment by sdebacker** [comment]
Difficult to find the problem without code sample.

**Comment by Mdpproduction** [comment]
You right. I have this array of data, something like that:

$data = [
    'code' => 'it',
    'en' => [
      'title' => 'en title',
      'description' => 'en descrive'
      .....
    ]
];

and then 

$this->model->fill($data)->save() or $this->model->update($data)

What i'm forgot to to?

**Comment by dimsav** [comment]
Use the fill method directly on the main model:

```php
$this->model->fill($data)->save();
```

**Comment by Mdpproduction** [comment]
Ok, i'll try, Thank for that awesome package for now!!!
