### ISSUE TITLE
Setting translation with different locale fails

### ISSUE THREAD

**Issue by jbajou** [dimsav/laravel-translatable#126]
Hello,

For some reason that I can't explain, I have a problem setting the translation for a give model.
```
$p = Property::find(1);
$p->title = 'My title';
$p->save();
```
This sets the title to local en (the website default locale)
```
$p = Property::find(1);
$p->translate('gr')->title = 'My title';
$p->save();
```
Fails because: ' Creating default object from empty value '

Any idea what I did wrong ?

Here is the property model:
```
class Property extends Model {
	use \Dimsav\Translatable\Translatable;
	public $translatedAttributes = array('title', 'description');
	public $translationModel = 'App\Models\PropertyTranslation';

}
```

Here is the translation model:
```
class PropertyTranslation extends Model {
	public $timestamps = false;
	protected $fillable = ['title', 'description'];
}
```

Thanks in advance for you help

**Comment by nonoesp** [comment]
If the translation of a given locale does not exist, *gr* in this case, it fails.

For this reason, it is safer to use the **translateOrNew('gr')** method &mdash which returns the translation object if it exists, or creates a new row in case it doesn't.

```
$p = Property::find(1);
$p->translateOrNew('gr')->title = 'My Title';
$p->save();
```

Hope it helps.

**Comment by jbajou** [comment]
it def did the trick! Thanks a lot. Maybe it would be useful to update the doc with this...

thanks again @nonoesp

**Comment by dimsav** [comment]
This method is in the [docs](https://github.com/dimsav/laravel-translatable#available-methods).

**Comment by mkwsra** [comment]
@dimsav buddy I guess the same thing, it should be in Docs (clearer), it's true that it's there but since you are using it to take value of it not on the left side of assignment operator `=` it's hard to find it, and I fell in the same issue as `jbajou`

**Comment by dimsav** [comment]
@mkwsra feel free to send a PR mate.

**Comment by mukete** [comment]
thanks @jbajou 👍🏾
