### ISSUE TITLE
how to set config locals dynamically?

### ISSUE THREAD

**Issue by umefarooq** [dimsav/laravel-translatable#127]
really good package for translation, do we always need to add locals in config file or we can set them dynamically if local is not available in config file.

**Comment by dimsav** [comment]
It's up to you how you want to define your locales. You could define them in a service provider instead.

One thing you have to watch out for is to make sure all the locales you have saved into the translations table are defined. Otherwise you won't have access to them.

**Comment by umefarooq** [comment]
thanks for reply can you give me an example to define locales in service provider 

my current project is Codeigniter based where i can enable and disable languages from admin

for front-end point of view we can use fallback local, but for admin or back end point of view 

for example if you have saved only English content while editing form Spanish content is not there you will see the same error.

**Trying to get property of non-object**

```php  
$page->translate('es')->title 
```
if local is not there you are returning null is there any way just return empty object of translation model so we will not have this error or any better way you have to avoid this error.

**Comment by dimsav** [comment]
Yes, try `$page->translateOrNew('es')->title;`

**Comment by dimsav** [comment]
For more information about service providers check the official [docs](http://laravel.com/docs/master/providers)

**Comment by umefarooq** [comment]
that is really great its work like charm i have to work more on service provider
