### ISSUE TITLE
Could be optimized.

### ISSUE THREAD

**Issue by chernandezosma** [dimsav/laravel-translatable#128]
Hello,

I wonder if  the function scopeListsTranslations, could be optimized as who below:

In this way, we can save time calling once to $this->getTranslationsTable() and $this->getLocaleKey() and use the variables in anonymous functions

    public function scopeListsTranslations(Builder $query, $translationField)
    {
        $translationTable = $this->getTranslationsTable();
        $localeKey        = $this->getLocaleKey()
        $withFallback      = $this->useFallback();

        $query->
        select($this->getTable() . '.' . $this->getKeyName(), $translationTable . '.' . $translationField)->
        leftJoin($translationTable, $translationTable . '.' . $this->getRelationKey(), '=', $this->getTable() . '.' . $this->getKeyName())->
        where($translationTable . '.' . $this->getLocaleKey(), $this->locale());

        if ($withFallback)
        {
            $query->orWhere(function (Builder $q) use ($translationTable, $localeKey)
            {
                $q->
                where($translationTable . '.' . $localeKey, $this->getFallbackLocale())->
                whereNotIn($translationTable() . '.' . $this->getRelationKey(),
                function (QueryBuilder $q) use ($translationTable, $localeKey)
                {
                    $q->
                        select($translationTable . '.' . $this->getRelationKey())->
                        from($translationTable)->
                        where($translationTable . '.' . $localeKey, $this->locale());
                });
            });
        }
    }

I hope to help to optimize the code of this great package.

Kind Regards
Cayetano H. Osma

**Comment by dimsav** [comment]
Added your suggestion to the code. Thanks!

**Comment by chernandezosma** [comment]
Hi, thanks to keep in mind my suggestion. I hope to ear a new version from you soon.
