### ISSUE TITLE
Support for L5.1

### ISSUE THREAD

**Issue by jammersonf** [dimsav/laravel-translatable#129]
Can you add support for L5.1?

Thank you a lot!

**Comment by sdebacker** [comment]
It is supported.

**Comment by sdebacker** [comment]
But docs should be updated.

**Comment by dimsav** [comment]
We also need to update composer.json and the travis file for tests.

**Comment by Jaspur** [comment]
+1

**Comment by dimsav** [comment]
Doc updated. v5.1 was already supported.
