### ISSUE TITLE
Issue while searching record using Eloquent

### ISSUE THREAD

**Issue by sameernyaupane** [dimsav/laravel-translatable#130]
First of all, thanks a lot for the package. I just love it, it has been really handy to use. 

Unfortunately I am having an issue with this. I can't seem to relate to $property->title translation for searching through it.

First I tried with the normal method, since laravel-translatable should work with magic method.

`$results = Property::where('title', 'like', '%' . $keywords . '%')->get();`

but it gives me the following error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'where clause' (SQL: select * from 'properties' where 'title' like %comm%)`

Then I tried the eloquent relationship search method:

`$results = Property::whereHas('property_translations', function($q) use($keywords) { $q->where('title', 'like', '%' . $keywords . '%'); })->get();`

But then it gives me an error:

`BadMethodCallException in Builder.php line 1992: Call to undefined method Illuminate\Database\Query\Builder::property_translations()`

So how does one actually try to query and return a record with this package? Any help would be appreciated. Thanks a lot. :+1:

**Comment by sdebacker** [comment]
Try with

```php
$results = Property::whereHas('translations', function($q) use ($keywords) {
    $q->where('title', 'like', '%' . $keywords . '%');
})->get();
```

**Comment by sameernyaupane** [comment]
Thanks a lot @sdebacker , that seemed to do the trick. So if the related table is whatever_translations, it will be related as just 'translations', am I right? Thanks a lot again :)

**Comment by sdebacker** [comment]
Yes it is.

**Comment by johnef** [comment]
good job but small question here please what if I am searching in multi columns 

```
$results = Property::whereHas('translations', function($q) use ($keywords) {
    $q->where('title', 'like', '%' . $keywords . '%');
    $q->where('details', 'like', '%' . $keywords . '%');
})->get();  
```
I try this but didn't work
`$q->where( 'name', 'like', '%' . $keywords . '%' ) OR $q->where( 'details', 'like', '%' . $keywords . '%' );`
