### ISSUE TITLE
For what me need a mysql connection?

### ISSUE THREAD

**Issue by approached** [dimsav/laravel-translatable#131]
Hi@all,

It is unnecessarily created a mysql connection. I have a phpunit test and do the following:
```
        $data = $this->toArray();

        $model = new AppModel();
        $model->fill($data);
```

Then I start the test and he is building a mysql connection even though I have never been saved!
```
PDOException: SQLSTATE[28000] [1045] Access denied for user 'USER'@'localhost' (using password: YES)
```

**Comment by dimsav** [comment]
In order to run the tests, you need a mysql connection. Just create one named `translatable_test` and run the tests. See the creds used here: https://github.com/dimsav/laravel-translatable/blob/master/tests/TestsBase.php

**Comment by approached** [comment]
Okay

But why i need mysql connection on a ``fill`` method?

I think the mysql connection need to be create on `->save` method.

**Comment by dimsav** [comment]
Because before each test we reset the migrations to make sure the database is on a clean state: https://github.com/dimsav/laravel-translatable/blob/master/tests/TestsBase.php#L59
