### ISSUE TITLE
Country class should not be called that

### ISSUE THREAD

**Issue by tomicakorac** [dimsav/laravel-translatable#135]
Hi, I would like to suggest you rename your `Country` class to, let's say `Language`, or `Lang`, or `Locale`, or basically anything except `Country`. You can read why [in this article](http://responsivenews.co.uk/post/123104512468/13-tips-for-making-responsive-web-design). In short, A language (and hence a translation) is not the same as a country. There are literally hundreds of languages which are not official in any country whatsoever. Also, there are languages which are being spoken in more than one country. This class however serves to get a translation to a certain language, and should not have any concerns about countries.

What say you?

**Comment by dimsav** [comment]
Hi there,

I'm sorry to hear that you feel confused. The model `Country` is not used to represent a language or a locale. It is just an example used in the tests and in the documentation and thus you are not forced to use it.

If this is still confusing you, replace `Country` by `Vegetables` while reading the docs.

**Comment by tomicakorac** [comment]
Oh, only now I see! Haha, really sorry, I must have been very tired when I read the README.md.
