### ISSUE TITLE
When manually joining translations, we should not have a second query WHERE … IN (…)

### ISSUE THREAD

**Issue by sdebacker** [dimsav/laravel-translatable#139]
In order to increase performance of long lists, I wanted to manually make a left join on translation table. But I see that I cannot avoid the second query

    select * from `news_translations` where `news_translations`.`news_id` in (“many ids here, slow query”)

It should be great if the package could detect that we already have a translated column loaded by join.
What do you think about that ?

**Comment by dimsav** [comment]
Do you really need to load so many items at once? Even if the package is able to detect if a translation has been loaded, you would still have to make this big query to fetch the data initially. 

Some performance tips would be: 
- only load the translations you need
- eager load data
