### ISSUE TITLE
[Q] How to delete/remove specific translation?

### ISSUE THREAD

**Issue by Omranic** [dimsav/laravel-translatable#141]
First of all, thank you @dimsav for this awesome package.
My question is: How to delete/remove specific translation from a model without affecting the model itself or other translations? Do I have to deal with translations regularly like normal, actually it loops through all translations even if any of it has been removed from the form, it must be a way to clear out dropped translations.. Am I missing something?

**Comment by dimsav** [comment]
Hey,

I'm not sure what you mean. You can delete translations like any other eloquent object. [See here](http://laravel.com/docs/5.1/eloquent#deleting-models).

**Comment by Omranic** [comment]
What I mean is that "saveTranslations" method loop through all translations (already inserted in the database), while in the form/UI I've added a deletion functionality that just remove the specific translation fields from the DOM & I'm supposed to see that reflection on the code; ie. expected to loop through submitted data not existing data..

$this->translations array reflects only changed & new translations, but not deleted ones..

**Comment by dimsav** [comment]
I see. Can you write a code example showing the issue?

PS. Are you at Laracon in Amsterdam this year?

**Comment by Omranic** [comment]
Sure, I'm working on it now, once I've something acceptable I'll post it here to discuss it again.

Laracon: I hope so, but not this year!

**Comment by Omranic** [comment]
```
    protected function saveTranslations()
    {
        $saved = true;
        $exclude = array_diff($this->translations->lists('locale')->toArray(), array_keys(input()->all()));

        foreach ($this->translations as $translation) {
            //dd(get_class($translation));
            if ($saved) {
                if ($this->isTranslationDirty($translation) && ! in_array($translation->locale, $exclude)) {
                    $translation->setAttribute($this->getRelationKey(), $this->getKey());
                    $saved = $translation->save();
                } elseif (in_array($translation->locale, $exclude)) {
                    $saved = $translation->delete();
                }
            }
        }

        return $saved;
    }
```
That's what I mean, does that code make it clear what I'm trying to achieve?

**Comment by dimsav** [comment]
Sorry for replying with delay.

Hmm. Even though I tried a lot to understand, unfortunately I wasn't able to:

- We are deleting records from the database in the `saveTranslations()` method, which contradicts with what the method should be doing.
- We are relying on input() which is not something we should put in the trait.
- All the tests break when using this code.

Please send a code from the project, this might help me understand what exactly is happening.
