### ISSUE TITLE
Using this with forms

### ISSUE THREAD

**Issue by namik-mesic** [dimsav/laravel-translatable#145]
Hello,

How am I supposed to use this in forms when using the fill($attributes) method?

When I fill my attributes via controller / repository, it never saves the translations in the database.

Note: I have installed everything as mentioned on the site.

I tried naming the form fields like name:en, name:de, etc.

Thanks!

**Comment by dimsav** [comment]
This question might not be related to the package but to Laravel it self. In order for methods like fill() to work you need to make sure the attributes you save are set as fillable.
