### ISSUE TITLE
[feature] Get Model only if has translation

### ISSUE THREAD

**Issue by Pyton** [dimsav/laravel-translatable#147]
It would be nice if getting result it will filtered if there is no translation (current or specified).

Currently i'm doing sth like that:

    $posts = Post::published()->get()->filter(function($model) {
            return $model->hasTranslation();
        });

**Comment by dimsav** [comment]
Hi Lukas, how would you implement that? Feel free to open a pull request :)

**Comment by Pyton** [comment]
#148 
I set default locale. This method do waht i want :)

**Comment by dimsav** [comment]
PR merged. Thanks!
