### ISSUE TITLE
[Laravel 4.1] LocalesNotDefinedException

### ISSUE THREAD

**Issue by Mdpproduction** [dimsav/laravel-translatable#153]
Hi guys, i'm working on an old project with L4.1,
and when i try to save i get this message:

**Please make sure you have run "php artisan config:publish dimsav/laravel-translatable" and that the locales configuration is defined.**

And this is a little strange, because i've run 'config:publish' command. So, any suggestions ?

**Comment by dimsav** [comment]
Sorry for the delayed reply. For some reason the $locales variable is empty [here](https://github.com/dimsav/laravel-translatable/blob/v4.4/src/Translatable/Translatable.php#L225-L232). 

Please make sure your configuration is set correctly.

**Comment by Mdpproduction** [comment]
I fixed, my fault. Works fine now
Il 05/Ott/2015 18:34, "Dimitris Savvopoulos" <notifications@github.com> ha
scritto:

**Comment by summermick** [comment]
it's still empty in laravel 5.6
