### ISSUE TITLE
Suggestion: Locale-specific fallback locales?

### ISSUE THREAD

**Issue by kitbs** [dimsav/laravel-translatable#154]
From what I understand, the way the fallback locale works, you can either have:
* the specific language you have requested: (`$model->translate('fr')->name;`); or
* fall back to a single locale set in the config file (`'fallback_locale' => 'en'`).

But could it be possible to configure (or infer) a language-only fallback locale for a country-specific locale, and failing that, fall back to the base fallback locale?

Assuming the following:

* I have a site that is available in English (United Kingdom) `en_GB`, English (United States) `en_US`, French (France) `fr_FR` and French (Canada) `fr_CA`.
* 90% of my English translations are the same in UK and US English.
* 90% of my French translations are the same in French (France), and Canadian French.
* 5% of all of my translations are the same in both English and French.

If a translation is the same in the UK and the US, I don't want to have to save and maintain it twice. I would rather say:
* If the translation is specific to a country, save it under `en_US` or `en_GB`.
* If the translation is common to both countries, save it under `en`.
* If no `en_US` or `en_GB` variant exists, fall back to `en`.

Which would work easily under current functionality.

**But**, I also have French translations, some specific to France and some to Canada, so I would say:
* If the translation is specific to a country, save it under `fr_FR` or `fr_CA`.
* If the translation is common to both countries, save it under `fr`.
* **If no `fr_FR` or `fr_CA` variant exists, fall back to `fr`.**
* And *finally*, if no French variants exist at all, fall back to `en`.

This could be done in two ways, either:

1. Detect that a country-specific locale (`fr_FR`) is being used and automatically strip the country off to try the language (`fr`) as a fallback, and then the final fallback to what is set in the config `'fallback_locale'`.
2. Allow custom configuration to map locales to their own specific fallbacks, e.g. something like:
```php
'fallback_locales' => [
    'en_GB' => 'en',
    'en_CA' => 'en',
    'fr_FR' => 'fr',
    'fr_CA' => 'fr',
    // etc.
],
```
or
```php
'fallback_locales' => [
    'en' => ['en_GB', 'en_US'],
    'fr' => ['fr_FR', 'fr_CA'],
    // etc.
],
```

In my scenario, option 2 is overly complicated and gives no particular benefit, but it could theoretically be useful to some users with more complicated combinations of locales, I suppose.

I think this would help users in situations like #50 and #51, although I believe he was thinking about the problem in the wrong way.

What do you think of this as as suggestion? Thanks for your great work!

**Comment by dimsav** [comment]
I like your idea a lot! Thanks for taking the time and writing using details.

We could implement this for one of the next versions. Now, regarding the style of configuration:

I'm a big fan of using conventions over configuration. We could add a config for enabling locale-specific fallbacks (disabled by default). When this setting is set to true, we should use the technique you describe to switch from location specific language to location agnostic. (from en_GB to en).

If a user of this package want's to add custom rules, we could implement that later. 

I see in [wikipedia](https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes) they use a `-` as separator instead of a `_`. What do you think we should use by default? (we can make this configurable, so no worries if you have existing data)

**Comment by simonfunk** [comment]
I'm in the same situation, we have german german and swiss german, it's also up to 90% similar but has some differences.
So i would also be glad to have this feature ;)

**Comment by dimsav** [comment]
Hey Simon! This feature is coming with the next release :)

**Comment by simonfunk** [comment]
Hi Dimitris :)
What's the timeplan of next release?

**Comment by dimsav** [comment]
Very soon...!

**Comment by kitbs** [comment]
This is exciting news! Looking forward to seeing it. Thanks for the great work!

**Comment by dimsav** [comment]
@kitbs and @simonfunk can you please review https://github.com/dimsav/laravel-translatable/pull/169 ?

**Comment by dimsav** [comment]
Done. Please check the docs for instructions: https://github.com/dimsav/laravel-translatable#country-based-fallback

**Comment by simonfunk** [comment]
thanks you very much Dimitris! Currently i'm really under pressure so i not really have time to test it. but will do as soon as i can. 

Cheers
