### ISSUE TITLE
Store a new entity in Database from Scratch fields are empty

### ISSUE THREAD

**Issue by siavash13** [dimsav/laravel-translatable#155]
I am trying to get this package working with my application, I have created a class like 

     <?php 

        namespace App;
        use Illuminate\Database\Eloquent\Model;

        class Category extends Model {
            use \Dimsav\Translatable\Translatable;

           public $translationModel = '\App\Category_Translation';
    
          public $translatedAttributes = ['name'];
          protected $fillable = ['name'];    
    
          protected $table = 'Category';
          public $name;
    }

When I need to store an entity into the database, I use the following piece of code: 

       $category = new \App\Category();
       $category->name = "cat_name";        
       $category->save();

But what I get inside the database is like this and nothing is stored as the value of field name

![emptyfield](https://cloud.githubusercontent.com/assets/5511686/10248348/d594d6b6-692b-11e5-96c4-a64d0e147997.png)

where am I probably making mistake?

**Comment by dimsav** [comment]
Did you create a CategoryTranslation model and a `category_translation` table? 

If yes, the name `cat_name` should be saved into the `category_translation` table. 

Also make sure that the table `categories` doesn't have a column named `name`.

**Comment by AEK-BKF** [comment]
Same issue with me :/
