### ISSUE TITLE
What is the optimized way of requesting all objects from the tables with a specific language

### ISSUE THREAD

**Issue by catalinux** [dimsav/laravel-translatable#156]
Let's say i have a table `category` with translation for german. 

How would I replace my code that has `Category::get()`  into something like Category::translate('de')->get(). I would like to have similar objects (of Category) so I could replace existing code.

**Comment by dimsav** [comment]
This is eloquent my friend and has nothing to do with this package.

Have a look at the documentation [here](http://laravel.com/docs/5.1/eloquent-relationships#querying-relations)
