### ISSUE TITLE
Select a Country by CountryTranslation.name

### ISSUE THREAD

**Issue by rafamds** [dimsav/laravel-translatable#159]
Using the examples models (Country and CountryTranslation), how could I select Country by a property on its translation table?

For example, imagine I wanted to search in all Countries for one that has in ContryTranslation the name 'Portugal':

``` php
$country = Country::get()->translations()->where('name', 'Portugal')->first();
```

This obviously doesn't works :/
How would you achieve this without using two queries?

**Comment by sdebacker** [comment]
You can use whereHas:

```php
$country = Country::whereHas('translations', function ($query) {
    $query->where('locale', 'en')
        ->where('name', 'Portugal');
})->first();
```

More info: http://laravel.com/docs/5.1/eloquent-relationships#querying-relations

**Comment by rafamds** [comment]
Yeah, I tought that it was more like an Eloquent related problem, than the plugin itself. But maybe @dimsav can make a easier way to achieve this. 

Thanks for your answer @sdebacker it really helped

**Comment by dimsav** [comment]
Let's add this to the FAQ

**Comment by dimsav** [comment]
Done.

**Comment by rafamds** [comment]
May I suggest the addition of the following QueryScope to the Translatable Trait?

```php
public function scopeWhereTrans($query, $search){
    return $query->whereHas('translations', function($query) use ($search){
        $query->where('locale', $search['code'])->where($search['key'], $search['value']);
    });
}
```

Then you would use it like this example:

```php
$country = Country::whereTrans(['code' => 'pt', 'key' => 'name', 'value' => 'Portugal'])->first();
```

**Comment by dimsav** [comment]
Please make a pull request if you want a feature to be added.

**Comment by rafamds** [comment]
Here it is #162  
Hope it helps :+1:

**Comment by sebdesign** [comment]
I was thinking of using the `translatedIn()` scope to achieve what @rafamds was asking but of course I couldn't pass the where clause inside the query.

So I would suggest the following solution (or additional method) to pass extra query parameters to the scope like @sdebacker did:

```php

/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @param string $locale
 * @param callable|null $extra
 *
 * @return \Illuminate\Database\Eloquent\Builder|static
 */
public function scopeTranslatedIn(Builder $query, $locale = null, callable $extra = null)
{
    $locale = $locale ?: $this->locale();

    return $query->whereHas('translations', function (Builder $q) use ($locale, $extra) {
        $q->where($this->getLocaleKey(), '=', $locale);

        if(is_callable($extra) {
            call_user_func($extra, $q);
    });
}

// This is how it would be used
$country = Country::translatedIn('en', function ($query) {
    $query->where('name', 'Portugal');
})->first();
```

**Comment by Gummibeer** [comment]
`scopeWhereTranslation` is available to query the main model by a translation.
