### ISSUE TITLE
Impossible to order by from a translation column

### ISSUE THREAD

**Issue by gmarineau** [dimsav/laravel-translatable#160]
Hi,

I have categories with a translation table everything work but when I try to order by with a translation column the model don't found the column from the translation table.

This is an example:

```php
Category::where('status, true)->orderBy('category', 'ASC')->get();
```

If you have any idea thanks and great job !

**Comment by gmarineau** [comment]
I have try this but i have a sql error : 

Category::where('category_id', NULL)
    ->translated()
    ->orderBy('category', 'DESC')
    ->get();

 Unknown column 'category' in 'order clause' (SQL: select * from `categories` where `category_id` is null and (select count(*) from `categories_translations` where `categories_translations`.`category_id` = `categories`.`id`) >= 1 order by `category` desc)

Any idea ?

**Comment by dimsav** [comment]
A tip here is to make the MySQL query first and then do the Eloquent one.

To fetch a list of records ordered by a translated field, you can do this: 

```mysql
SELECT * from countries
JOIN country_translations as t on t.country_id = countries.id 
WHERE locale = 'en'
GROUP BY countries.id
ORDER BY t.name desc
```

The corresponding eloquent query would be:

```php
Country::join('country_translations as t', 't.country_id', '=', 'countries.id')
    ->where('locale', 'en')
    ->groupBy('countries.id')
    ->orderBy('t.name', 'desc')
    ->with('translations')
    ->get();
```

I hope this helps.

**Comment by cmoralesweb** [comment]
I have created this scope, in case you'd like to add it to the available ones :smile:  :

```
 /**
     * Order by field from translation table instead of local table
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $locale
     * @param string $orderField
     * @param string $orderType
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOrderByTranslation($query, $locale, $orderField, $orderType = 'ASC')
    {
        $translationTable = $this->getTranslationsTable();
        $table = $this->getTable();

        return $query->join("{$translationTable} as t", "t.{$this->getRelationKey()}", "=", "{$table}.id")
            ->where('locale', $locale)
            ->groupBy("{$table}.id")
            ->select("{$table}.*")
            ->orderBy("t.{$orderField}", $orderType)
            ->with('translations');
    }
```

**Comment by dimsav** [comment]
This query is already added in the [FAQ](https://github.com/dimsav/laravel-translatable#how-do-i-sort-by-translations) of the docs.

Hmm I wonder if it is too specific to be added in the code, things might go weird if we combine this scope with other joins or conditions.

**Comment by cmoralesweb** [comment]
Ok, I understand :)

**Comment by kp77** [comment]
I tried to use the code example from the FAQ, and it didn't work perfectly. 
I had to add 
`->select('countries.*')`
to the query to make it work.

**Comment by fico7489** [comment]
this package can solve your problem https://github.com/fico7489/laravel-eloquent-join
