### ISSUE TITLE
[QUESTION] How to select only some translation columns

### ISSUE THREAD

**Issue by shadoWalker89** [dimsav/laravel-translatable#161]
Hi,
I'm new to this package and i hope you can help me.
Is it possible to select only some columns from a translation.

For exemple, let's say we have an article that is translatable. The translatable attributes are 'title', 'description', 'content'

How can i make an eloquent query that select only the article 'id' on the main table and the 'title' and 'description' from the translations table but in the same time, keep all the cool stuff of the package like locale fallback ...

**Comment by dimsav** [comment]
Why would you want to do that?

**Comment by shadoWalker89** [comment]
I just made a simple example but in my case i have a Model that have a lot of relations and a lot of data to load.
For performance purposes i need to load only the columns i need and not all the columns.
After all it is better to load 5 columns instead of loading 20 columns.

**Comment by dimsav** [comment]
It's not a question of how we can do this in this package, but rather of how can we do this in Laravel. Honestly I have no idea and after searching around the only solution I found was [this](http://laravel-tricks.com/tricks/column-selection-in-eager-loading), but for some reason it didn't work form me using Laravel 5.

**Comment by shadoWalker89** [comment]
Thank you for your answer.
Dear dimsav, i know that trick and i already use it in my projects, but that only will not help because, like i said in my intial post, locale fallback should not be dropped when a user want to select only some columns, and that is why i created this issue.

Following the logic in the specified link will not give us locale fallback because this is a thing that you developped in your package.

**Comment by dimsav** [comment]
Please make a pull request if you want a feature to be added.
