### ISSUE TITLE
Eager loading doesn't work

### ISSUE THREAD

**Issue by maciekish** [dimsav/laravel-translatable#17]
Hi,
I'm trying to load a laravel-translatable model from a different models relationship throught eager loading. Only the untranslated attributes are returned. Is this by design or am i "doing it wrong"™?

```
$game = Game::with('players', 'rounds', 'rounds.questions')->find($game->id);
```

It's rounds.questions that contains laravel-translatable models.

The question model has this:

```
use \Dimsav\Translatable\Translatable;
public $translatedAttributes = array('question', 'correct', 'incorrect0', 'incorrect1', 'incorrect2');
```

And it's exactly the translatedAttributes that are missing.

**Comment by BartHuis** [comment]
@dimsav Hi, thanks for this module :D but, i get problems with this too. Using with, using constraints, everything.

category controller:
`
        $category = \App\Category::find(1)->with(['products','products.translations'=>function($query){$query->select(['product_id', 'name'])->where('locale','=','nl');},'categoryFeatures'])->firstOrFail();
        return view('category', ['category'=>$category,'ancestors'=>$ancestors]);
`

category view:
`
            @if(! empty($category->products))
                @forelse ($category->products as $product)
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 categorybox">
                        <a href="{{$product->product_url}}">
                            <div class="category">
                                @if( ! empty($product->productGallery[0]["thumb_link"]))
                                    <img src="{{$product->productGallery[0]["thumb_link"]}}" />
                                @endif
                                {{ var_dump($product->translations) }} ({{trans('routing.product')}} {{$product->id}})
                            </div>
                        </a>
                    </div>
                @empty
                @endforelse
            @endif
`
this way i get over 300 queries, one for each translation of every product. When i remove the translation from the view it has only 10 queries on my whole page. so it seems like it's not passing the translations on the forst query?

Bart
