### ISSUE TITLE
Fall back to default locale if the translation is null

### ISSUE THREAD

**Issue by rigor789** [dimsav/laravel-translatable#171]
Hey, I'm not sure if It's there, and I totally missed it, but I'm trying to translate properties, and if no translation is given `NULL` is saved to the db. When retrieving properties, the `NULL` properties don't fall back to the default locale, and just display blank!

I could possibly create a helper for

``` php
$model->property ?: $model->translate($default_locale)->property;
```

For example

``` php
$model->translateOrDefault($current_locale)->property;
```

Will check if a translation exists, and if it does, it will return it, but if the property is null, it will not fall back to the default!

Have I missed something, or is this the intended behaviour?

**Comment by dimsav** [comment]
Please have a look at what translate() is doing. You'll see that this doesn't return any fallback by default. Check the code for public methods to use what you need.

**Comment by rigor789** [comment]
Hey @dimsav, I have looked at the source, and as far as I can tell most methods rely on `getTranslation($locale = null, $withFallback = null)` which returns a `ModelTranslation` instance for the current (given) locale, or the default locale, and lastly if none is found, returns `null`.

Let's say I have a Model with
```yaml
Model: 
  en:
    - title: Some English Title
    - name: Some name
  other-language:
    - title: Some translated title
    - name: NULL
```
If I want to display the title, I would use:
```php
$model->title
```
And that will display the title in the current locale. If I want to display the `name` property, I'd like to use the same markup: `$model->name` which would work properly for the `en` locale, but display an empty string for the `other-language` since it will find the `ModelTranslation` and it's field is `null`, so it will not fall back.

Is this the intended behaviour?

If it is, then I'm not sure if this should be implemented on the package level or not, that's your call! 

Anyways just thought I'd share this particular use case, where not all translations are required, if they are the same the default should be displayed.

**Comment by dimsav** [comment]
Hi @rigor789, 

thanks a lot for sharing your ideas! Unfortunately that's not how fallback in Translatable works. As you can see in the `getTranslation()` method, we don't check if the translation of a specific field exists. What we check is if there is a translation relationship for the selected locale.

However your question makes totally sense. Maybe we can build this feature but it has to be done very carefully to not break existing conventions or worsen the performance.

**Comment by rigor789** [comment]
I would think a config option to fall back for falsy values could be an appropriate solution! Something along the lines of
```php
'fallback_for_empty_values` => true
```
which would be `false` by default for backwards compatibility.

Another idea would be to force the behaviour independant of the configuration, with a method
```php
$model->translateOrFallback('property');
```
That would ignore the configuration, and display the localized property if it's not empty or `null`, and fall back to the default locale otherwise.

**Note**:The `translateOrDefault()` method could be replaced, but that would possibly break backwards.

I'm unsure about the name for the method though!

**Comment by mige** [comment]
For this case I wrote this abstract class. Override only toArray method is enough for me, because data always go to JSON.

```php
abstract class FallbackTranslationModel extends Model
{
    use \Dimsav\Translatable\Translatable {
        toArray as translatableToArray;
    }

    public function toArray()
    {
        $attributes = $this->translatableToArray();
        $hiddenAttributes = $this->getHidden();

        $fallbackLocale = $this->getFallbackLocale($this->locale());
        $translations = $this->getTranslation($fallbackLocale);

        if($translations)
        {
            foreach ($this->translatedAttributes as $field)
            {
                if (in_array($field, $hiddenAttributes)) {
                    continue;
                }

                if (empty($attributes[$field])) {
                    $attributes[$field] = $translations->$field;
                }
            }
        }

        return $attributes;
    }
}
```

**Comment by trallamochila** [comment]
Break many conventions adding this to "getAttribute" method to add this feature?

            if($this->useFallback() && empty($this->getTranslation($locale)->$key)) {
                return $this->getTranslation($this->getFallbackLocale())->$key;
            } else {
                return $this->getTranslation($locale)->$key;
            }

**Comment by llioor** [comment]
@dimsav Hi there... 
I think it related to the subject.
I want to select the fallback translation if I have NULL or '' in current translation. Do we have a good method for it?
Thanks

**Comment by llioor** [comment]
@dimsav Hi there... 
I think it related to the subject.
I want to select the fallback translation if I have NULL or '' in current translation. Do we have a good method for it?
Thanks

**Comment by fatoskurtishi** [comment]
@rigor789 I have exactly problem as yours! Have you found a solution for this ?

**Comment by rbngzlv** [comment]
Hi!

I have the same problem, and I opted to not save the empty translations in the database. I have an application with a dozen of languages, and I think that is not necessary to save rows that have all fields empty.

I modified the following two methods in the trait `Dimsav\Translatable\Translatable` 

```php

trait Translatable {

    ...

    /**
     * @param \Illuminate\Database\Eloquent\Model $translation
     *
     * @return bool
     */
    protected function isTranslationDirty(Model $translation)
    {
        $dirtyAttributes = $translation->getDirty();
        unset($dirtyAttributes[$this->getLocaleKey()]);

        /* START ADDED */
        if(! $translation->exists) {
            // We are creating the record
            foreach ($this->translatedAttributes as $attribute) {
                if (empty($dirtyAttributes[$attribute])) {
                    unset($dirtyAttributes[$attribute]);
                }
            }
        }
        /* END ADDED */

        return count($dirtyAttributes) > 0;
    }

    /**
     * @return bool
     */
    protected function saveTranslations()
    {
        $saved = true;

        foreach ($this->translations as $translation) {
            if ($saved && $this->isTranslationDirty($translation)) {
                /* START ADDED */
                if($translation->exists) {
                    // We are editing the translation
                    $isEmptyTranslation = true;
                    foreach ($this->translatedAttributes as $attribute) {
                        if (!empty($translation->getAttribute($attribute))) {
                            $isEmptyTranslation = false;
                            break;
                        }
                    }

                    if($isEmptyTranslation) {
                        $saved = $translation->delete();
                        continue;
                    }
                }
                /* END ADDED */

                $translation->setAttribute($this->getRelationKey(), $this->getKey());
                $saved = $translation->save();
            }
        }

        return $saved;
    }

    ...

}
```

For now seems to work fine. Any comment is very welcome.

Regards,
Rubén

P.D:  Thanks for make this library.

**Comment by lotestudio** [comment]
For me this depends on input! If you want fallback for all translated keys just fill them with fallback locale values, ...It will be a little bit complicated when doing updates.

**Comment by allamgr** [comment]
I made a little change in the "getAttribute" method, instead of return null, the method will return the original parent method.

Original 
if ($this->getTranslation($locale) === null) {
      return null;
}

With changes
if ($this->getTranslation($locale) === null) {
      return parent::getAttribute($key);
}

I don't know if break some conventions but it solve my problem.

**Comment by Gummibeer** [comment]
`getAttributeOrFallback` is the solution here.
