### ISSUE TITLE
101 sql queries, Carl! Why so much?!

### ISSUE THREAD

**Issue by Roquie** [dimsav/laravel-translatable#172]
My code:
```php
DB::connection('pgsql')->enableQueryLog();
$results = $this->model->take(100)->get()->toArray();
$log = DB::connection('pgsql')->getQueryLog();
dd($log);
exit;
```
Output:
![2015-10-25 23 21 18](https://cloud.githubusercontent.com/assets/3214290/10717627/1387927e-7b6f-11e5-8511-1a72949cb0db.png)

wtf? why not two queries (1 to `Countries` table, 2 to `CountryTranslation` table with `where in (1, 2, 3)` statement)?

**Comment by sdebacker** [comment]
Just add ->with('translations') before get method.

**Comment by Roquie** [comment]
Oh my God, I forget this. I'am just overworked. Works fine!
