### ISSUE TITLE
How can i send array?

### ISSUE THREAD

**Issue by omerozturk0** [dimsav/laravel-translatable#173]
$page->translate(app()->getLocale())->name = $request->input('name');
$page->translate(app()->getLocale())->title = $request->input('title');
$page->translate(app()->getLocale())->kyw = $request->input('kyw');
$page->translate(app()->getLocale())->dsc = $request->input('dsc');
$page->translate(app()->getLocale())->content = $request->input('content');
$page->save();

i don't want to write like this. How can i send them attributes from array or other way?

**Comment by dimsav** [comment]
Hi mate, you can do this:

```php
$input = Input::only(['name', 'title', 'kyw', 'dsc', 'content']);

$translation = $page->translate(); // Don't need an argument for the current locale
$translation->fill($input);
$translation->save();
```

That's typical Laravel and not related to the package.
