### ISSUE TITLE
Option to have a different primary key in Eloquent

### ISSUE THREAD

**Issue by SerendipityNL** [dimsav/laravel-translatable#174]
When you specify a different primary in an Eloquent model, the translation fails because it thinks it needs 'id' instead of the already specified primary key. 

Is there a way to use the set primary key when it is present? Or just always get the primary key?

Edit: 
A quick look in #170 (from @bbredewold) seems so fix this.

**Comment by RamonSmit** [comment]
#170 indeed an useful PR. Solves a lot of problems for me. I think @dimsav should merge this PR. 
It passes the travis-ci tests and has no conflicts, thereby no harm done.

**Comment by dimsav** [comment]
Implemented and will be released soon.
