### ISSUE TITLE
Fire 'updated' event along with 'saved'

### ISSUE THREAD

**Issue by rigor789** [dimsav/laravel-translatable#175]
Hey,

The `Translatable` trait fires the `saved` event on the parent when a translation is saved, but it doesn't fire the `updated` event. 

According to the Laravel docs the default models fire both `saved` and `updated` events 
> Whenever a new model is saved for the first time, the `creating` and `created` events will fire. If a model already existed in the database and the save method is called, the `updating` / `updated` events will fire. However, in both cases, the `saving` / `saved` events will fire.

I think Translatable should fire the `updated` event as well!

I can do a PR if you want!

**Comment by dimsav** [comment]
Sure do a PR.

**Comment by junkystu** [comment]
I've just come across this issue too. Any updates? Thanks

**Comment by rigor789** [comment]
Hey I have been busy with work, will try and do a pr in a few hours!
