### ISSUE TITLE
Question about saving models

### ISSUE THREAD

**Issue by cyprusglobe** [dimsav/laravel-translatable#176]
@dimsav  i have a form with a field for name in english and a field for name in spanish

what is the best way to add them to their respected locale
i have a product with a name when i add a new product do i have to have 2 input field for the product 1 for spanish and 1 for english or?

can someone help me out please?

**Comment by dimsav** [comment]
Hi @cyprusglobe 

it's up to you how you're going to input the translations. One form? Multiple forms? It's totally up to you.

The only think I can help you with is the db structure. Make sure you add a model `Product` and a model `ProductTranslation` with the appropriate tables.
