### ISSUE TITLE
country based fallback

### ISSUE THREAD

**Issue by alvinmok** [dimsav/laravel-translatable#177]
if country based fallback is not available, it returns null instead of the default fallback.

**Comment by alvinmok** [comment]
I got what I want by modifying line 68 of Translatable.php, thanks!
i.e. it falls back from zh-hk to zh, and then en

```php
        } elseif ($withFallback
            && $this->isLocaleCountryBased($locale)
            && $this->getTranslationByLocaleKey($this->getFallbackLocale($fallbackLocale))
        ) {
            $translation = $this->getTranslationByLocaleKey($this->getFallbackLocale($fallbackLocale));
        } else{
```

**Comment by dimsav** [comment]
Hi mate, I ran some tests and it seems that there is no issue with the code. Can you please share the code reproducing the issue?
