### ISSUE TITLE
Working with factories

### ISSUE THREAD

**Issue by redgluten** [dimsav/laravel-translatable#180]
I may be misguided but after reading the docs there is no mention on making this (awesome) package work with factories. I suppose this is not a trivial issue and I’m not sure that I can be of any help to implement it but I’m still willing to if someone can clarify this and suggest some starting point.

**Comment by dimsav** [comment]
Well, the factory of a model is dependant of the model itself. What information are you looking for?

**Comment by AkibaTech** [comment]
I also need help here too!

Are there best practises when defining factories working with laravel-translatable?

For example, I've a table named "news" and an other named "news_translations" with a title and a body. How can I simply define it?

**Comment by dimsav** [comment]
@AkibaTech I don't understand your question. Have you read the docs on the readme file?

**Comment by AkibaTech** [comment]
@dimsav It's quite simple, Laravel provide a good way to make factories for our models.

Example : Previously (before laravel-translatable) I had to manage my factory for my model called News : 

```php
$factory->define(App\News::class, function (Faker\Generator $faker) {
    return [
        'title' => $faker->words(rand(2,4)),
        'body' => $faker->paragraph(rand(250,450)),
    ];
});
```

Now, laravel-translatable has been installed and I want to create a factory for my news translations model. I tested something like that but I'm pretty sure there's a better way to achieve it for all of my locales (currently, locale hardcoded).

```php
$factory->define(App\NewsTranslations::class, function (Faker\Generator $faker) {
    return [
        'locale' => 'en',
        'news_id' => factory(App\News::class, 1)->create()->id,
        'title' => $faker->words(rand(2,4)),
        'body' => $faker->paragraph(rand(250,450)),
    ];
});
```

The documentation does not seem to provide informations about that.

Thank you! (Is it clear enough :D ?)

**Comment by ovp87** [comment]
@AkibaTech from what i understand you would need to add a seperate factory for the translations, then do somthing like:

´´´
$users = factory(App\User::class, 3)
           ->create()
           ->each(function($u) {
                $u->posts()->save(factory(App\Post::class)->make());
            });
´´´

**Comment by vcarreira** [comment]
@AkibaTech When calling your original News factory you can simply override with the intended translations:

```
factory(App\News::class)->create([
    'title:en' => 'creates an english title',
    'body:en' => 'creates an english body',
]);
```

You can even provided multiple translations at once:
```
factory(App\News::class)->create([
    'title:en' => 'creates an english title',
    'body:en' => 'creates an english body',
    'title:pt-PT' => 'cria um titulo',
    'body:pt-PT' => 'cria um corpo',
]);
```

If you have a default locale set, calling:
`factory(App\News::class)->create(); `

will create a new record on the table news and another on news_translations.

**Comment by jadsalhani** [comment]
So I'm having the issue of 

`PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "name" violates not-null constraint`

When using a ModelFactory of my Translatable model in Unit Tests. The translatable field is`name`

I've tried to setup like the answer above but to no luck

Any help or indication how I can setup the modelfactory to recognize the translatable field?

Thanks!
