### ISSUE TITLE
Select specific column for translated entity

### ISSUE THREAD

**Issue by simonfunk** [dimsav/laravel-translatable#181]
Hi Dimitris :)

How can i select a specific column of a translated entity?
Because i wanna output a json for my API and don't wanna output id and created_at etc.

**Comment by dimsav** [comment]
Yo! It seems that your question is more like a generic laravel/php question. You can define how your responses look like by using transformers. Check [this](http://fractal.thephpleague.com/transformers/) for example.

**Comment by camelscript** [comment]
I think there is no such select('name') to select particular column. Instead i use Collection::pluck('name') to get only name column.
