### ISSUE TITLE
Implementation of orWhereTranslation scope?

### ISSUE THREAD

**Issue by starovoitovs** [dimsav/laravel-translatable#182]
Hello Dimitris,

usually there is an orWhere scope that provides possibility to join disjunctive WHERE clauses. I wouldn't mind implementing it, if this functionality is not already implemented (it's likely I just missed it, how to logically replace this functionality). But even if it is implemented, it wouldn't hurt to provide this method by analogy, for syntactic sugar.

**Comment by dimsav** [comment]
I don't follow. Can you give an example?
