### ISSUE TITLE
provide an replicateWithTranslations function

### ISSUE THREAD

**Issue by simonfunk** [dimsav/laravel-translatable#185]
Hi Dimitris

I've tried to implement a replicate function to the asgard cms. my main problem is now, that the 'locale' column is not a fillable column so it does not allow me to make the replication. i know i could allow this in the config, but that's a security risk and i will provide the duplicate function to all modules for asgard cms so everyone has it. i think it would be anyway helpfull if the the translatable module would provide this.
Or do you have any advice?

Cheers

**Comment by dimsav** [comment]
Hey! 

What do you mean by replication? Show some code.

**Comment by simonfunk** [comment]
well, i already tried many ways but here the probably most closest:
for example, $mymodel->replicate() doesn't replicate the translations.
so one way looked like that:
```
        $duplicatedEntity = $this->infobox->find($infoboxId)->replicate();
        //it replicates also the relation, but the id's and foreign key ids are already set to the origin so no change applied
        $translations = [];
        foreach($duplicatedEntity->translations as $translation)
        {

            $except = [
                $translation->getKeyName(),
                $translation->getCreatedAtColumn(),
                $translation->getUpdatedAtColumn(),
            ];

            $attributes = array_except($translation->getAttributes(), $except);

            $translations = [
                $InfoboxTranslation(attributes);
            ];
            with($duplicatedEntity)->setRawAttributes($attributes);

        }
        $duplicatedEntity->name = $request->get('code');
        $duplicatedEntity->code = $request->get('name');
        $duplicatedEntity->save();
```
The problem now here is, that the local column is not fillable.

**Comment by dimsav** [comment]
Have you [googled](https://www.google.com/search?q=laravel+replicate+relationships) for this?

This is a generic laravel question. I didn't even notice there was a replicate() method :P

Are you eager-loading the translations first? (No idea if this will solve the issue)

**Comment by simonfunk** [comment]
Yeah of course ;)
![image](https://cloud.githubusercontent.com/assets/8578044/11442772/5b32be2e-9518-11e5-8917-d06409d45197.png)

You see, all already read articles.
As i wrote i tried several things, as well eager-loading. Loading is not the problem, the problem i can not save it from my controller, cause then i get a constrain because "locale" can not be empty and is not permitted cause it's not fillable. so it would makes sense that the translatable package provides it ;)

**Comment by dimsav** [comment]
Thanks to @Propaganistas, a solution will come soon.

**Comment by simonfunk** [comment]
ah ok, so i'm looking forward to it :)

**Comment by simonfunk** [comment]
so, i've done it and made a PR for it ;)
https://github.com/dimsav/laravel-translatable/pull/199
