### ISSUE TITLE
Translatable 4.4.x tutorial

### ISSUE THREAD

**Issue by afujita** [dimsav/laravel-translatable#187]
Hi there,

Do you still have the 4.4.x version tutorial?
I built a site in laravel 4.2 sometime ago and linking to a database just now.

Will appreciate any help.

**Comment by dimsav** [comment]
Yes everything is in git. Go to the [tags](https://github.com/dimsav/laravel-translatable/releases) page and choose 4.4. Then navigate to the readme file.

**Comment by afujita** [comment]
Thank you very much!
