### ISSUE TITLE
Package of interest

### ISSUE THREAD

**Issue by Propaganistas** [dimsav/laravel-translatable#188]
Hi

I just created a package to have BootForms work flawlessly with your Translatable package.
https://github.com/Propaganistas/Laravel-Translatable-Bootforms

Maybe you could add a reference in Translatable's README if you like since this is a rather common use case for many developers.

Cheers.

**Comment by dimsav** [comment]
Will definitely link to it as soon as it gets more stable. (no tests are implemented)

**Comment by dimsav** [comment]
will close this for now but feel free to ping me. Your contributions is very welcome!

**Comment by Propaganistas** [comment]
There you go, tests are implemented now.

**Comment by dimsav** [comment]
Nice job

**Comment by sdebacker** [comment]
I made a simpler package for the same purpose: https://github.com/TypiCMS/TranslatableBootForms
But no tests for the moment.

**Comment by sdebacker** [comment]
@Propaganistas I see you referenced my package for the logic of the FormBuilder@getModelValue(). Nice.

**Comment by Propaganistas** [comment]
@sdebacker Yes indeed. I first started using your package, but then realized there exists a lot of code duplication by defining (or looping) fields for each locale.
My package is an attempt to solve this as noted in the readme.

Thanks for the inspiration.

**Comment by sdebacker** [comment]
@Propaganistas yes, it depend on how the fields are displayed in the form (grouped by locale or by column) Does your package allow to group fields by locale ? By the way, I realize that it's probably better to group it by column like your package does by default.

**Comment by Propaganistas** [comment]
@sdebacker No it does not. Moreover, Grouping by locale is simply not achievable when using a form builder package since the class should then be aware of the entire form.

Let's continue any further comments in the issue tracker of the package instead of polluting laravel-translatable.

**Comment by dimsav** [comment]
Let's leave the issue open as a reminder for me to update the readme.

**Comment by dimsav** [comment]
[Done](https://github.com/dimsav/laravel-translatable#add-ons)
