### ISSUE TITLE
all(); method

### ISSUE THREAD

**Issue by afujita** [dimsav/laravel-translatable#189]
Hi there,

Sorry for bothering you again.
I am using the first(); method following your tutorial to retrieve the translation from the database, and everything is working fine, but when I change to all(); method, it retrieves with and error: Undefined property: Illuminate\Database\Eloquent\Collection::$text.
Could give me any clue to solve this issue.
Thanks again.

**Comment by dimsav** [comment]
Can you paste some code? Impossible to debug otherwise.

**Comment by afujita** [comment]
Hi Dimitris,

It was just a matter of querying, thanks for your answer again.

On Sat, Dec 5, 2015 at 12:53 AM, Dimitris Savvopoulos <
notifications@github.com> wrote:

> Can you paste some code? Impossible to debug otherwise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimsav/laravel-translatable/issues/189#issuecomment-162003081>
> .
>



-- 
藤田アレシャンドレ勉

-------------------------------------
トゥピニキーン・エンターテイメント株式会社
Tupiniquim Entertainment Co. Ltd.
〒130-0015 東京都墨田区横網2−6−2 3F
代表 (03)5637-5469  |  直通 (03)5637-5481
Website: http://www.tupiniquim.jp
Email: afujita@tupiniquim.jp
-------------------------------------

**Comment by joshbrw** [comment]
Looks like you were trying to do `$results->text`, which won't work. You
need to `foreach` over the results, or use any of the `Collection` methods
to retrieve a specific instance. :)

**Comment by kasungihan** [comment]
I have to same problem,

$users = User::first();
		//dd($user);
		//dd($users->depart);
		if ($users) {
			//dd($user->userl);
			foreach($users->depart as $user) {
				echo $user->fname;
				echo $user->departments;			
			}		
		} else {
			echo 'error';
		}
