### ISSUE TITLE
Translated attributes with application locale won't work

### ISSUE THREAD

**Issue by hiendv** [dimsav/laravel-translatable#192]
![screenshot from 2015-12-10 15-01-24](https://cloud.githubusercontent.com/assets/1917947/11710054/0a3dcca2-9f4f-11e5-901c-f02d26ec7516.png)

The category's name should be `Bar` I guess. Am I missing something ?

**Comment by dimsav** [comment]
we are no magicians

**Comment by hiendv** [comment]
@dimsav Why, buddy? The example is even in the readme?

**Comment by dimsav** [comment]
We need some code to understand what produces the error, how would we know otherwise?
