### ISSUE TITLE
setLocale retrieves data from db only after switching language

### ISSUE THREAD

**Issue by afujita** [dimsav/laravel-translatable#193]
I have a mix of Translatable and native Laravel Localization setup in my bilingual site (ja and pt)
Everything is working fine except that it is not loading the translations stored in database if I do not switch the language for the first time.

Here is my HomeController (where I retrieve translations from db):

    app()->setLocale(Session::get('locale'));	
	    $evento = Evento::whereBetween('id', array(4, 5))->orderBy('id', 'desc')->get();
		return View::make('home')
		->with('evento', $evento);

Here is my LanguageController (used to retrieve translations from lang app)

    	public function chooser () {
		Session::set('locale', Input::get('locale'));
		return Redirect::back();
	}
Here are my models

    // Evento.php
    class Evento extends Eloquent {

	use \Dimsav\Translatable\Translatable;

	public $translatedAttributes = array('event_title', 'start_date', 'week', 'open', 'start', 'title', 'sumary', 'carousel', 'entrance', 'venue', 'artists', 'performer', 'venue_url');
    }

    // EventoTranslation
    class EventoTranslation extends Eloquent {
    public $timestamps = false;
    }

Can you help me with this?
Thanks again.

**Comment by dimsav** [comment]
What is the issue here? This: `app()->setLocale(Session::get('locale'));` ?

**Comment by afujita** [comment]
Added setLocale to start/global.php and its working now.
Thank you.
