### ISSUE TITLE
getNewTranslation() executes a useless query

### ISSUE THREAD

**Issue by koichirose** [dimsav/laravel-translatable#194]
Survey model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    use SoftDeletes, \Dimsav\Translatable\Translatable;

    public $translatedAttributes = ['name'];

    protected $fillable = [
        'start_at',
        'end_at',
    ];
}
```

SurveyTranslation model:
```php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class SurveyTranslation extends Model
{
    public $timestamps = false;

    protected $fillable = [
        'name',
        'locale',
    ];
}
```

Test route:
```php
        Route::get('ttest', function() {
            $s = new \App\Models\Survey;
            $s->getNewTranslation('en');
        });
```

This should execute 0 queries, but runs this one instead:
```
select * from `survey_translations`
where `survey_translations`.`survey_id` is null
and `survey_translations`.`survey_id` is not null
```

Apparently, this won't be executed if I interrupt execution before 'add' is called on the translations collection here:
https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L425

I don't understand what's happening...

**Comment by koichirose** [comment]
@dimsav ?

**Comment by argb** [comment]
@koichirose 
public function getNewTranslation($locale)
    {
        $modelName = $this->getTranslationModelName();
        $translation = new $modelName();
        $translation->setAttribute($this->getLocaleKey(), $locale);
        $this->translations->add($translation);

        return $translation;
    }

Have you seen $this->translations->add($translation); ?
it's because $this->translations <=> ($this->translations())->add($translation);
Have you got it? $this->translations() will issue a query for the associated survey_translations table.

**Comment by koichirose** [comment]
I don't understand your question.
That code is from this package itself.
I have:
this->translations->add($translation);

**Comment by koichirose** [comment]
Anyone?

**Comment by dimsav** [comment]
Hey mate, sorry for replying with delay. 

What makes this extra query is not the add() method, but `$this->translations`. 

`$this->translations` is run by laravel magic and if you debug a little bit you'll see that it [fetches](https://github.com/illuminate/database/blob/941c80358ebbc8723af62ab39df44342ca78eaa8/Eloquent/Model.php#L2731) the existing relationships. 

Maybe there is a workaround for this. Feel free to recommend any changes.

**Comment by koichirose** [comment]
Hmm I have no idea.
Since you need to add the newly created translation to the existing $this->translations collection, it doesn't look like there could be a workaround for this.
I'll try to limit the usage of this as much as possible.
