### ISSUE TITLE
Problem with relationship

### ISSUE THREAD

**Issue by Mdpproduction** [dimsav/laravel-translatable#196]
Good evening,
i've a question, if i try to get a relationship like this, from a model:

```php
	public function tabs()
	{
		return $this->hasMany('ProductTab');
	}
```
i notice that when i try to display the results:

```php
	@foreach($model->tabs as $tab)  
	{{ $tab->title }}
	@endforeach
```

the translation associated to that model does not appear. It's like if the translations was not loaded. Any suggestions ?

**Comment by koichirose** [comment]
did you setup the tabs model correctly and are you eager loading translations in there?

**Comment by Mdpproduction** [comment]
I setup the model correctly, with the trait, and the table on my DB are set correctly too, like the documentation said. Maybe the problem is on eager loading. But i don't know why doesn't works. I need to eager loading the trandlations on the relationship right?

**Comment by koichirose** [comment]
Yes, you need to add this:
    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    // (optionaly)
    // protected $with = ['translations'];

**Comment by Mdpproduction** [comment]
Oh my bad again. You're right thanks man!

**Comment by Mdpproduction** [comment]
I tried, but doesn't works. The point is that the relationship return a query builder. Where am i wrong ?

**Comment by koichirose** [comment]
You should post some more code (model, controller...)

**Comment by Mdpproduction** [comment]
I fix my problem with this join inside the relationship:

```php
->join('product_tab_translations as ptt', 'ptt.product_tab_id', '=', 'product_tabs.id')
					->where('locale', App::getLocale());
```

From my controller i just find the parent model, and then i call the $model->tabs, like i show you before.

**Comment by koichirose** [comment]
Hmm I still don't know your exact structure, but laravel-translatable should be used exactly to avoid querying the translations table manually.

**Comment by Mdpproduction** [comment]
Oh finally works fine. I'm so sorry @koichirose, you're right, again, it's my fault. Damn!! :D SOrry again
