### ISSUE TITLE
advices for getTranslationOrNew

### ISSUE THREAD

**Issue by argb** [dimsav/laravel-translatable#197]
```php
protected function getTranslationOrNew($locale)
    {
        if (($translation = $this->getTranslation($locale, true)) === null) {
            $translation = $this->getNewTranslation($locale);
        }

        return $translation;
    }
```

I suggest that change getTranslation($locale, false) to getTranslation($locale, true).

if second param is false,even if i set a fallback_locale,i can't work correctly to get what i want data.
for example,Here there is a model Teacher,and has $teacher->students relationship,before i get $teacher->student,I make a assignment like this,$teacher->student=process($teacher->student).
note here,because this assignment used getTranslationOrNew, So my locale_fallback don't work,if i supposed to get zh_CN ,and fallback for en_US,but in fact i got a empty zh_CN instance. This is not a right behavior.

I met a weird behavior when i call getTranslationOrNew after

**Comment by dimsav** [comment]
The method was created to meet some internal requirements (that's why it is protected). Sorry for the confusion
