### ISSUE TITLE
Generating a select box

### ISSUE THREAD

**Issue by swimlappy** [dimsav/laravel-translatable#198]
Hi,

Given the Country table in the demo, what is the simplest way to generate a select box of id, name for a list of countries?  The method ```Country::lists('name', 'id')->toArray()``` isn't available.  I do see a ```listsTranslation()``` method, but that returns an array of arrays that isn't usable in ```Form::select```, unless you iterate through it prior and build a proper array of the values.

Thank you for this package.  It is quite interesting and I'm having fun playing around with it.

**Comment by joshbrw** [comment]
:+1: would like to know this too

**Comment by WrongWay** [comment]
Stumbled upon this too these days. This is what I use as a workaround:
```php
    $country_list = Country::listsTranslations('name', 'id')->get();

    foreach($country_list as $country)
    {
        $countries[$country->id] = $country->name;
    }
```

**Comment by swimlappy** [comment]
@WrongWay Thanks.  That's what I'm currently doing.  I agree with your last statement.  Perhaps a new method could be added.

**Comment by slano** [comment]
Can't you use `Country::get()->lists('name','id')->all()`?

**Comment by swimlappy** [comment]
@slano  indeed you can, that works.  That is the kinda of shortcut I was looking for, thanks.

**Comment by slano** [comment]
@swimlappy Perfect! I'm glad it helped.
