### ISSUE TITLE
Translation not working wiht Baum node

### ISSUE THREAD

**Issue by isomis** [dimsav/laravel-translatable#200]
I have a model extends node with this boot function:

    public static function boot() 
    {
        parent::boot();

        static::moving(function($node) {
          // YOUR CODE HERE
        });

        static::moved(function($node) {
          // YOUR CODE HERE
        });
    }

Translation is not working with parent::boot();

When i remove it, it works. But node is not working anymore. Is there a workaround?

**Comment by lotestudio** [comment]
I have issues too. And found solution for some of them.
First: When create record and saved in model saved event Baum has method setDepth() which reload the model and we loose translations from memory. The solution is to store translations before saving the model, something like this:
    
    public function save(array $options = [])
    {
        //!!!store translations to prevent deleting from model events...
        $translations = $this->translations;


        if ($this->exists)
        {
            if (count($this->getDirty()) > 0)
            {
                // If $this->exists and dirty, parent::save() has to return true. If not,
                // an error has occurred. Therefore we shouldn't save the translations.
                if (parent::save($options))
                {
                   //!!!get translations back
                    $this->translations = $translations;
                    return $this->saveTranslations();
                }

                return false;
            } else
            {
                // If $this->exists and not dirty, parent::save() skips saving and returns
                // false. So we have to save the translations
                if ($saved = $this->saveTranslations())
                {
                    $this->fireModelEvent('saved', false);
                }

                return $saved;
            }
        } elseif (parent::save($options))
        {
            //!!!get translations back
            $this->translations = $translations;
            // We save the translations only if the instance is saved in the database.
            return $this->saveTranslations();
        }

        return false;
    }


It's not so good but work for me. Do you found some other issues?
