### ISSUE TITLE
setAttribute breaks method chaining

### ISSUE THREAD

**Issue by oneminutefly** [dimsav/laravel-translatable#201]
According to laravel docs Model's setAttribute method returns $this.
https://laravel.com/api/5.1/Illuminate/Database/Eloquent/Model.html#method_setAttribute

Translatable->setAttribute(...) returns null (no return)

**Comment by dimsav** [comment]
Thanks for your feedback! [This change](https://github.com/illuminate/database/commit/5be10adce6a11261e9e12d4eab7c6c27885f1fe4#diff-ea23035e94022c6bdbca2a2cd7647ee0R2879) was added on September, the only way to keep the package up to date is thanks to contributors like you :)

**Comment by dimsav** [comment]
Added [here](https://github.com/dimsav/laravel-translatable/commit/e527dc68c1119d721b5b32956ee63333d825a7e4). Thanks!
