### ISSUE TITLE
One translation model for multiple models with polymorphic (morphMany) relationship

### ISSUE THREAD

**Issue by abhishek238** [dimsav/laravel-translatable#202]
I just wanted to suggested that it would be better if we can store all the translation in single model, so that we don't have to create tables for each model,

**Comment by huglester** [comment]
Hello,

I just came to this package and similar thing came to my mind.

We would have a single table for all the translations. Which would be really awesome.

Do you have any plans for this? Or maybe saw somewhere similar package?

Thank you!

**Comment by dimsav** [comment]
Thanks for your feedback guys. There are many reasons why I chose to have a new translation table for each model. This architecture belongs to the core of the package and it's not in my plans to change it. If we change it, we would have to delete the whole package and start from scratch.

It may be a bit of extra work when setting things up, but on long term you have more benefits.

I am not aware of a package that uses 1 table for all translations, sorry.
