### ISSUE TITLE
Tests break on Laravel 5.2

### ISSUE THREAD

**Issue by dimsav** [dimsav/laravel-translatable#207]
For some reason tests fail on travis-ci when illuminate/support version 5.2 is used. However I have no problem when running these locally: https://travis-ci.org/dimsav/laravel-translatable/jobs/101381089

Does anyone have an idea what could be the reason for this?

cc @sdebacker @nWidart @freekmurze

**Comment by Propaganistas** [comment]
Suggestion: use an in-memory database during testing to be platform agnostic and simply omit such errors.

See [here](https://github.com/Propaganistas/Laravel-Auth-Context/blob/master/tests/TestAuthContext.php#L36) for an example.

**Comment by nWidart** [comment]
I haven't upgraded to 5.2 yet but 

```
PDOException: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```
Sounds like a mysql strict mode issue no ?

**Comment by dimsav** [comment]
@Propaganistas thanks for the reply. Using an in-memory database from my experience is a bad practice because it doesn't protect you 100% from introducing bugs. Also, the reason I opened this issue is to find out what causes the error when laravel 5.2 is used. The tests run fine with laravel 5.1.

@nWidart as you can see in the .travis file, the only thing that changes is the illuminate/support version and the correspondant testbench version. 

... Maybe testbench is doing nasty stuff when setting up the laravel environment.

**Comment by nWidart** [comment]
Ok, but `Incorrect table definition` is a strange error to be introduced by only having support + testbench updated.
Maybe @crynobone knows what this happens.

**Comment by freekmurze** [comment]
I'm just guessing here, but maybe Travis update their default mysql version? In version 5.7 strict mode is on by default.

**Comment by crynobone** [comment]
Laravel 5.2 change some logic with `$table->timestamps()`, I personally choose to swap with `nullableTimestamp()` for my project.

**Comment by crynobone** [comment]
There actually nothing new in Testbench, other than bringing support to the new group middleware and support for installing 5.2

**Comment by dimsav** [comment]
Looks like a travis error :(

Thank you all for your feedback!
