### ISSUE TITLE
Laravel 5.2 empty translations table

### ISSUE THREAD

**Issue by zgabievi** [dimsav/laravel-translatable#210]
I'm trying to insert some data:

```php
$data = [
  "en" => [
    "title" => "1",
    "description" => "<p>1</p>"
  ],
  "ru" => [
    "title" => "2",
    "description" => "<p>2</p>"
  ],
  "ka" => [
    "title" => "3",
    "description" => "<p>3</p>"
  ],
  "slug" => "1",
  "logo" => "uploads/store/1453042305.png"
];
```

in table named `providers` using my `Provider` model's `create` method. But only `providers` table is getting filled, `provider_translations` table is empty.

Here is my files:
`\App\Provider.php`:

```php
<?php

namespace App;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use App\Translations\ProviderTranslation;

class Provider extends Model
{
	use Translatable;

	/**
	 * @var bool
	 */
	public $timestamps = false;

	/**
	 * @var array
	 */
	public $translatedAttributes = [
		'title',
		'description',
	];

	/**
	 * @var array
	 */
	protected $fillable = [
		'slug',
		'cover',
		'logo',
	];

	/**
	 * @var
	 */
	public $translationModel = ProviderTranslation::class;
}
```

`App\Translations\ProviderTranslation.php`:

```php
<?php

namespace App\Translations;

use Illuminate\Database\Eloquent\Model;

class ProviderTranslation extends Model
{
	/**
	 * @var bool
	 */
	public $timestamps = false;

	/**
	 * @var array
	 */
	protected $fillable = [
		'title',
		'description',
	];
}
```

I have tried **Saving translated attributes** instruction from `Readme.md` but i'm getting same result. Can anyone help me?

**Comment by lotestudio** [comment]
Same with me. After updating to 5.2.11!

**Comment by taai** [comment]
I just struggled with this too. I don't know why (probably because previously I was using another package), but I didn't assign the **translatable fields** in the **main model**, but you **must do** that this to work.
Read again the README: https://github.com/dimsav/laravel-translatable#step-3-models

So, in your case in the class ```Provider``` must include also translatable fields in the ```$fillable``` property!

Replace this
```php
protected $fillable = ['slug', 'cover', 'logo'];
```
with this
```php
protected $fillable = ['slug', 'cover', 'logo', 'title', 'description'];
```


By the way, I'm using Laravel 5.2.14.

**Comment by zgabievi** [comment]
Thanks, I will try it. ;)

**Comment by dimsav** [comment]
@zgabievi can we close this?

**Comment by zgabievi** [comment]
Yeap close it. Thank you
