### ISSUE TITLE
wheretranslation not having expected result?

### ISSUE THREAD

**Issue by Philwn** [dimsav/laravel-translatable#211]
I have an articles and an articles_translations table.

Articles

id | created_at | updated_at
------------|------------|------------|
1 | 2016-01-19 11:43:52 | 2016-01-19 11:43:52
2 | 2016-01-19 11:43:52 | 2016-01-19 11:43:52

articles_translations

id | article_id | locale | name | slug | excerpt | text 
------------|------------|------------|------------|------------|------------|------------|
1 | 1 | en | article 1 | article-1 | excerpt | text |

I may be wrong but I expected the below code to return the article with the given slug. below code returns a SQL error as 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translation' in 'where clause' (SQL: select * from `articles` where `translation` = slug limit 1)
```

Code:
```
Route::get('{locale}/articles/{slug}', function($locale, $slug) {
    app()->setLocale($locale);

    $article = Article::whereTranslation('slug', $slug)->first();

    return $article;
});
```

obviously there isn't a translation field. Am I missing something?

**Comment by Philwn** [comment]
I have solved my problem with the following

```
public function show($locale, $slug)
    {
        app()->setLocale($locale);
        $article = Article::whereHas('translations', function ($query) use ($slug, $locale) {
            $query->where('locale', $locale)
            ->where('slug', $slug);
        })->first();


        echo "<h1>".$article->name."</h1>";
        echo $article->text;
    }
```

Maybe I misunderstood the purpose of whereTranslation?

**Comment by dimsav** [comment]
Check the code inside the translatable trait and check if the scope is set. If not, you are using an older version of the package and should update.
