### ISSUE TITLE
Laravel 5 Validations

### ISSUE THREAD

**Issue by AEK-BKF** [dimsav/laravel-translatable#212]
Hi, 
Thanks a lot for this nice package.
I'm using Laravel 5.1, please is there a way to validate fooTranslation attributes ? 
For example I have the attribute 'name' required and unique in 'foo' model, so how can I update it with this validation ?
Example :

_class Foo extends Model
{
    use  Translatable;  
    protected $table = 'foos';
    public $translatedAttributes = ['name', 'description'];_

**Comment by Philwn** [comment]
Does the normal Laravel Validation not work for this?

https://laravel.com/docs/5.1/validation

**Comment by sdebacker** [comment]
You should use the dot notation like fr.name, en.name, de.name or with laravel 5.2 you can use the star : *.name, *.description

**Comment by AEK-BKF** [comment]
Thanks for answer @sdebacker 
Please could you post an example ^^

**Comment by sdebacker** [comment]
Using a [Form Request](https://laravel.com/docs/5.2/validation#form-request-validation) class:

```php
class FormRequest extends AbstractFormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            '*.name'        => 'max:255|required',
            '*.description' => 'required',
        ];
    }
}
```

**Comment by AEK-BKF** [comment]
Thanks a lot,
but what about unique validation ? for example the **name**  is it unique for model **Foo** or **FooTranslation** ?

**Comment by asisti2-pruebas** [comment]
I have '*.slug' rule in a translatable model. I want validate if its unique combination 'locale' and 'slug' how can i do that:
'*.slug' => 'required|unique:category_translations,slug,NULL,id,locale,'.?¿?¿?¿¿

Thanks

**Comment by ovp87** [comment]
> have slug rule in a translatable model. I want validate if its unique combination 'locale' and 'slug' how can i do that:
> '*.slug' => 'required|unique:category_translations,slug,NULL,id,locale,'.?¿?¿?¿¿
> 
> Thanks

@asisti2-pruebas have a look at https://github.com/felixkiss/uniquewith-validator/

**Comment by dimsav** [comment]
please check the laravel docs for validation.

**Comment by hugofabricio** [comment]
I use '*.title' to validate title, it validated normally, but it creates other fields .title that exist in the table.

<img width="261" alt="captura de tela 2016-10-07 as 15 45 07" src="https://cloud.githubusercontent.com/assets/425678/19201670/25f88f06-8ca5-11e6-85dc-4cde44d1cbbb.png">

**Comment by notflip** [comment]
Did you find a solution to thisissue @hugofabricio

**Comment by anaisabel19886** [comment]
I came up with this solution:

<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class CreatePageRequest extends FormRequest {

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules() {

        $locales = config('translatable.locales');

        $page = [
            //  
            'order' => 'sometimes|nullable|integer|min:0',
            'starred' => 'sometimes|boolean',
            'image_id' => 'sometimes|integer|exists:images,id',
            'page_id' => 'sometimes|integer|exists:images,id',
            'view_id' => 'required|integer|exists:views,id',
        ];

        $trans = [];

        foreach ($locales as $locale) {
            $trans = $trans + [
                $locale . '.title' => 'required|string|min:3|max:60',
                $locale . '.description' => 'required|string|min:3|max:155',
                $locale . '.slug' => 'required|string|min:3|max:200|unique',
            ];
        }

        return $page + $trans;
    }

}

this should return the required complete array for validationr

**Comment by notflip** [comment]
Has anyone found a solution on how to validate uniqueness?

**Comment by stefkes** [comment]
@anaisabel19886 Validation rule unique requires at least 1 parameters

You're missing the table name

**Comment by anaisabel19886** [comment]
@stefkes 
duh! you are absolutely right! :)

Anyway, I ended up making a custom validator since I needed something more specific..

**Comment by arturmamedov** [comment]
I see i late, but maybe it can help someone in the future.

For validate translatable fields with unique,
in Laravel 5.3 i can use this custom syntax for unique, and it working:


```php
public function rules()
{
    return [
        'ru.name' => 'required|max:255',
        'ru.slug' => [
            'required',
            'max:255',
             Rule::unique('category_translations', 'slug')
                 ->where(function ($query) {
                     $query->where('locale', 'ru');
                 })
        ]
    ]
}
```

@stefkes If you've found something in this time, I would be curious and happy to see it. Thanks!

**Comment by stefkes** [comment]
@arturmamedov - I had a solution but I replaced it with your much cleaner method.

**Comment by Gummibeer** [comment]
To bring this up again: do you think that we should have a validation rule in this package? Or provide a validation package for this one?
And if so: which cases should be covered/possible with the rule?

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
