### ISSUE TITLE
Get all translations of content by id

### ISSUE THREAD

**Issue by petyots** [dimsav/laravel-translatable#213]
Hi, i have little issue here i can't figure out how can i get all the translations of content by id for example i have two tables
````
--pages
--pages_translations

````
Pages holds active updated_at etc... and translations holds slug,title,body... I tried with 
````
        $pages = Page::where('id',$id)->translatedIn(['bg','el','en'])->get()->toArray();
````
This code return empty array and execute the following SQL statement 
````
select * from `pages` where `id` = '4' and exists (select * from `page_translations` where `page_translations`.`page_id` = `pages`.`id` and `locale` = 'bg')
````
So i can't understand how can i get the translations of particular id not only the default.
My fallback and current locale is bg if this matter. Thanks in advance @dimsav

**Comment by 4unkur** [comment]
Same problem here  
code: 
```php
    public function edit($id)
    {
        $news = News::where('id', $id)->translated()->get();
    }
```
returns `News` model with no translated fields. How can they be retrieved?  
I'm using laravel form model binding.
```blade
        {!! Form::model($news, ['route' => ['admin.news.update', $news->id], 'method' => 'put']) !!}
```

Any help would be appreciated.

**Comment by dimsav** [comment]
> `$pages = Page::where('id',$id)->translatedIn(['bg','el','en'])->get()->toArray();`
> This code return empty array and execute the following SQL statement

Translated in accepts a string as an argument, not an array.

> returns News model with no translated fields. How can they be retrieved?

Use eager loading: https://laravel.com/docs/5.1/eloquent-relationships#eager-loading

**Comment by 4unkur** [comment]
Thanks @dimsav !

**Comment by Gummibeer** [comment]
From readme:

```
// To set the translation for a field you can either update the translation model.
// Saving the model will also save all the related translations.
$germany->translate('en')->name = 'Germany';
$germany->save();

// Alternatively we can use the shortcut
$germany->{'name:en'} = 'Germany';
$germany->save();

// There are two ways of inserting mutliple translations into the database
// First, using the locale as array key.
$greece = $country->fill([
    'en'  => ['name' => 'Greece'],
    'fr'  => ['name' => 'Grèce'],
]);

// The second way is to use the following syntax.  
$greece = $country->fill([
    'name:en' => 'Greece',
    'name:fr' => 'Grèce',
]);
```
