### ISSUE TITLE
Polymorphic translation table

### ISSUE THREAD

**Issue by gregoriohc** [dimsav/laravel-translatable#214]
Hi!
I was looking for a translations package and I have found that yours it's maybe the best one.
There is only one thing that I don't like, that I have to create a new table for each model I want to translate.
Why are you not using Laravel [polymorphic relations](https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations) so you can use only one table for all models translations? Is there a reason? Performance maybe?
I'm going to fork your repository to implement polymorphism, but before doing it I want to know if you have any plans of implementing it by yourself in a short term?
Thanks!

**Comment by dimsav** [comment]
Hey @gregoriohc!

Thanks for the feedback. Unfortunately there is no plan to switch to switch to polymorphic relations. Actually this package was fundamentally built using 1 table for each model for many reasons. Having to to create an extra table for each model is indeed some extra work but in the long term it totally makes sense, especially for performance reasons.

I appreciate your effort to improve the package, however submitting a PR that attempts to change that won't be accepted.
