### ISSUE TITLE
scopeWhereTranslationLike does not exist.

### ISSUE THREAD

**Issue by kanazaca** [dimsav/laravel-translatable#215]
HI @dimsav,

I have noticed that you implemented  a scope called WhereTranslationLike, but you forgot to make a new release with that functionality, can you do that please ?

Thanks a lot.

**Comment by dimsav** [comment]
Done! I didn't forget it, we had some issues with the tests but all is fine now. Enjoy!

**Comment by johanbgoode** [comment]
Maybe I misinterpreted this functionality, but: 

`>>> App\Article::whereTranslation('title', 'test')->first();
=> App\Article {#722
     id: 6,
     created_at: "2016-02-05 15:33:56",
     updated_at: "2016-02-05 15:33:56",
   }
>>> App\Article::whereTranslationLike('title', '%est')->first();
Illuminate\Database\QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translation_like' in 'where clause' (SQL: select * from `articles` where `translation_like` = title limit 1)'
>>> `
