### ISSUE TITLE
Timestamps not being updated

### ISSUE THREAD

**Issue by junkystu** [dimsav/laravel-translatable#216]
Hi,

When a model has its translations updated, the timestamp `updated_at` field, which lives on the parent model, does not get updated unless you update a column on the parent model too.

I know that a possible workaround would be to use parent [timestamps touching](https://laravel.com/docs/5.2/eloquent-relationships#touching-parent-timestamps) on the corresponding translation model but, I also wonder if this should be done by default given that the parent model's events also fire?

**Comment by dimsav** [comment]
I wouldn't do that a custom behavior because that would be against performance. You are free to customize on your installation if you want.
