### ISSUE TITLE
Isn't it good idea to use events instead of overriding save method

### ISSUE THREAD

**Issue by domesticlion** [dimsav/laravel-translatable#217]
There are some problems when using this package and [laravel-nestedset](https://github.com/lazychaser/laravel-nestedset) together, because of the overridden `save` method.

 e.g. `up()` and `down()` to change node order don't work

Is there any other way to save translations without changing `save` method?

**Comment by armababy** [comment]
As of this merge it now uses Trait instead of extending https://github.com/lazychaser/laravel-nestedset/pull/76
