### ISSUE TITLE
Unneeded queries?

### ISSUE THREAD

**Issue by lmarcelocc** [dimsav/laravel-translatable#219]
Hi all,

first of all, thanks for this great package!

I have one doubt, this are my configs:
config/app.php
`
    'locale' => 'en',
    'fallback_locale' => 'fr',
`

config/translatable.php
`
'locales' => [
        'en',
        'fr',
        'pt',
    ],
    'locale_separator' => '-',
    'locale' => null,
`

now, every time I make a request to some endpoint that uses a model translation, even if is the default locale selected, I see that are made some queries to the translatable database table.
For instance:
`select * from country_translations where country_translations.country_id = 80 and country_translations.country_id is not null`

Is this supposed to be like this? I feel we're using some unneeded queries since we're using the default locale, that shouldn't be needed to get something from the translatable table.

Am I right? Am I missing something?

Thanks in advance.

Best wiches,
Marcelo Carvalho

**Comment by dimsav** [comment]
Hi Marcelo, we can't help you if we don't see some code.

**Comment by lmarcelocc** [comment]
Hi dimsav,

you're right.

For instance, I will show you my Country Model.
**Country Model**

```
namespace Modules\Country\Entities;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;

class Country extends Model
{
    // Translate data trait
    use Translatable;

    // The names of the fields being translated in the "Translation" model.
    // This field is automatically translated
    public $translatedAttributes = ['name'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

    /**
     * Get the regions for the country
     *
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function regions()
    {
        return $this->hasMany('Modules\Region\Entities\Region');
    }
}
```

**CountryTranslation Model**

```
namespace Modules\Country\Entities;

use Illuminate\Database\Eloquent\Model;

class CountryTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = [];
}
```

**Account Controller**

```
/**
* Show a specific accountId
* GET /account/{id}
*
* @api
*
* @param int $accountId
* @return \Illuminate\Http\JsonResponse
*/
public function show($accountId)
{
        $userInfo = Auth::guard('api')->user();

        // Check if has role admin
        if (!$userInfo->hasRole('admin')) {
            return $this->respondForbiden('forbiden');
        }

		$account = Account::with('regions.country', 'sector', 'notation')
            ->find($accountId);

        // If user not found or maybe, is soft deleted!
        if (is_null($account)) {
            return $this->respondNotFound('account_not_found_or_inactive');
        }

        // Prepare data to sent back to frontend
        $data = ['isOk' => true, 'data' => $account];
        return $this->respond($data);
}
```

Now, the frontend debug bar result:
<img width="960" alt="queries" src="https://cloud.githubusercontent.com/assets/6483007/13699637/89e7f1be-e773-11e5-900b-05f92cfa4766.png">

My questions are:
- why is this making queries to country_translation if there's no neeed for it, since we're using the default locale? (It's because the this: public $translatedAttributes = ['name'] ?)

Notes: To change locale, I have a middleware that handle with it, if there's a url parameter named "locale" it will setLocale() with that parameter value (if valid).

Thank you again!

Best wishes,
Marcelo

**Comment by catalinux** [comment]
because this package does not care about your fields in your original Country table. Indeed, if you are missing the default language in your translate table, it might use those fields, because it only overrides those values. Otherwise they are untouched , so you get them from the original table

**Comment by lmarcelocc** [comment]
Hi catalinux,

so I think is that.

In my Country table I only have english "names" countries and at my country_translation table I have french transations.

There's any easy way to check first if, the selected locale is the default one, and if so, not get values from translated table?

This should only go to translation table if the selected locale is not the default one....

Thanks

**Comment by catalinux** [comment]
@lmarcelocc it's true.

**Comment by dimsav** [comment]
Feel free to open a pull request.
