### ISSUE TITLE
isFillable doesnt check the parent model

### ISSUE THREAD

**Issue by fosron** [dimsav/laravel-translatable#221]
Hello,

so i've ran into a problem with checking of fillable fields, in this case the check in this line `/src/Translatable/Translatable.php:252` (`$this->isFillable($translationAttribute)`) is always failing when using `create`/`fillable` methods of Eloquent. One solution i found is to add it to parent models `$fillable`, but that's not a viable solution. How could this be solved?

On an interesting note, when using the same model (with same array structure) in a seed, this problem did not happen.

**Comment by dimsav** [comment]
This is strange. Can you investigate and see why this doesn't happen in your seeds?

**Comment by fosron** [comment]
I think it's because Seeds are by default calling `Eloquent::unguard();`. In my case i call it by hand in the `DatabaseSeeder` file.

**Comment by dimsav** [comment]
Please have a look at the docs how to properly setup fillable fields: https://github.com/dimsav/laravel-translatable#step-3-models
