### ISSUE TITLE
How to remove a translation via filling?

### ISSUE THREAD

**Issue by SteveEdson** [dimsav/laravel-translatable#222]
How do I go about removing a translation / multiple translations?

I've tried

```
$data = [
    'name' => 'Default Name'
    'en-GB'  => ['name' => false],
    'fr-FR'  => ['name' => null],
    'en-US' => null
  ];
```

Etc, but nothing works. Is it not possible to do this with multiple translations?

**Comment by dimsav** [comment]
Good point, I don't think this is possible. Maybe we should implement it? @nWidart @sdebacker

**Comment by SteveEdson** [comment]
Thanks, for now I'm removing all translations manually, and re-adding the ones that are present.

**Comment by dimsav** [comment]
I am not sure about that because it could accidentally delete translations for some developers. I would suggest you delete the translations the same way you would delete eloquent relationship entries.
