### ISSUE TITLE
Translation Fallbacks

### ISSUE THREAD

**Issue by SteveEdson** [dimsav/laravel-translatable#223]
Is this an issue, or am I doing something wrong?

I'd like to have all my translation locales in the format of `en-GB`, `en-US`, `fr-FR` etc.

I have the config options:

```php
// App Config
    'locale' => 'en-GB',
    'fallback_locale' => 'en-GB',

// Translatable
    'locale' => null,
    'use_fallback' => true,
    'fallback_locale' => 'en-GB',

```

So when I select my app locales to something that doesn't exist, like `fr-BE`, I would expect it to look for this translation, and then fallback to use `en-GB` (or optionally look for a `fr` value first, and then fallback to `en-GB`). Instead, it is just looking for `fr` translations, and then not returning anything?

Is this correct? This isn't what I would want.

Thanks

**Comment by dimsav** [comment]
That is indeed possible. Have a look at the docs for [country based fallbacks](https://github.com/dimsav/laravel-translatable#country-based-fallback).
