### ISSUE TITLE
Dynamic Fallback Locale

### ISSUE THREAD

**Issue by oltreseba** [dimsav/laravel-translatable#224]
I'm trying to achieve the following result:
- The admin of a website can fill entities in two language (the website is in two languages)
- If one language is not available the other one should be taken.

The fallback_locale setting allow me to set one as fallback, but if the user directly fill in the other locale i'm not getting any translation in the "main" language.

Is there an easy way to do this globally?

**Comment by dimsav** [comment]
There is not a method in the package that feeds that need, sorry.
This is very custom so you would have to make something on your own.

**Comment by brian2694** [comment]
@oltreseba I know it's too late bro, but I did that.

In the "original" model I've added an attribute called "primary_language"

Then I've extended the Trait "Translatable". Look at this

<?php

namespace App;

use Dimsav\Translatable\Translatable;

trait CustomTranslatable
{
    use Translatable;
    /**
     * @param null $locale
     *
     * @return string
     */
    private function getFallbackLocale($locale = null)
    {
        return $this->primary_language;
    }
}

SORRY FOR MY ENGLISH

**Comment by oltreseba** [comment]
Don't worry and thank you for your help. In the meanwhile i've extended so much this package, an now our internal version supports things like:
- multiple fallback locale
- sorting (keeping in account the fallback locale)
- and much more :)

**Comment by Maxence-Machu** [comment]
@oltreseba , could you share your code ? I'm looking to develop the same feature (dynamic fallback).
Thanks
