### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by kirobo** [dimsav/laravel-translatable#225]
Hello
I'm using it as described in documentation I get this error
![image](https://cloud.githubusercontent.com/assets/11143132/13896814/9e468ff0-edc0-11e5-9232-da85ed60b47f.png)
![image](https://cloud.githubusercontent.com/assets/11143132/13896818/b23c747a-edc0-11e5-8293-b6abdb5836a1.png)
![image](https://cloud.githubusercontent.com/assets/11143132/13896819/babd73d8-edc0-11e5-9b73-4fe8e9a2e2de.png)

Please help.

**Comment by kirobo** [comment]
@dimsav Please help.

**Comment by dimsav** [comment]
Please send the execution code. Also follow the instructions at the docs.
