### ISSUE TITLE
Why this module don't use inner join?

### ISSUE THREAD

**Issue by approached** [dimsav/laravel-translatable#226]
Hello,

i like this approach:
```php
Country::join('country_translations as t', 't.country_id', '=', 'countries.id')
    ->where('locale', 'en')
    ->get();
```

It is fast and just only **one query**. But why isn't this implemented in this module?

**Comment by dimsav** [comment]
Feel free to do a pull request :)

**Comment by approached** [comment]
Ok thanks. I created one... https://github.com/dimsav/laravel-translatable/pull/227
