### ISSUE TITLE
Can not get specific value from country_translations table

### ISSUE THREAD

**Issue by Shajjadhossain** [dimsav/laravel-translatable#229]
Hello, 

I have followed the [doc](https://github.com/dimsav/laravel-translatable).  I created two tables (1. countries and 2. country_translations). 

![tr](https://cloud.githubusercontent.com/assets/14067302/14271605/77290420-fb1c-11e5-9155-792933da8863.jpg)

Now I changed the column name => key and value cause I can get the value (lang text) by query "key". 

Say for example : 

`       $r = 'DE';//App::getLocale(); // 'fr'
         $germany = Country::where('code', $r)->first();

        // I want to get value where key= 'contacts-last-name'
        $translation = $germany->translate($r, true)->where('key', 'contacts-last-name')->value;

        print_r($translation);
        exit("----");`

ERROR: Undefined property

Please let me know the way to get specific value using new query/sub query (key). @dimsav

**Comment by Shajjadhossain** [comment]
@dimsav :: Please have a look.

**Comment by Shajjadhossain** [comment]
@

**Comment by dimsav** [comment]
Hi, if I understand correctly you are trying to find a record by the translated attribute?

If so, see [this](https://github.com/dimsav/laravel-translatable#how-can-i-select-a-country-by-a-translated-field).

Otherwise please explain.
