### ISSUE TITLE
Translatable not insert when saving

### ISSUE THREAD

**Issue by trinvh** [dimsav/laravel-translatable#233]
I have a weir issue with translable. I have two main model used translatable, the first one work perfectly. The second dont work anymore. I spent 2 days for rewrite, compare between 2 models but nothing happends.

This is my code

```
class Page extends Model {
	use Translatable;
	use SoftDeletes;
	use \App\Classes\Scope;

	public $translatedAttributes = ['name', 'content', 'slug', 'keyword', 'description'];

	protected $fillable = ['compiler', 'status', 'permission'];

	protected $table = "pages";

	public static $rules = [
		'*.name' => 'required',
		'*.content' => 'required',
	];
}
```

```
class PageTranslation extends Model {

	protected $fillable = ['name', 'slug', 'content', 'keyword', 'description'];

	public $timestamps = false;
}
```

In controller

````
public function store(Request $request) {
	$this->validate($request, Page::$rules);

	$inputs = $request->all();
	$inputs['status'] = $request->has('status');

	$newPage = Page::create($inputs);
	return view('backend.pages.create')->withPage($newPage);
	return redirect()->back()->withFlashSuccess('Saved successfully');
}
````

Only page was inserted, page_translations not insert anymore. No error shown.
I see in debugbar and only page insertion query runs:

> insert into `pages` (`permission`, `compiler`, `status`, `updated_at`, `created_at`) values ('aaaaaaaaabbbb', 'html', '0', '2016-04-10 09:26:55', '2016-04-10 09:26:55')
> select * from `page_translations` where `page_translations`.`page_id` = '26' and `page_translations`.`page_id` is not null

Please tell me what i was wrong!

**Comment by dimsav** [comment]
Sorry I have no idea. I would make sure that the input is validated before passing it into the create method.
