### ISSUE TITLE
Why select() method still returns non selected fields?

### ISSUE THREAD

**Issue by aleixfabra** [dimsav/laravel-translatable#236]
My model:

``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use \Dimsav\Translatable\Translatable;

    /**
     * The attributes that are translatable.
     *
     * @var array
     */

    public $translatedAttributes = [
        'title',
        'body'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'body'
    ];
}
```

My Controller:

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Page;

class PageController extends Controller
{
    public function index() {

        $page = Page::join('page_translations', 'pages.id', '=', 'page_translations.page_id')
                   ->select(['pages.id', 'page_translations.title', 'pages.created_at', 'pages.updated_at'])
                   ->groupBy('pages.id')
                   ->first();
    }
}

/* $page
{  
   "id":2,
   "title":"foo",
   "created_at":"2016-04-18 12:22:36",
   "updated_at":"2016-04-18 14:06:47",
   "body":"" <----- I don't want this attribute
}
*/
```

I'm using `select()` method, and I didn't select the `body`, so I don't want to get the `body` field. 
The result I want should be:

``` php
/* $page
{  
   "id":2,
   "title":"foo",
   "created_at":"2016-04-18 12:22:36",
   "updated_at":"2016-04-18 14:06:47"
}
*/
```

I want to select only the fields that I want but keeping them as `translatedAttributes`. So I can still use their magic properties.  

Is it possible?

Thanks!

P.S. thanks to @HarleyFuagras

**Comment by dimsav** [comment]
Why do you want to select only selected columns?

**Comment by aleixfabra** [comment]
Because I don't want to remove it manually using:

```php
$datatables = Datatables::of($data)->removeColumn('body');
```

**Comment by aleixfabra** [comment]
I want to select only the selected columns because I don't need the remaining for further logic operations.

e.g. when I use datatables package (https://github.com/yajra/laravel-datatables) I don't need them.

**Comment by dimsav** [comment]
The fact you don't need it doesn't mean you shouldn't fetch it from the database. Unless you have millions of records in the database.

**Comment by aleixfabra** [comment]
But the function of `select` is precisely select only those fields you want, and here, it isn't working.

I don't want to remove it by hand using `unset($page['body'])` or something like this. I want to fetch my data properly at the first time.

This is why I am asking for.

**Comment by dimsav** [comment]
Unfortunately, `select` is an eloquent specific command and it's not supported by this package.

**Comment by zanematthew** [comment]
@aleixfabra fwiw that `select` is added at the model level.

```
public function fooRelation()
{
    return $this->belongsTo('App\User')->select(['id','name']);
}

```

**Comment by HamidReza63** [comment]
@dimsav  I have exactly the same Issue . for anybody who use  datatables package (https://github.com/yajra/laravel-datatables) , this issue would cause serious problems. It would be appreciated if you could  find a proper solution regarding Select Column.

**Comment by HamidReza63** [comment]
aleixfabra Did you (by any chance) find a proper solution for this Issue

**Comment by HamidReza63** [comment]
@zanematthew What did you mean. Please elaborate.

**Comment by aleixfabra** [comment]
@HamidReza63 I didn't anything.

**Comment by andresfranco** [comment]
I have the same issue .Someone has a workaround?

**Comment by zanematthew** [comment]
@HamidReza63 honestly, not sure, its been awhile since I looked at this issue. 

I think this sums it up;

> @dimsav  Unfortunately, select is an eloquent specific command and it's not supported by this package.

Regarding the original code in question, my suggestion was that rather than manually creating the relationship to retrieve results, this should be done at the model level, as noted in the [Laravel Eloquent documentation](https://laravel.com/docs/5.5/eloquent-relationships#one-to-many)

```
$page = Page::join('page_translations', 'pages.id', '=', 'page_translations.page_id')
    ->select(['pages.id', 'page_translations.title', 'pages.created_at', 'pages.updated_at'])
    ->groupBy('pages.id')
    ->first();
```

but then again, isn't this what the package provides.
