### ISSUE TITLE
Documentation is needlessly confusing

### ISSUE THREAD

**Issue by reachuniversal** [dimsav/laravel-translatable#240]
I use laravel-translatable in my project and it's a fantastic extension, thanks for making it. I just wanted to point out to you that your choice to use a table of countries as sample data in the documentation left me scratching my head at first and it would be a good idea to change it to something else that's not related to languages or countries so people reading it don't get confused.

Thanks!

**Comment by dimsav** [comment]
This is a valid point. Thanks for your feedback

**Comment by acornforth** [comment]
I just read the installation guide thinking that creating a 'Countries' table is a necessary step for this package to function correctly, luckily i thought i would check, and found this question, so now i am assuming it's not a requirement ? 
This ought not to be too big of a thing to fix, i would be happy to run a search and replace on the docs and submit a pull request... later though, and if no-one else gets to it first!

**Comment by reachuniversal** [comment]
> This ought not to be too big of a thing to fix, i would be happy to run a search and replace on the docs and submit a pull request... later though, and if no-one else gets to it first!

Yes please.

**Comment by acornforth** [comment]
Cool, I have put it on my todo list :)

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
