### ISSUE TITLE
Trait method getAttribute has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by mikimaine** [dimsav/laravel-translatable#242]
this error will occur
 Trait method getAttribute has not been applied, because there are collisions with other trait methods

when i add this package trait with Eloquence trait ??

how should i use it ??

it is not only the getAttribute but also 

```
-  getAttribute
-  setAttribute  
-  setAttribute
-  save
-  toArray   
-  __isset  
```

**Comment by mekramy** [comment]
Hi, This example maybe usefull for you:
`trait A{
	public function Say(){
		echo "A Class";
	}
}
trait B{
	public function Say(){
		echo "B Class";
	}
}

class C{
	use A,B{
		A::Say insteadof B;
		A::Say as protected aSay;
		B::Say as protected bSay;
	}

	public function Say(){
		$this->aSay();
		$this->bSay();
	}

}`

**Comment by mikimaine** [comment]
Yes i have done it like that . it is solved! Thanks!

**Comment by LaurentEsc** [comment]
Hi @mikimaine 

I'm currently facing the same problem. Could you please share your solution to make Translatable work with Eloquence? Solving the traits conflict don't seem very easy and I could use some help.

Thank you

**Comment by edgarsn** [comment]
+1 I would like to see solution as well.

**Comment by trixanapp** [comment]
+1

**Comment by mikimaine** [comment]
yap @trixanapp @edgarsn @LaurentEsc . 
sorry i was out for a while. Here is my code. 

use Translatable,Eloquence{

        Eloquence::getAttribute  as getAttributeEloquence;
        Translatable::getAttribute insteadof Eloquence;

        Eloquence::setAttribute  as setAttributeEloquence;
        Translatable::setAttribute insteadof Eloquence;

        Eloquence::save  as saveEloquence;
        Translatable::save insteadof Eloquence;

        Eloquence::toArray   as toArrayEloquence;
        Translatable::toArray  insteadof Eloquence;

        Eloquence::__isset   as __issetEloquence;
        Translatable::__isset  insteadof Eloquence;
     }

**Comment by joturako** [comment]
as it turned out, to search on translated fields, i have to give the translations table that search trait and use `whereHas`

```
Book::whereHas('translations', function ($query) use($request) {
                    $query->where('locale', \App::getLocale())
                            ->search($request->s);
                })->paginate();
```
