### ISSUE TITLE
Error on getAttribute

### ISSUE THREAD

**Issue by vikkio88** [dimsav/laravel-translatable#243]
Hi, I could not find a previous example of this issue.
Basically I make some class implement your trait, and everything works fine, I have some unittests and when I try to access directly to an attribute of a model which is implementing your trait the result is always null, whereas the json parser works fine on them.
a small example.

```php
>>> $user =\App\Models\Role::all()->random();
=> App\Models\Role {#1176
     id: 1,
     name: "super_admin",
   }
>>> $user->name;
=> null
>>> $user =\App\Models\User::all()->random();
=> App\Models\User {#1136
     id: 10,
     name: "Roy Predovic",
     email: "kaitlin.kuhn@gmail.com",
   }
>>> $user->name;
=> "Roy Predovic"
>>>
```

Role implements your trait, User doesnt.

Am I doing something wrong? I am just using it the way you suggest in your readme.

**Comment by dimsav** [comment]
Hi, is there a `name` column defined in your `roles` db table?

**Comment by vikkio88** [comment]
of course there is

**Comment by dimsav** [comment]
if `name` is a translated property, it should only exist in your roleTranslations table.

See an example here: https://github.com/dimsav/laravel-translatable#step-2-migrations

**Comment by vikkio88** [comment]
ah I got it, so basically I need to move everything to the translation table?
Thanks

**Comment by dimsav** [comment]
yes, for the translated fields of course.
