### ISSUE TITLE
Illegal offset type

### ISSUE THREAD

**Issue by ArnauMe** [dimsav/laravel-translatable#244]
Hello, 

this issue is driving me insane, and i don't really know if it's this package problem or something else, but i couldn't find anything remotely close to what i'm experiencing. I've tried to do a simple example just like yours :  

**Page Class:**

```php
use Illuminate\Database\Eloquent\Model;
class Page extends Model{
  use \Dimsav\Translatable\Translatable;
  protected $primaryKey = 'idPage';
   protected $fillable = ['position', 'type', 'template', 'hasSubMenu', 'active', 'identifier', 'name', 'title', 'subTitle', 'url', 'metaTitle', 'metaDesc'];
  protected $hidden = ['idPage'];
  public $translatedAttributes = ['name', 'title', 'subTitle', 'url', 'metaTitle', 'metaDesc'];
}
```
**PageTranslation Class:**
```php
use Illuminate\Database\Eloquent\Model;
class PageTranslation extends Model{
  protected $primaryKey = ['idPageTranslation'];
  protected $fillable = ['name', 'title', 'subTitle', 'url', 'metaTitle', 'metaDesc'];
}
```

Migrations are as they should be, if you need them i'll post them.

The problem comes when i try to save the translations: 

I have a form with all the possible translations to submit, so following the tutorial which you refer to, it ended up looking like this: 

foreach ($langs as $lang) {     
          $page->translateOrNew($lang->locale)->name = $request->input('name_'.$lang->locale);
          $page->translateOrNew($lang->locale)->title = $request->input('title_'.$lang->locale);
          $page->translateOrNew($lang->locale)->subTitle = $request->input('subTitle_'.$lang->locale);
          $page->translateOrNew($lang->locale)->url = $request->input('url_'.$lang->locale);
          $page->translateOrNew($lang->locale)->metaTitle = $request->input('metaTitle_'.$lang->locale);
          $page->translateOrNew($lang->locale)->metaDesc = $request->input('metaDesc_'.$lang->locale);         
        }
        $page->save();

$lang is a Language object which has a locale variable with 'en', 'es', etc .
Values from the form are how they are supposed to be. 
I tried your way with $data array, same error. 
Hell, i even tried just to make a new PageTranslation object and saving it (since all can be null) and it still gave me the same error. 

Here's the error (cropped):
ErrorException in Model.php line 2766: Illegal offset type
in Model.php line 2766
at HandleExceptions->handleError('2', 'Illegal offset type', '{myProjectRoot}/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php', '2766', array()) in Model.php line 2766
at Model->hasCast('locale', array('date', 'datetime')) in Model.php line 2781

For what's worth, i even tried with and without timestamps(), same result.

Am i doing something terribly wrong? 

This is laravel 5.2.38 by the way.

Thanks in advance. 

If you need some more code just let me know. Cheers.

**Comment by ArnauMe** [comment]
I "solved" this issue by using Uuid as id's instead of using eloquent autoincrement. Not sure why, it just works this way.
So i guess it's not solved, but worked around. 
Still, any explanation would be awesome. 
Thanks.

**Comment by dimsav** [comment]
Illegal offset type errors occur when you attempt to access an array index using an object or an array as the index key.

Can you try to debug the code in Model.php line 2766?

**Comment by ArnauMe** [comment]
Honestly i should go back way too much to debug that now.
As i mentioned, it stopped giving the error when i used Uuid package for my id's instead of eloquent's autoincrement.
I agree it shouldn't be a valid reason , but it did nonetheless. 
All i did was trying your package in a clean laravel project (5.2) with php 5.5.34.
Do you wanna see any other parts of the code? 

Anyway i may try it again in a new project with autoincrement, and if the error keeps showing up i'll post here again.

Thanks.

**Comment by dimsav** [comment]
I see. Feel free to respond here if you have more info about this.

**Comment by ArnauMe** [comment]
Hello! 

Here we are.. 9 months later with the same error on a new application :) This time i get the error no matter what primary keys i'm using, but heres the classes code anyway:

class Post extends Model{
  use \Dimsav\Translatable\Translatable;
  
  protected $primaryKey = 'id';
   
  protected $table = 'posts';
  
  public $translatedAttributes = ['post_content', 'post_title', 'post_slug'];
}

class PostTranslation extends Model{
  
  protected $table = 'post_translations';
  
  protected $primaryKey = ['post_id', 'locale'];
}

I've debuged that line in Model.php as you requested last time, here's the output:

The first one is Keyname, second one is KeyType just before merging

[2017-03-21 09:48:15] dev.INFO: array (
  0 => 'post_id',
  1 => 'locale',
)  
[2017-03-21 09:48:15] dev.INFO: int  
[2017-03-21 09:48:15] dev.ERROR: ErrorException: Illegal offset type in /Users/arnau/Workspace/somens/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2782
Stack trace:

**Comment by dimsav** [comment]
That is strange. Can you try replicating the examples from the tests in your project just to debug?

https://github.com/dimsav/laravel-translatable/tree/master/tests

You could test for example the models City and CityTranslation. The migrations are [here](https://github.com/dimsav/laravel-translatable/blob/master/tests/migrations/2013_11_28_152610_create_tables.php)

**Comment by ArnauMe** [comment]
Hello, 

Your code works, but it's slightly different from mine, and I'm not really sure why aren't you using composite keys in the translation model. I mean, it should be id+locale, and that was the issue with me. 
I forgot to use $incrementing = false on my PostTranslation, hence the error.  Still, if that shouldn't happen, i leave it to you :)
Thanks!
