### ISSUE TITLE
How to Translate a text

### ISSUE THREAD

**Issue by adnanafzal565** [dimsav/laravel-translatable#245]
How to translate a text into some other language ?

**Comment by dimsav** [comment]
Hi there, please check the [docs](https://github.com/dimsav/laravel-translatable#documentation) to read about how you can use this package.

**Comment by trong291990** [comment]
I didnt see any document about translate a text
Would I new CountryTranslate object then save as a eloquent instance  ?

**Comment by dimsav** [comment]
Yes, you should store the translations using a *Translation model.
