### ISSUE TITLE
Class 'Illuminate\SupportokFacades\App' not found

### ISSUE THREAD

**Issue by captain-torche** [dimsav/laravel-translatable#246]
I'm having this recurrent bug which does not allow me to use the script.

I've had the issue with my own implementation and, feeling I made a mistake, I followed the steps mentioned in [laravel news](https://laravel-news.com/2015/09/how-to-add-multilingual-support-to-eloquent/) : 

- I created a migration
- I created the two models, Article, and ArticleTranslation
- I created the route "create"

Then, when I try to access the route, I get an error which says `Class 'Illuminate\SupportokFacades\App' not found`

Is this a known bug, or did I misconfigure something ?

I use laravel-translatable v.5.6 with Laravel 5.2.39

**Comment by captain-torche** [comment]
Wait ... on a fresh installation, is seems to work. I'll try to understand what was interfering.

**Comment by dimsav** [comment]
Seems like there's a typo in `SupportokFacades`

**Comment by captain-torche** [comment]
Yes, I'll try to find which other plugin would interfere with this one.
