### ISSUE TITLE
use locale_id instead of locale

### ISSUE THREAD

**Issue by saazrai** [dimsav/laravel-translatable#248]
I have a separate table for locales and I am trying to use locale_id as FK instead of locale file in translations table. 

locales
id | name | code
1 | English | en
2 | Spanish | es

color_translations
id | color_id | locale_id | name
1 | 1 | 1 | blue
1| 1| 2| azul

How can the default name be selected in this relationship ?

**Comment by dimsav** [comment]
See [fallback locales](https://github.com/dimsav/laravel-translatable#fallback-locales) in the docs.

**Comment by mkwsra** [comment]
@saazrai May I know how did you solve it?
