### ISSUE TITLE
Do not retrieve null records

### ISSUE THREAD

**Issue by afujita** [dimsav/laravel-translatable#252]
Hi. I am trying to retrieve only translated menus in to my header. Currently have Portuguese and English translations. If I use the code bellow, it does not load the null record (thats OK), but it is not loading the notNull record also (Portuguese record).
 
Here is my controller (part)..

```php
$menus = Menu::whereHas('translations', function ($query) {
    $query->where('locale', 'en')->whereNotNull('menu');
})->get();
```

My view..

```
@foreach ($menus as $menu)
@if ($menu->category_id == 1)
 <li><a href="{{ $menu->slug }}">{{ $menu->menu }}</a></li>
 @endif
@endforeach                  
```

Appreciate your help, guys!

**Comment by dimsav** [comment]
Feel free to use the `translatedIn` scope as demonstrated at the docs: https://github.com/dimsav/laravel-translatable#available-scopes

**Comment by afujita** [comment]
Thanks for your kindness. I will take a look at the documentation!
