### ISSUE TITLE
Forget a Translation

### ISSUE THREAD

**Issue by johannesschobel** [dimsav/laravel-translatable#253]
Dear @dimsav ,
first of all, I would like to thank you for your **awesome** package. I really, really appreciate your work!

I have a feature request for your package:
Is it possible to "forget" (i.e., delete / remove) a translation?

Consider the following example:
I have an API endpoint to `store` FAQ entries. The `post body` of this request must hold all translations. Of course, I would like to create an API endpoint to `update` one given FAQ entry. My initial idea was to submit the entire FAQ again - with the translations needed.

If I first create an FAQ entry with the languages `en` and `de`. Then I'm going to update the entry and submit `en` and `fr` - I would like to get the `de` translation to be removed from the database.

How can I manage this?
Would it be a good idea to add a `forgetTranslation()` method to the trait?

Cheers

**Comment by dimsav** [comment]
Hey @johannesschobel 

what arguments is `forgetTranslation()` supposed to accept?

**Comment by johannesschobel** [comment]
The language to forget.. in the example above
forgetTranslation('de');

Am 01.08.2016 5:23 nachm. schrieb "Dimitris Savvopoulos" <
notifications@github.com>:

**Comment by johannesschobel** [comment]
Maybe we could have one `forgetTranslations()` method to forget *all* translations of this model.
And one `forgetTranslation(string locale)` to forget one specific translation.

What do you think - or how would you handle this problem mentioned above?

**Comment by dimsav** [comment]
Have [googled](https://www.google.com/search?q=laravel+sync+one+to+many) the issue? Seems like an eloquent question rather than specific to this package. Also check [this](https://laracasts.com/discuss/channels/general-discussion/syncing-one-to-many-relationships).

**Comment by johannesschobel** [comment]
Hey @dimsav ,
yeah, I thought as well, that this might be an issue related to eloquent and not related to your plugin. However, I do think, that it would be a valuable contribution to **forget** translations (or one translation specifically).

Currently, it is not possible to delete translations - I need to overwrite them. In the worst case scenario, I need to overwrite them with ```""``` (empty string). By doing so, however, I would loose the auto-fallback-feature (as there is a translation available!).

Would you accept a pull request for this issue? Unfortunately, I am quite busy at the moment..

Cheers and greetings from Germany

**Comment by johannesschobel** [comment]
well i guess i can close this issue - it has been merged ;)
