### ISSUE TITLE
What About existing model

### ISSUE THREAD

**Issue by carloshuggins** [dimsav/laravel-translatable#260]
Lets say I have a project that is already in production and have the country's name already on the database and accesible tru the Models $country->name; attribute.... when implementing laravle-translatable shoud I remove the 'name' field from the original country table??

**Comment by dimsav** [comment]
Correct, you should drop the name column after you populate the translations table during the migrations.

**Comment by carloshuggins** [comment]
I assumed it, and droped all the fileds to be translated... it works GREAT!!! excellent work keep it up....

**Comment by dimsav** [comment]
thanks!

**Comment by yusufyilmaz** [comment]
Is it possible to use translatable without droping the existing name column. 

I mean is that I have default spanish table for "name" in a model and adding second language with new translations model. is it possible to use default "name" from existing table and additional translations table from the translations table. 

Tables will be like

default table spanish default table

> id | name
> 1  | coche

adding en and ru languages as additional translations table.
translations table

> id | locale | default_id | name
> 1  | en       | 1              | car
> 1  | ru       | 1              | автомобиль
