### ISSUE TITLE
Working with Eloquent's lists() Method

### ISSUE THREAD

**Issue by beratdogan** [dimsav/laravel-translatable#27]
Hey @dimsav, first thanks for this amazing package.

When I want to get translatable data with lists() I got "Fields couldn't find" errors. Code is here:

``` php
Category::lists('name', 'slug');
```

But I got data with this:

``` php
Category::all()->lists('name', 'slug');
```

But, this way couses a performance problem. First we get all lines, after select them. Is there any way to get data like first code?

**Comment by dimsav** [comment]
@beratdogan the scope is coming in the next update.
