### ISSUE TITLE
How to force magic fields to be filled always without fallback?

### ISSUE THREAD

**Issue by simeonbugarija** [dimsav/laravel-translatable#270]
Hello,
first of all thanks for your awesome package, I use it on every project, and it's working fine.
Now I have a situation where the user must enter at least one translation in any language.
The problem is that if the user entered a translation which is not the default locale, I can't access the magic properties, display fields, generate routes..
For example:
- I use 4 locales (hr, en, de, it), in app.php default is "hr"
- user enters translation only in italian
- list of posts doesn't show title for posts without translation in croatian
- when I try to generate route `{{route('post.show', $post)}}`, there is no translated slug for croatian language, and link is not working
- I bind posts by translated slug, and route key name is slug:

RouteServiceProvider.php

```
$router->bind('post', function($value)
{
    return Post::whereTranslation('slug', $value)->first();
});
```

Post.php

```
public function getRouteKeyName()
{
        return 'slug';
}
```

I can achieve this by using the first element of the translations collection, but then I always get english translation first, are they ordered by locale by default?
I also have to change the way I generate routes, I can not use the Post object anymore, I have to replace it with translated slug `{{route('post.show', $post->translations[0]->slug)}}`
Other way would be to write a custom function, this is just an idea:

```
public function trans($attribute)
{
    return $this->translations()->first()->$attribute;
}
```

`{{$post->trans('title')}}`

Is there a way to order the translations, give them some priority, like: 1.hr, 2.en, 3.de, 4.it, and the magic fields are filled automatically with the first translation found?
I hope I was able to explain :)

**Comment by dimsav** [comment]
Hi,

have you checked https://github.com/mcamara/laravel-localization ?

**Comment by simeonbugarija** [comment]
Hello,thank you for your answer, I'm using this package also..The problem in my case is that there is no default and fallback locale for translations.User can enter whatever translation he wants, but when I try to display data in a table or generate a route,it tries to find translation with default locale..
