### ISSUE TITLE
with('translations') clause  error

### ISSUE THREAD

**Issue by pbernim** [dimsav/laravel-translatable#272]
Hi,

I'm using the laravel-translatable and would like to order my results on a column of the _translations table (Amphora typology).

return Amphora::select('amphorae.*')
            ->join('dic_glossary_translations as t', 't.id', '=', 'amphorae.typology_id')
            ->where('locale', Session::get('locale'))
            ->groupBy('amphorae.id')
            ->orderBy('t.name', 'asc')
            ->with('translations')
            ->paginate($items_per_page);

Without the clause 'with('translations')' it works fine, but I see only the records with the typology translated.

When I use the clause 'with('translations')' I get this error:

"Call to undefined method Illuminate\Database\Query\Builder::translations()"

What have I forgotten ?

Thanks!

**Comment by okneloper** [comment]
Looks like you have forgot to add the use of Translatable trait?
