### ISSUE TITLE
get translations as array with locale as key

### ISSUE THREAD

**Issue by wolle404** [dimsav/laravel-translatable#273]
Hey there,

is there currently a way to get the translations with the locale as key? Like so:

```
[
    ['en' => ['foo' => 'bar in en'],
    ['de' => ['foo' => 'bar in de'],
]
```

Thanks!

**Comment by dimsav** [comment]
Hi @wolle404 

there is no such built in method.

**Comment by ElMatella** [comment]
What is the best practice with this package when consuming an API?

Let's imagine the following controller:
```
public function show(Product $product)
{
    return $product;
}
```
```
{
    id: 1,
    translations: [
        {
            id: 1,
            product_id: 1,
            name: 'My Product',
            locale: 'fr'
        }
    ]
}
```
I then have the following method to update the `Product`:
```
public function update(Request $request, Product $product)
{
    $product->update($request->all());
    return $product;
}
```
To make this work, it is necessary to send the following Json Body in the request:
```
{
    id: 1,
    fr: {
        name: 'My new name'
    }
}
```

So, I'll need to make a transformation on my Javascript objects before sending them back to the server.

Wouldn't it be nice, if we included those locales keys in attributes of the model?

**Comment by shadoWalker89** [comment]
@wolle404 just do this

```php
        $translations = [];

        foreach ($this->getLocales() as $locale)
        {
        	$translation = $this->getTranslation($locale);

        	if( $translation != null )
        	{
            	$translations[ $locale ] = $translation->toArray();
        	}
        }
```

**Comment by estrica2000** [comment]
this would be nice to be included in the original

**Comment by Gummibeer** [comment]
`getTranslationsArray` solves this request

**Comment by Gummibeer** [comment]
**related:**
* https://github.com/dimsav/laravel-translatable/issues/434
