### ISSUE TITLE
Translations in current language not saved

### ISSUE THREAD

**Issue by mrdezzods** [dimsav/laravel-translatable#276]
I have a model 'Page' which is translated in 3 languages. When I save the model with translations, the translations of the current language aren't saved. I tried changing the language and still the same: translations of active pages aren't saved. in database, the translated fields for active language are null. 

What could be reason for this?

**Comment by okneloper** [comment]
Hi @mrdezzods,
Can you show us some example code?

**Comment by reno1979** [comment]
same problem here.

current locale is nl, with this command only the en locale is stored in the database. 

```
$featureGroup = \App\FeatureGroup::create(['en'=>['name'=>"general"],'nl'=>['name'=>"algemeen"]]);
``` 

If I change the nl to fr for example, the database translations are both stored.

**Comment by dimsav** [comment]
@reno1979 you probably forgot adding `nl` as a locale. Read the docs.

**Comment by reno1979** [comment]
@dimsav ehmm oops 

;) thank you
