### ISSUE TITLE
Baum Nested Sets and Laravel Translatable

### ISSUE THREAD

**Issue by haipham** [dimsav/laravel-translatable#277]
Hi everyone!

Please help me make Baum Nested Sets work with Laravel Translatable package! How make below tree work in multi language? 

>     public function index()
>     {
>         $categories = Category::getNestedList('name', null, '-');
> 
>         return view('admin.categories.index', compact('categories'));
>     }
> 

'name' column move from categories table to category_translation table, so I get error:

> ErrorException in Node.php line 1213:
> Undefined index: name
> 

Thank for your time.

**Comment by dimsav** [comment]
You might want to check #25.
