### ISSUE TITLE
Check if there's a Trasalation or Not 

### ISSUE THREAD

**Issue by Bribin** [dimsav/laravel-translatable#281]
How to get all locales codes as array?
                           

>   $lang = array('en','fr')
                                @unless ($post->translations->isEmpty())
                                    @foreach ($post->translations as $lang)
                                        @if ($post->hasTranslation($lang->locale) == $lang )
                                            English
                                        @else
                                            Add Translation FR
                                        @endif
                                    @endforeach
                               @endif

How to check the locales transalation is avaible or not ?

**Comment by okneloper** [comment]
Hi @Bribin 

Is this 2 separate questions? 

I think what you are looking for is something like this:

    @foreach (config('translatable.locales') as $lang)
        @if ($post->hasTranslation($lang->locale) == $lang )
            Has {{ $lang }} translation
        @else
            {{ $lang }} translation not found
        @endif
    @endforeach

Let me know if it helps.

**Comment by Bribin** [comment]
@okneloper  yes. this is looking.
But this is not working.

**Comment by okneloper** [comment]
yeah, sorry. I amended the code. Please check it out now.

**Comment by Bribin** [comment]
@okneloper  thanks for your support. still im getting the error 
Trying to get property of non-object (View:

**Comment by okneloper** [comment]
what line is it related to? What code is on that line?

**Comment by Bribin** [comment]
@okneloper 
Please have a look on my code
Error on line 34
https://s12.postimg.org/wh5z1sdy5/code.jpg

**Comment by okneloper** [comment]
I see, you haven't copied over the amends from my example. It should look like this:

    @foreach (config('translatable.locales') as $lang)
        @if ($post->hasTranslation($lang))
            Has {{ $lang }} translation
        @else
            {{ $lang }} translation not found
        @endif
    @endforeach

Particularly this line
`@if ($post->hasTranslation($lang))`

**Comment by Bribin** [comment]
Thank you, Very much
