### ISSUE TITLE
translate on different connection, uses default connection

### ISSUE THREAD

**Issue by reno1979** [dimsav/laravel-translatable#283]
When I have two connection possibilties (mysql1, mysql2) and I try the following: 

```
$featureGroup = \App\FeatureGroup::on('mysql2')->firstOrCreate(['code'=>"general"]);
$featureGroup->translate('en')->name = 'general';
$featureGroup->translate('nl')->name = 'algemeen';
$featureGroup->save();
```

This saves the new row with code value general into the mysql2 database, but the translations are never stored. (even when I also use the setConnection('mysql2') on each translate and save method)

```
\App\FeatureGroup::on('mysql2')->getModel()->create(['code'=>"general", 'en'=>['name'=>"general"],'nl'=>['name'=>"algemeen"]]);
```

also fails
## update

When I dump the created model instance (using second connection) , it appears the realtion to the translation table has not the same value in its connection parameter. 

It seems related to Elequent relations not using its parent connection, see this issue::

https://github.com/laravel/framework/issues/9355

**Comment by reno1979** [comment]
@dimsav 

After using the laravel parent connection fix we have problems inserting translations on an other connection. 

We currently use this to be able to continue, but it is a bit ugly.... 

```
// create a new feature group entry
$featureGroup = new App\FeatureGroup;
$featureGroup->setConnection('otherconnection'); // Don't forget to set the connection!
$featureGroup->save();
 
// Now we will create the translation.
$featureGroupTranslation = new App\FeatureGroupTranslation;
$featureGroupTranslation->setConnection('otherconnection'); // Don't forget to set the connection here either.
 
$featureGroupTranslation->feature_group_id  = $featureGroup->id; // Grab the id of the newly created featureGroup.
$featureGroupTranslation->name              = 'algemeen';
$featureGroupTranslation->locale            = 'nl';
 
$featureGroupTranslation->save(); // And save the translation.

```

**Comment by dimsav** [comment]
@reno1979 can you please make a pull request ?

**Comment by reno1979** [comment]
I'll try

**Comment by reno1979** [comment]
@dimsav 

I would like to add a pull request, but did not figure out how. 
What do you need?

**Comment by dimsav** [comment]
I think we need to setup the tests with a second db connection and make the tests fail asserting the expected behavior and the code above. 

If you need help about how to make a pull request try googling it. 

:-)

**Comment by reno1979** [comment]
@dimsav The tests are a good start. 

I will not be making a pull request, because then I suppose to have a source code change proposal. And that is the part that I have not figured out yet, I don't think google did either :P

I hoped this plugin would benefit from the fixes in Laravel 5.4 regarding relations on other connections.

**Comment by dimsav** [comment]
Leaving this open in case somebody from the community wants to contribute.

**Comment by vocanic-saumini** [comment]
@dimsav 

Derived from @reno1979 solution. Thinking we can add following line `$translation->setConnection($this->getConnectionName());` in `saveTranslations` function after the `if` condition.

**Comment by Gummibeer** [comment]
it's fixed
