### ISSUE TITLE
whereTranslationLike and accents

### ISSUE THREAD

**Issue by marcelwirtz** [dimsav/laravel-translatable#285]
Hello,

if i have a name of an item which is like "Menu à la card" and the full name is given over to the whereTranslationLike function like

Class:whereTranslationLike('name', 'Menu à la card')->firstOrFail()

the function does not find any results.

It's possible this fails with other special chars too, i did not test this.

EDIT: The normal whereTranslation() function works with this string.

**Comment by dimsav** [comment]
Cool
