### ISSUE TITLE
Translatable not working together with barryvdh/laravel-debugbar

### ISSUE THREAD

**Issue by janboden** [dimsav/laravel-translatable#288]
Hi guys,

First of all: great job on this package, works great!

I was trying to create a profile of the app I created, using barryvdh/laravel-debugbar. That one doesn't seem to work, because this package redirects all urls to /locale/*. 

ex: en/_debugbar/assets/javascript

Is there anything I can do about that, so my debug-files won't throw a 404.

Working in L5.3, latest versions of both packages.

Thanks in advance.

**Comment by dimsav** [comment]
Hi @janboden 

I don't see how this package can be related to the 404 issue, since there is no http involved at all.

Also I haven't used debugbar so unfortunately I can't help you, sorry.

**Comment by hanigamal** [comment]
I've the same problem, it happens when using routes like /{locale} the whole app blanks and debugbar isn't working, would you please put an example of routing for your great package?

**Comment by dimsav** [comment]
There are other packages to handle routing. For example: https://github.com/mcamara/laravel-localization
