### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::translate()

### ISSUE THREAD

**Issue by hako2008** [dimsav/laravel-translatable#289]
i have followed all the instructions, but i still have that error. 
Call to undefined method Illuminate\Database\Query\Builder::translate()
hint: hint: i'm using Laravel 5.3

**Comment by dimsav** [comment]
We need to see some code, don't be shy.

**Comment by hako2008** [comment]
that error it's just disappear i don't know why, now i have this error!!!

Call to undefined method Illuminate\Database\Query\Builder::keywords()
the code: 
`foreach ($ArticleKeywords as $keyword)
            {
                           
               if (keyword::whereTranslation('name', $keyword)->exists())
               {
                   $keyword1 = keyword::whereTranslation('name', $keyword)->first();
                   $Article->keywords()->attach($keyword1->id);
                }
                else
                {
                    $keyword1 = new Keyword;
                    //$data['lang'] was sent from the view to the controller post method
                    $keyword1->translateOrNew($data['lang'])->name = $keyword;
                    $keyword1->save();
                    Auth::user()->keywords()->save($keyword1);
                    $Article->keywords()->attach($keyword1->id);
                }
                
                   
            }
`

**Comment by hako2008** [comment]
after all everything work as charm
