### ISSUE TITLE
Foreign key problem with an extra underscore

### ISSUE THREAD

**Issue by nmpribeiro** [dimsav/laravel-translatable#290]
Hi!
So, I am having a Column not found 'mymodel_translation.my_model_id' when the actual one created is 'mymodel_translation.mymodel_id'

The model class is 'MyModel' (I suppose I will not use upper case anymore). But, I ran into this issue and now it's rather a curiosity. How can I make model::crate() accept that my translation resides on mymodel_id instead of my_model_id ?

getRelationKey() outputs 'my_model_id'

Thanks

**Comment by dimsav** [comment]
You can define the relation key like this: https://github.com/dimsav/laravel-translatable/blob/c8439cd518752e8988f4351835b8d2d3ab7b5427/tests/models/CountryGuarded.php#L19

Hope this helps.
