### ISSUE TITLE
Form design for insert data multiple languages.

### ISSUE THREAD

**Issue by huonsokly** [dimsav/laravel-translatable#292]
Hi dimsav,
I have followed all the instructions.
but I don't clear how to design form (CRUD) with dynamic input depend on number of languages.
may you help me for example please?
thanks!

**Comment by dimsav** [comment]
It's up to you how to implement CRUD. I don't have an example to give you but I know [this project](https://github.com/TypiCMS/TranslatableBootForms) is using laravel translatable.

It would be great if somebody using the package with forms could open a pr to update the docs.
