### ISSUE TITLE
Class lists with relationship

### ISSUE THREAD

**Issue by johnef** [dimsav/laravel-translatable#296]
When try to put my Class to lists it did not find the translation
$var = Class::lists('title', 'id');
now `title` in another table so I got 
`Column not found: 1054 Unknown column 'title' in 'field list'`

**Comment by dimsav** [comment]
Check `listsTranslations()` in the [docs](https://github.com/dimsav/laravel-translatable)

**Comment by johnef** [comment]
@dimsav Thanks very much,
I using this line to retrieve the list
`{{ Form::select('category', [null=>'Please Select']+$serviceCategory, null, array('class'=>'form-control1')) }} `

got the list with `optgroup`
 
```
<select class="form-control1" id="category" name="category">
<option value="" selected="selected">Please Select</option>
<optgroup label="0">
<option value="id">1</option>
<option value="title">Services 1</option>
<option value="brief">
with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</option>
</optgroup>
```

what I need is just something like this

```
<select class="form-control1" id="category" name="category">
<option value="" selected="selected">Please Select</option>
<option value="1">Services 1</option>
</option>
```
any suggestion please
