### ISSUE TITLE
Creating Different Language Versions in different time?

### ISSUE THREAD

**Issue by yubarajshrestha** [dimsav/laravel-translatable#299]
It's working very nice when we insert both content at the same time. But what if I want to add a content in one language now and want to add other language version in different time? Let's say I have two different users the one who creates English post and the other one in Spanish, how can we make this possible? Thanks in advance, I have having trouble in this step.

**Comment by dimsav** [comment]
See the section `Saving translated attributes` in the [docs](https://github.com/dimsav/laravel-translatable)
