### ISSUE TITLE
store translation in single table

### ISSUE THREAD

**Issue by meta0102** [dimsav/laravel-translatable#301]
hi,
it is possible to store all model translations in a single table like this october cms plugin? https://github.com/rainlab/translate-plugin

table: translate_attributes
   | id | locale | model_id | model_type                 | attribute_data
    -------------------------
    | 1  | en     | 12            | test\models\products |  {"title": "en title }
    | 2  | de     | 34            | test\models\products |  {"title": "de title }

would be much easier than to create a 2nd table for each model...

thanks

**Comment by dimsav** [comment]
Unfortunately, this is not how this package works.
