### ISSUE TITLE
App Locale never used?

### ISSUE THREAD

**Issue by WickedSik** [dimsav/laravel-translatable#302]
According to the documentation, the current app locale should be used when no locale is given in the parameters, or by directly using `$model->field`. However, according to both the code, and the tests that I've ran, this never happens!

Reason being that in the trait `\Dimsav\Translatable\Translatable` the output of `$this->locale()` is always the configured locale in `config/translatable.php`. Or did I misunderstood the configuration file, and should I remove that setting? The idea was that the default locale of Laravel is `en`, where the system I'm building is dutch, therefor the default locale would be `nl`.

If this shouldn't be in the configuration, why do we have the option? As far as I can tell, it makes no sense to configure something that should always come from `App::getLocale()`.

My test code (simplified, executed in `php artisan tinker`):
```php
App::getLocale(); # shows 'nl'
$e = Model::first(); 
$e->title # shows "Titel" (dutch)

App::setLocale('en');
$e->title # shows "Titel" (still...)
App::getLocale(); # shows 'en'

$e->{'title:en'} # shows "Title" (as expected)
```

**Comment by WickedSik** [comment]
I just tested setting the `locale` configuration to `null`. This actually makes the code above work as expected!

**Comment by yinx** [comment]
the logic in the locale retrieval is incorrect. If the locale is set in the config file it will ALWAYS override the current application locale. 

```php

protected function locale()
    {
        return app()->make('config')->get('translatable.locale')
            ?: app()->make('translator')->getLocale();
    }

```

The snippet above is taken from the /translatable.php trait file. Here the first condition should be left out in order to work as expected. This only means the locale parameter is not required anymore for this package. The laravel app()->locale() will always give the correct fallback as set in the app.php config.

**Comment by anaisabel19886** [comment]
This was driving me nuts! Thank you!

**Comment by marcoocram** [comment]
+1

**Comment by Gummibeer** [comment]
It just uses the translator locale if the config value is `null`. In https://github.com/dimsav/laravel-translatable/pull/470 we've cleared this a bit more in the config comment.
