### ISSUE TITLE
How to translate pivot values?

### ISSUE THREAD

**Issue by marcbelletre** [dimsav/laravel-translatable#303]
I couldn't find a way to translate pivot values from ManyToMany relationships. In my case, I have a Combination model and an Attribute model which are connected together with a belongsToMany relationship and a pivot value as shown below:

```
namespace App;

use Illuminate\Database\Eloquent\Model;

class Combination extends Model {
   public function product() {
      return $this->belongsTo('App\Product');
   }

   public function product_attributes() {
      return $this->belongsToMany('App\Attribute')->withPivot('value');
   }
}
```

The attribute_combination intermediate table looks like this:
```
+--------------+----------------+-------+ 
| attribute_id | combination_id | value |
|--------------+----------------+-------|
| 1            | 1              | Black |
| 2            | 1              | M     |
| 1            | 2              | Black |
| 2            | 2              | L     |
+--------------+----------------+-------+
```

Is there a way to retrieve the translation of this pivot value?

**Comment by dimsav** [comment]
Of course, make an AttributeCombination model and attach it to the pivot table. Also you will need to add an id column to the table. Then make a AttributeCombinationTranslation model and the correspondent table.

**Comment by marcbelletre** [comment]
Thank you for your answer. Unfortunately I already tried to do this and it still doesn't work.

I have one attribute_combination table with: id, attribute_id, combination_id and value
And one attriubute_combination_translations with: id, attribute_combination_id, value and locale

Here are my two models:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;

class AttributeCombination extends Model {
   use Translatable;

   protected $table = 'attribute_combination';
   public $translatedAttributes = ['value'];
}

class AttributeCombinationTranslation extends Model {
   public $timestamps = false;
   protected $fillable = ['value'];
}

```

You can see that the AttributeCombination model should be attached to the attribute_combination table. I certainly missed something because there is no way I can get the translation of my pivot value using $attribute->pivot->value.

**Comment by marcbelletre** [comment]
I figured out how to solve this issue by making a relationship between Combination and AttributeCombination, which is a bit messy but it actually works.
Anyway it would be great if we could simply retrieve a translation using the standard pivot syntax without having to create another relationship ;)
Thank you again for your time and for this awesome package!

**Comment by dimsav** [comment]
I'm glad you found a solution :)

**Comment by eminos** [comment]
@marcbelletre I've run into the same problem regarding a translated field on a pivot table. How did you solve this by creating a relationship? Could you give a code example?

**Comment by marcbelletre** [comment]
Hey @eminos, sorry for the late answer I was out during the last days.
First I created a new model "AttributeCombination" for my pivot table as you can see in my first answer. Then I simply added the relationship in my "Combination" model like this:
```
public function combination_attributes() {
    return $this->hasMany('App\AttributeCombination');
}
```
I changed my code a lot since I asked this question so I don't have the full example anymore but this should help you. Perhaps you already found out the solution by yourself anyway ;)

**Comment by ahmadbadpey** [comment]
what about  some attributes that are not translatable like `weight` or `dimension` and only get one value for all locales?

**Comment by dimsav** [comment]
@ahmadbadpey you should store these in the main model/table and not in the translation one.

**Comment by makz** [comment]
Hi, I use @marcbelletre solution to get translations of pivot. In my case, I have `products` and `specifications` which connected through pivot called `specifications_products`, and for translation - `spec_product_translations`.  

**I have another question:  how I supposed to save translations?**

Such thing is not working:
```php
$model->specifications()->syncWithoutDetaching([
                    $id => [
                        'en'  => ['value' => $item['en']],
                        'ru'  => ['value' => $item['ru']],
                    ],
                ]);
```  
or such:
```php
$model->specifications()->syncWithoutDetaching([
                    $id => [
                        "value:en" => $item['en'],
                        "value:ru" => $item['ru'],
                    ],
                ]);
````

**Comment by Gummibeer** [comment]
The described solution just works if you get an instance of the pivot table model.
Laravel doesn't do this out of the box.
So you should do something like:

```php
$product = Product::first();
$specifications = $product->specifications;
$pivotIds = $specifications->pluck('pivot.id');
$pivots = SpecificationProduct::whereIn('id', $pivotIds)->get();
foreach($pivots as $pivot) {
    // get the related translation data and save it on the translatable pivot model
}
```

This code is untested and not optimized. But it should give you an idea of how to do it.

For performance reasons you should have the translatable pivot model as a relationship on both `n:m` models to allow eager loading the translations in the main query.

But all these solutions aren't optimal/good. If I were in this situation I would create a custom trait and handle the translations in a JSON column (like in https://github.com/spatie/laravel-translatable - this also requires a model for the table).
In the trait I would use the accessor and mutator methods to handle translatable pivot values. To keep it clean I would create a mapping of pivot table names to translatable attributes in a service provider on a Singleton class like explicit route model binding.
To allow access to the original pivot values (you will need them in the mutators) I would create a overloaded attribute like `translated_pivot` that's attached by the trait and uses, if present, the original `pivot` attribute.
In the spare package you can see how to query translations in JSON columns (MySQL 5.7 required). 

I hope that this helps - I won't support this here any further because all solutions to work with pivot tables are out of scope of this package.
If anyone has a great solution that's usable in this package and a dynamic way I'm open for discussion in a new issue or even a PR.

**Comment by AshrafHefny** [comment]
@tomasvanrijsse , @Gummibeer  you can use  `using()` over the `belongsToMany()`  relation
Assuming your models as the following:
```
Class Product {
  function properties(){
    $this->belongsToMany(Property::class)->withPivot([
                                             'prodict_id',
                                             'property_id'
                                             ])
                                          ->using(ProductProperties::class);
  }
}

Class Property {
}

Class ProductProperties {
    use Translatable;
    $fillable = ['prodict_id','property_id'];
    $translatedAttributes = ['value']
}

Class ProductPropertyTranslation {
    $fillable = ['value'];
}
```
So then you can normlly call the `translated value column` as the following:
```
app()->setLocale('en');
$product = Product::with('properties')->find($id);
foreach ($product->properties as $property){
    echo $property->value;
}

**Comment by AshrafHefny** [comment]
You can use  `using()` over the `belongsToMany()`  relation
Assuming your models as the following:
```
Class Product {
  function properties(){
    $this->belongsToMany(Property::class)->withPivot([
                                             'prodict_id',
                                             'property_id'
                                             ])
                                          ->using(ProductProperties::class);
  }
}

Class Property {
}

Class ProductProperties {
    use Translatable;
    $fillable = ['prodict_id','property_id'];
    $translatedAttributes = ['value']
}

Class ProductPropertyTranslation {
    $fillable = ['value'];
}
```
So then you can normlly call the `translated value column` as the following:
```
app()->setLocale('en');
$product = Product::with('properties')->find($id);
foreach ($product->properties as $property){
    echo $property->value;
}

**Comment by scil** [comment]
I have similar question about Many To Many Polymorphic Relations.  I'm looking for an easy way like  the beatiful sollution from @AshrafHefny .

Article and Book model  share a polymorphic relation to a Place model.    intermediate table is placeables.


```
class CreatePlaceablesTalbe extends Migration
{
    public function up()
    {
        Schema::create('placeables', function (Blueprint $table) {
            $table->increments('id');

            $table->integer('place_id')->unsigned();

            $table->enum('placeable_type', [' 'App\\\\Article', 'App\\\\Book'])->nullable(); 
            $table->integer('placeable_id')->unsigned();
        });
        Schema::create('placeable_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->string('locale')->index();
            $table->integer('placeable_id')->unsigned();

            $table->string('intro', 800)->nullable(); // markdown

            $table->unique(['placeable_id', 'locale']);

        });
    }
}


class Article extends Model
{
    public function places()
    {

        return $this
            ->morphToMany('App\Place', 'placeable')
            ->withPivot('id','place_id',  'placeable_type', 'placeable_id')
            ->using(Placeable::class);
    }

}


class Placeable extends \Illuminate\Database\Eloquent\Relations\MorphPivot
{
    protected $fillable = ['place_id', 'placeable_type', 'placeable_id'];

    use Translatable;
    protected $translatedAttributes = ['intro'];
    public $translationModel = \App\PlaceableTranslation::class;

   // these two lines are necessary, otherwise error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'placeable_translations.' in 'where clause' (SQL: select * from `placeable_translations` where `placeable_translations`.`` is null and `placeable_translations`.`` is not null)
    protected $translationForeignKey = 'placeable_id';
    protected $table = 'placeables';

    protected $with = ['translations'];
}


class PlaceableTranslation extends Model
{
    protected $fillable = ['intro'];
    public $timestamps = false;
}

```

Now I can save data
```
                $data = [
                    'placeable_type' => 'App\\Article',
                    'placeable_id' => 1,
                    'place_id' => 1,
                    'en'=>['intro' => ' this article is connected to this place'],
                ];

                $item = \App\Placeable::create($data);
                $item->save();

```

But I can not featch locale data
```
$article = \App\Article::with('places')->find(1);

$article->places[0]->intro  
=>  null

$article->places[0]->pivot
=>  App\Placeable {
       placeable_id: 1,
       place_id: 1,
       placeable_type: "App\Article",
       id: 1,
   }
```

Now the way I can fetch the locele data is : 
```
$article->places[0]->pivot->translate()['intro']
```
or
```
\App\Placeable::find(1)
```


I wonder if there is a simple way like ` \App\Article::with('places')->find(1)->places[0]->intro `

**Comment by Gummibeer** [comment]
You should be able to do `$model->pivot->intro`.

**Comment by scil** [comment]
Thank you!  I'm stupid. 

It works!
```
$article->places[0]->pivot->intro
```
