### ISSUE TITLE
model->load('translations') works, but model->load('translation') dont.

### ISSUE THREAD

**Issue by p3ym4n** [dimsav/laravel-translatable#309]
Hi,
I faced a situation which I can't use the `withTranslation()` method and I have to pass the 'translation' as the name of the relation to load() method on model.
So if I want to use `model->load('translation')` to only load the current locale (and callback if have) translation , it won't works.
I know that its not a problem but I think that it's good to have a scope for that.
any ideas?

**Comment by dimsav** [comment]
The reason `model->load('translation')` won't work is because model has a one to many relationship with translation and not a one to one relationship. 

What behavior would you expect if would call `model->load('translation')` ?

**Comment by dimsav** [comment]
Maybe for db performance we should add this relationship?

**Comment by p3ym4n** [comment]
I don't think the one to many relation makes problem.  
and `model->load('translations')` returns more data.🤔
The only difference is adding the locale condition to the query ( and fallback if set).
I think we need some thing like this.

**Comment by fsasvari** [comment]
This would be very good to pull only current translation from database, thumbs up!

**Comment by gabrieldasilva** [comment]
Thumbs up for this too!

Actually, it would be great if we could eager load the relations just for the locale we need. By now, the relationsship gets all the translations associated to the item on database.

I could work on a code for this =D

**Comment by Gummibeer** [comment]
@p3ym4n I've added a PR #505 with this relation. Atm without unittests. I've no idea if there is a better way to do the fallback check!? A simple `orWhere()` doesn't work if the fallback is the first entry in the table (common usecase).

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
