### ISSUE TITLE
with translations set by default on relation

### ISSUE THREAD

**Issue by mavriz** [dimsav/laravel-translatable#312]
I have 2 translatable models (let's call them State, StateTranslatable,  Area, AreaTranslatable). that have a 1 to many relationship (an area belogs to a state but a state can have many areas).
I have set no with field for models StateTranslatable,  Area, AreaTranslatable 
and I have set **with=['areas']** for model State.

When I display Area:all() the translations field is not part of the output as expected.

However, when I display State:all() **the translations field exists** for most areas in the output. Nothing I have tried has worked so far.

**Comment by dimsav** [comment]
Please have a second look to the docs. Checking the code in tests might help as well.
