### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by rahmanQaiser** [dimsav/laravel-translatable#316]
Can you explain the Naming Convention for the foreign keys and translations table.
What if i want to follow different naming Convention for translation table and foreign keys. How do i mention that?
Great Package.

**Comment by dimsav** [comment]
Please read the docs on how to have custom table names: https://github.com/dimsav/laravel-translatable#the-translation-model

**Comment by rahmanQaiser** [comment]
Thanks
