### ISSUE TITLE
Save Translations Recursive

### ISSUE THREAD

**Issue by deargonaut** [dimsav/laravel-translatable#320]
Hi!

Thanks for the good work.
I've written a trait for filling the model and translation with dynamic values.
This helps me a lot... Maybe something to implement?

```
public function fillTranslatableAttributeCallback($attribute, $callback)
{
	foreach($this->getLocales() as $locale)
	{
		$attr = "$attribute:$locale";
		$this->{$attr} = $callback($attr, $locale, $attribute);
	}

	return $this;
}
```

Like this you can do something like this:
```
$page->fillTranslatableAttributeCallback('slug', function($locale_attribute, $locale, $attribute) use ($request)
{
	return str_slug($request->{$locale}['slug'] ?: $request->{$locale}['page_title']);
});
```

**Comment by dimsav** [comment]
Hi @deargonaut :-)

I am trying to understand how you use this function. If I get it correctly, you have a model Page with a translated attribute slug. And by using `fillTranslatableAttributeCallback()` you fill the model by using a specific structure of the http request. Is that correct? 

I have the impression that this is something custom. What would be another use case for the function above?

**Comment by deargonaut** [comment]
Well, I try to explain it better than ;-)

There is this nice function fill(), which can receive the $request if needed.
What I have to do a lot is alter the data coming from a user.

I could do this:
```
$attributes = $request->all();
foreach($translatable->getLocales() as $locale) // <-- Side note: getting locales is hard already. Because it is private.
{
    $attributes[$locale]['title'] = str_slug($attributes[$locale]['title']);
}
$translatable->fill($fill);
```

With my pull this could be done as following:
```
$translatable($request->all());
$translatable('title', function($locale_attribute, $locale, $attribute, $item) use ($request)
{
    return str_slug($request->{$locale}['title'];
    // or with passing the item to the callback (which i just committed)
    return str_slug($item);
}
```
It is just an convenience thing. But I use it a lot... I could imagine others would too.
Does this makes sense?

**Comment by dimsav** [comment]
Wouldn't it be simpler to make the getLocales() public then?

**Comment by deargonaut** [comment]
That's for sure. But if I want to call it within a controller it is not possible, because it is a trait.
An extra class must be written I think.
Something like this.
```
class TranslatableLocales
{
    use Translatable;

    public static function get()
    {
        return $this->getLocales();
    }
}
```

**Comment by dimsav** [comment]
If we make it public, you could bind the locales in your app service provider.

```php
app('locales');
```

**Comment by deargonaut** [comment]
Cool!

**Comment by dimsav** [comment]
In fact since we have already a service provider for the package we could add it there. I'm wondering if we need a new collection class so that folks using the package can mock things when testing.

**Comment by deargonaut** [comment]
See the pull request #323
