### ISSUE TITLE
Send the not correct data via json

### ISSUE THREAD

**Issue by iumag** [dimsav/laravel-translatable#324]
If I write dd($event-get()), I will get correct data

```
$language = app()->getLocale();
        $event = Event::join('event_translations', 'events.id', '=', 'event_translations.event_id')
            ->where('event_translations.locale', '=', $language);

        dd($event->get());
```

But I send data via json, something I get not correct data

```
        return response()
            ->json([
                'model' => $event->get(),
            ]);

```

For Example.

**dd($event->get())**

>   #attributes: array:8 [
>         "id" => 27
>         "picture" => "cutlery.png"
>         "created_at" => "2017-01-19 14:24:18"
>         "updated_at" => "2017-01-19 14:24:18"
>         "event_id" => 3
>         "locale" => "pl"
>         "name" => "RESTAURACJI"
>         "description" => "<p>RESTAURACJI</p>\r\n"
>       ]

**json**

> created_at:"2017-01-19 14:24:18"
> description:"<p>BARMANI NA ZLECZENIE</p>"
> event_id:3
> id:27
> locale:"pl"
> name:"BARMANI NA ZLECZENIE"
> picture:"cutlery.png"
> updated_at:"2017-01-19 14:24:18"

These vary. What are i do?

**Comment by dimsav** [comment]
Try this:

```
return response()
            ->json([
                'model' => $event->get()->toArray(),
            ]);

```
