### ISSUE TITLE
required_without validation

### ISSUE THREAD

**Issue by jaaksarv** [dimsav/laravel-translatable#325]
I have currently 2 languages and require that at least one of them is present. I'm using shorthand field names for translations. Using shorthand field names in required_without validation rules is not working, because ":" symbol is used for another purpose. Is it possible to escape this symbol somohow or use another notion?

My validation rules:
        'name:et' => 'nullable|string|max:255|required_without:name:en',
        'name:en' => 'nullable|string|max:255|required_without:name:et',

**Comment by jaaksarv** [comment]
Got it working with rules:
        'name:et' => 'max:255|required_without:name:en',
        'name:en' => 'max:255|required_without:name:et',

**Comment by dimsav** [comment]
@jaaksarv feel free to open a PR with the changes you recommend in the docs.
