### ISSUE TITLE
Does this Package Support Lumen Microframework

### ISSUE THREAD

**Issue by deep88** [dimsav/laravel-translatable#327]
i want to use this package with lumen.. can anybody tell me does it work with lumen 5.4

**Comment by dimsav** [comment]
As you can see, this package only requires illuminate support: https://github.com/dimsav/laravel-translatable/blob/master/composer.json#L15

It should be fine.

**Comment by jumshud** [comment]
İt support Lumen. Just you need add this package before:
https://github.com/irazasyed/larasupport

**Comment by dimsav** [comment]
Let's update the docs with this question/answer.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
