### ISSUE TITLE
Can't query post_id = 2, >1

### ISSUE THREAD

**Issue by xitrum2406** [dimsav/laravel-translatable#328]
it's ok when query post_id>0, post_id=1 but it's not work when query post_id=2, post_id>1

app()->setLocale($lang);
$list = post::join('posttranslation as pt', 'post.id', '=', 'pt.post_id')
->where('post_id','=',2)
->first();

**Comment by dimsav** [comment]
Not sure how your tables are setup or what you try to do with this query. Please make sure you follow the conventions for table and column names and to read the docs about how to use the package.
