### ISSUE TITLE
Code not working on server

### ISSUE THREAD

**Issue by Varun-Yuvisha** [dimsav/laravel-translatable#335]
Here is the code :- 

```php
foreach (['en','fr'] as $row) {    //line1
    $title = (!empty($request->$row["video_title"]) ? $request->$row["video_title"] : "");    //line2
    $videoModel->translateOrNew($locale)->video_title = $title;
}
```

This code is working fine on local environment but gives issue on server as "Illegal string offset 'video_title' " in second line i.e. line 2 . 

I have even kept the video_title in single quotes then also give same error.

Please help.

**Comment by Spodnet** [comment]
Have you tried $request->{$row['video_title']} ?

**Comment by dimsav** [comment]
It's hard to say what could be the error. If you are sure the code is the same on the server and locally it might be that your php version is different. Try to debug.

Closing as irrelevant to the package.
