### ISSUE TITLE
Route model binding

### ISSUE THREAD

**Issue by lchachurski** [dimsav/laravel-translatable#337]
Hello, 

Is route model binding supported? https://laravel.com/docs/5.4/routing#route-model-binding 

It sort of work when using `SportTranslation` model as bind class. But, there is no way to query back to main Sport class without creating relation. Therefore I think this isn't the proper approach.

Is there a way to define `getRouteKeyName` method of Sport class, which would work? Or do I have to try with approach mentioned above / Explicit Binding?

```php
namespace App;

use Dimsav\Translatable\Translatable;

class Sport extends UnguardedModel
{
    use Translatable;

    /**
     * @var array
     */
    public $translatedAttributes = ['name', 'slug'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function categories()
    {
        return $this->hasMany(Category::class);
    }
}
```

```php
namespace App;

use Dimsav\Translatable\Translatable;

class Category extends UnguardedModel
{
    use Translatable;

    /**
     * @var array
     */
    public $translatedAttributes = ['name', 'slug'];

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function sport()
    {
        return $this->belongsTo(Sport::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tournaments()
    {
        return $this->hasMany(Tournament::class);
    }
}
```

```php
// controller class
    public function tournaments(Category $category, Tournament $tournament)
    {
        dd($tournament);
    }
```

```php
// route
Route::get('tournaments/{category?}_{tournament?}', 'TournamentsController@tournaments')->name('tournaments');
```

This approach results with: 

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'slug' in 'where clause' (SQL: select * from `categories` where `slug` = italy limit 1)

**Comment by Gummibeer** [comment]
I don't recommend to use translatable texts as url fragments. They are more than not unique. :/
But if you rly want to do it and know what it means: I don't know a direct way. This package is based on a trait and simple relation methods.
So yes, you have to add the relation and load it indirect. The only way I can imagin is to hook into the auto-find process (from route element to model). What you have to do, everywhere/time, you have to find the translation record and after this find the main record with the id from translation.

**Comment by lchachurski** [comment]
Thanks @Gummibeer, I've made my records unique so no worries :)

For anyone interested, my final solution is explicit binding:

```php
class TranslatableServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        Route::bind('category', function ($value) {
            return Category::whereHas('translations', function ($query) use ($value) {
                $query->where('locale', App::getLocale())->where('slug', $value);
            })->first();
        });

        Route::bind('tournament', function ($value) {
            return Tournament::whereHas('translations', function ($query) use ($value) {
                $query->where('locale', App::getLocale())->where('slug', $value);
            })->first();
        });
    }
}
```

**Comment by emco83** [comment]
I have the same issue and I can see hee that @lchachurski has a  solution.
Please help where should I put that class TranslatableServiceProvider?

**Comment by lchachurski** [comment]
`app\providers\TranslatableServiceProvider.php`

https://laravel.com/docs/5.5/providers

**Comment by emco83** [comment]
Awesome! Thank you very much!

**Comment by CristianH033** [comment]
first() or firstOrFail() dont trigger the 404 error, what can I do?

**Comment by lchachurski** [comment]
This is unexpected in case of firstOrFail(). Do you type hint variables in action method like I did in the example? If nothing helps, as a last thing to do, which is generally ugly-ish solution, is to handle this in the controller and throw an error when binded value is not what you expect.

**Comment by CristianH033** [comment]
Forget it, it's my mistake, App:: getLocale () gave me back the default locale but not the current locale in the sesión.
Sorry
