### ISSUE TITLE
Using "pluck" with translated columns

### ISSUE THREAD

**Issue by stefkes** [dimsav/laravel-translatable#339]
Is there any way I can get the `ID` from the blogs table and the `title` from the blogs_translations table in one simple query, for all my records?

This doesn't work

`$blogs = Blog::pluck('id','name');`

EDIT, this snippet from the documentation should do exactly what I'm looking for but it just returns the full database records and not an id / name key value pair

`Country::listsTranslations('name')->get()->toArray();`

EDIT2, ok found a working solution. Hopefully this can help someone.

`Blog::listsTranslations('name')->where('online', 1)->pluck('name', 'id')->toArray();
`

**Comment by saidbakr** [comment]
I'd like to add something:
I used it without `toArray` and it works fine for Laravel collective dropdown list.
**Suggestion**
I suggest to add this post as it is in the FAQ section of the documentation. It is very useful.
