### ISSUE TITLE
How to translate all String in website by using Laravel-Translatable ? 

### ISSUE THREAD

**Issue by phuongphally** [dimsav/laravel-translatable#342]
I understand to used  model translate in my project but I don't know how to use this package for translate full string in my website . 

Can you give me an example how to use it ? 

Thanks.

**Comment by dimsav** [comment]
Hello, this project is only for translations of models (saved in the database). For translating parts of templates check the [localization page in the laravel docs](https://laravel.com/docs/5.4/localization).
