### ISSUE TITLE
Elasticsearch n+1 bug ?

### ISSUE THREAD

**Issue by Melcus** [dimsav/laravel-translatable#343]
Using this package : https://github.com/sleimanx2/plastic

For  
`$model = Model::search()->querystring('*' . $search_keyword . '*' , ['fields' => ['suggestions' ])->get();`
it queries
```SELECT * FROM `model_trans` WHERE `model_trans`.`model_id` IS NULL and `model_trans`.`model_id` IS not NULL and `model_trans`.`deleted_at` IS NULL```
for every result. This only happens when I have the Translatable trait on the model. 

What would you suggest?
Opened a ticket on the said package as well https://github.com/sleimanx2/plastic/issues/92

**Comment by dimsav** [comment]
Support for other packages cannot be provided here, sorry. Feel free to explore to understand how you can achieve what you want.
