### ISSUE TITLE
Eager load/query relations not working?

### ISSUE THREAD

**Issue by cewlbird** [dimsav/laravel-translatable#345]
Hi dear Dimitris,

first of all thank you for this great package!
But I am currently struggling to get my models relations right.

Do I have to put the relation inside the main model or do I have to put it inside the ModelTranslation? Both ways dont work for me, especially because the foreign key only exists within the translation table as all attributes are translated within my model.
Also please note that all my relations to that model are also translatable.

**By not working I mean the following:**
- As the foreign key is not part of the model, it doesnt find the foreign key
- When I put the relation inside the translation model, it cant find it too

**Used Models**
- Meal (Belongs to one MealCategory and can have many Prices)
  Would this work with many-to-many? If yes, how is the right approach?
- MealCategories (Can have many Meals)
- Price (Belongs to Meals)
- PriceType (Belongs to Price, price_type_id in Price Model)

Do you have an examples on how I can use one-to-many relations (or other relations) in combination with this package?
Thank you in advance.

Best Regards,

CEWLBIRD

**Comment by Gummibeer** [comment]
There is no problem with relations and this package.

For every translated model you have two models and tables - the main/basic model and the translated one. The translated ist related to the main one with a one-to-many.
If you have more relations just add them on the main model like without this package and documented in the laravel doc.

for example:
meal to mealcategory

`$meal->translations()`
`$mealTrans->meal()`
`$meal->category()`
`$category->translations()`
`$categoryTrans->category ()`
`$category->meals()`

And even if all fields are translatable, your ID isn't - or how do you identify a row without ID?

**Comment by cewlbird** [comment]
Hi @Gummibeer,

thank your for your answer.

I tried it like that but it still cant access those relations (undefined method, property undefined etc.)
Also by ID, do you mean the foreign key used for accessing the relations, like meal_category_id?
Do I put this inside the main model or inside the translation model? At the moment its just inside the translations table.

Best Regards,

CEWLBIRD

**Comment by Gummibeer** [comment]
Ok, your main model should contain at least an id-column (primary index).
The translations table has the foreign key column `meal_id` and als it's own `id`.
If you want a relation between meal and category in a one-to-many: the meal table has a foreign key `category_id` and the category table has it's own id column (primary index).
If the category is also translatable the category translation table has a foreign key column `category_id`.

This structure is endless. And dependent on the column naming you can use the simple relation methods with one Argument (related model class) or you also define the foreign and local key.

https://laravel.com/docs/5.4/eloquent-relationships

**Comment by cewlbird** [comment]
Hi @Gummibeer,

yes the id column is mandatory, so its always present in my models.

I do unterstand the whole point of eloquent relationships as I am using Laravel quite a while, but somehow I just cant get it to work properly within this package as it always says that this relation/method doesnt exist.

I have my relations set up within the main models like you said and I am tring to access it, but it doesnt seem to work.

```
$meal_categories = MealCategory::find(3);
dd( $meals->translations->meals );
```

Results in _Property [meals] does not exist on this collection instance._
Changing meals to _->meals()_ results in a missing method exception, same goes for _->translations()_.

Thank you so far for your help.

Best Regards,

CEWLBIRD

**Comment by Gummibeer** [comment]
You access it wrong.

The relation is on the main model, so access it from the main one. ;)

`$category->meals`

Why do you try to access it from the translations? which is not an eloquent model but a collection.

**Comment by cewlbird** [comment]
Hi @Gummibeer,

I know that already (I was wondering myself too, but I am too desperate^^), but I cant access the relation on the main model because there is no foreign key to relate that model to the other. The foreign key of the meal_categories is just inside the meal_translations model, because I thought this is the way to go?

This means I should add the foreign key to the main model instead on the meal_translations?
I am so sorry to bother you with so many questions.

Best Regards,

CEWLBIRD

**Comment by Gummibeer** [comment]
Yes, why you want it translated? Your way would result in something like:

> One meal has `n` translations and every meal-translation is related to one meal-category.

This means that the english meal translation has another category than the french one!?
If it is like this, you should think in general about your structure cause than the translations aren't just translations.

And in your current structure you can also do it, but have to get a model and not a collection: `$meal->translations->first()->category`.

**Comment by dimsav** [comment]
@cewlbird please make sure you've read the [docs](https://github.com/dimsav/laravel-translatable/blob/master/readme.md). You can see examples of how to structure your relationships in the docs or in the [tests](https://github.com/dimsav/laravel-translatable/tree/master/tests/models).
