### ISSUE TITLE
Magic properties not working

### ISSUE THREAD

**Issue by melokki** [dimsav/laravel-translatable#351]
Hello,

I am trying to use this package in my laravel app, but I have some problems using it.

I am trying to use the magic properties, but it's not working.
This is my model class
```
class Location extends Model
{
    use Sluggable;
    use SoftDeletes;
    use Translatable;

    public $translatedAttributes = ['name', 'location', 'details'];

    protected $fillable = ['name','city_id','category_id','location','details'];
```
and this is my Translation class

```
class LocationTranslation extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'location', 'details'];
}
```
When I try to access a model property  like this
```
$location = Location::all()->first();

dd($location->name);
```

I get `null` and I don't understand why.

My default language is set in laravel config to `ro`
so when I want to print a location name I am expecting to just print `$location->name` and to get the default name of the location, witch is in `ro` when I change the app language to `en` , for example, I expect to get the location name translated, it's not this the default behavior?

I use the latest version of the package and laravel 5.4

**Comment by melokki** [comment]
Ok, i figured out why is not working as expected. 
In my Translation table I did not inserted a row for the default locale because I thought it is not necessary and when I will echo the name it will give me the name from the Location Model not from LocationTranslation Model.

I'm looking for a solution to implement this behavior for my app.

**Comment by Gummibeer** [comment]
We had the same and it's simple, you just have to override the setter and getter method on the main model - you can extend the eloquent one and extend from this or write a trait to save copy'n'paste.

```php
public function getAttribute($key)
    {
        if (str_contains($key, ':')) {
            list($key, $locale) = explode(':', $key);
        } else {
            $locale = $this->locale();
        }
        if ($this->isKeyALocale($key)) {
            if ($this->getTranslation($key) !== null) {
                return $this->getTranslation($key);
            }
        }
        if ($this->isTranslationAttribute($key)) {
            if ($this->hasTranslation($locale)) {
                if (!empty($this->getTranslation($locale)->$key)) {
                    return $this->getTranslation($locale)->$key;
                }
            }
        }
        return parent::getAttribute($key);
    }
    public function setAttribute($key, $value)
    {
        if (str_contains($key, ':')) {
            list($key, $locale) = explode(':', $key);
        } else {
            $locale = $this->locale();
        }
        if ($this->isTranslationAttribute($key)) {
            $this->getTranslationOrNew($locale)->$key = $value;
        }
        parent::setAttribute($key, $value);
    }
```

**Comment by Gummibeer** [comment]
I'm not 100% sure if this works in latest version and if this is everything you need to change - we use an older version and could be that there is something in the `fill()` method you also have to change. The main change is: put attributes that are translated in both models - so you have the fallback from the main model and also all translations in the translated model. In this solution, I think, the last value is in the main model - not sure. You can change and extend this with some ifs.

I hope this helps!?

**Comment by melokki** [comment]
Thank you for your reply @Gummibeer  
I'll try your solution when I get home tonight and I'll come back to tell you if it worked or not.

**Comment by melokki** [comment]
OK I had to extend the Translatable trait to modify the getAttribute method, nothing too complicated

```
if ($this->getTranslation($locale) === null) {
                return null;
            }
```

instead to return `null` I've returned `parent::getAttribute($key)` and now I got the expected behavior
Thanks again @Gummibeer for your snippet

**Comment by Gummibeer** [comment]
I think that you also have to override the set method - otherwise no value will find it's way in the main table!?

**Comment by melokki** [comment]
Yes, you are right, I had to override the set method too, and now everything works good, thanks again @Gummibeer :)

**Comment by Gummibeer** [comment]
Wouldn't it be better if you do `if empty(parent::getAttribute)` (pseudo code - on phone)!? With this you will set it just if it isn't set on your main model.

**Comment by melokki** [comment]
Yeah, that's a good point, thanks again for your support

**Comment by dimsav** [comment]
@melokki I see you have a `name` attribute in your `Location` model. You also have a name attribute in the `LocationTranslation` model. This is not how your models should be structured.

The `name` attribute should exist only in the translation model/table.

**Comment by Gummibeer** [comment]
@dimsav That's why we adjusted the setter and getter methods. There are reasons to have this setup and having a fallback on the main model.
For example we have a translation page over all models. To simplify and speed the validation and save process we have the fallback. With this we don't need a validation that a translation has to exist for every model.
