### ISSUE TITLE
How to avoid adding empty translation entries?

### ISSUE THREAD

**Issue by unitedworx** [dimsav/laravel-translatable#353]
my form data is structured using [language][field] so essentially with a $model->fill i can save my data. however if i enter data only for my main langauge then empty records will be added for my extra language and fallaback wont work sicne a record is there but with empty fields.

also the ideal solution would be to both not add a row in translation table if the all fields are empty for a specific language and even furhter when updatign a record it should delete the translation for a language row if all its fields are empty.

let me know if package handles this or i need to do this manually, inthe later case maybe you shoud consider baking this in to improve usability of the package!

**Comment by drbyte** [comment]
Maybe $model->fill isn't the best approach?

Perhaps `intersect` would be more ideal?  See: https://dyrynda.com.au/blog/partial-model-updates-in-laravel

**Comment by Gummibeer** [comment]
I would recommend to override the `setAttribute()` method in the trait. There you can add an if like `!empty($val)` and prevent this from getting saved. Or you do it in the `saving` observer of the TranslatedModel and return false if it's empty.

**Comment by unitedworx** [comment]
fill = magic = a keeper :) 

here is my solution

```
	$emptyLocale = $this->getLocaleWithEmptyData($data);
	$data = array_except($data, $emptyLocale);
        $article->fill($data);		
        $article->Save();
	$article->deleteTranslations($emptyLocale);
```

while utilizing this trait i created (since these will be needed in all my models that are translatable)

```<?php namespace App\Traits;

trait GetLocaleWithEmptyData {

	public function getLocaleWithEmptyData($data)
	{
		$emptyLocale = [];
		foreach (config('translatable.locales') as $locale){
			if (empty(implode('', array_get($data, $locale)))){
				$emptyLocale[] = $locale;
			}
		}
		return $emptyLocale;
	}

}
```
