### ISSUE TITLE
Getting null for some of the translated attributes

### ISSUE THREAD

**Issue by sanjivsharmalv** [dimsav/laravel-translatable#363]
Hello,

My models are as follows:

Faq:

```php
class Faq extends Model
{
    use Translatable;
    public $translatedAttributes = ['question','answer'];
    public function faqtranslations() {
        return $this->hasMany(FaqTranslation::class);
    }
} 
```

and FaqTranslation:

```php
class FaqTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = ['question','answer'];
}
```

And here is my Show method from FaqController:

```php
 public function show($id)
    {
        $faq = Faq::find($id);

        $faq_translations = Faq::join('faq_translations as t', 't.faq_id', '=', 'faqs.id')
            ->where('t.faq_id', $id)
            ->select('t.locale','t.question','t.answer')
            ->get();

        return view('dashboard.faqs.show', compact('faq_translations'));
    }
```

In response to {{$faq_translations}} as expected this is what I get:

Following are the results on the view page:
On this {{$faq_translations}}
I get:
[{"locale":"lv","question":"lv-q","answer":"lv-a"},{"locale":"ru","question":"ru-q","answer":"ru-a"},{"locale":"en","question":"en-q","answer":"en-a"}] as expected

On this {{$faq_translations[0]->locale}}
I get 'lv' as expected

On this {{$faq_translations[0]->question}}
I get 'null' - NOT expected, **expected** is **'lv-q'**
The same is true for other members of the array. Please advise, what is that I am missing here.

**Comment by dimsav** [comment]
Why do you query the translations using the join? Have you tried this?

```php
$faq = Faq::with('translations')->find($id);
```

**Comment by sanjivsharmalv** [comment]
Thanks for the response.
Meanwhile, 
This has worked:
$faq = Faq::find($id);
$faq_translations = $faq->faqtranslations()->get();

Following 
$faq = Faq::with('translations')->find($id);
gives the error:
Trying to get property of non-object.

**Comment by dimsav** [comment]
Glad you found a solution.
