### ISSUE TITLE
Json array doesn't update when adding a new key and value

### ISSUE THREAD

**Issue by fmcdigital** [dimsav/laravel-translatable#365]
I have a repeater field that adds images and descriptions, so the user can add how many he wants.
But, If i'm in Spanish language and modify the description, then in English I add another row, the Spanish won't add this row automatically, I'll have to add it manually.

It happens because json fields does not have a single id.
Is there anyway to solve this problem?

**Comment by dimsav** [comment]
Hello, we need to see the code to understand.

**Comment by fmcdigital** [comment]
It works like this:

If I add 5 elements in a json array column while in English language and then I change to Spanish it's column won't update, I'll have to add those same 5 elements while editing in Spanish.

Example of this json array:

```
[{"img": "img.jpg", "description": "Some description"}, {"img": "img2.jpg", "Some Description 2": ""}]
```

**Comment by dimsav** [comment]
A json array is not php code. How can we help if you don't show your actual code? How is this json used? Have you tried using the examples in the docs and tests?

**Comment by Gummibeer** [comment]
I recommend you to switch to any media attachment setup like in https://github.com/spatie/laravel-medialibrary and use the translation model for every image entity. Atm you try to translate descriptions for multiple entities (images) in one table row/entity - this will explode at any time. So split it into more tables/entities and you will be fine.
