### ISSUE TITLE
Using main table for default application locale.

### ISSUE THREAD

**Issue by Shogun147** [dimsav/laravel-translatable#367]
Hi,

Is there a way how can we set this package to save translatable attributes to default table for default locale instead of translation table?

Why there is such a need to forcing us always using translations tables when we can keep for example "countries.name" attribute in "countries" table and use "countries_translations" only in case there is a different locale requested?
This makes some sense as it will help us getting rid of forced queries to translations tables every time.

Can you advice something for this if there is a solution or small refactoring that can make it possible?

Thanks!

**Comment by dimsav** [comment]
Hello @Shogun147,

unfortunately it is not possible to use this package using all the translations into the default table. 

Indeed, the structure seems a bit complicated but for us it totally makes sense. The reason is that the translation has a one to many relationship with the model. How would you have a one to many relationship within one table?

Cheers!

**Comment by Shogun147** [comment]
Hello @dimsav,

I didn't mean that we need one to many relationship within one table, it will still have this relation with translations table, but only for non-default locales.

For example:

countries
-----------
id
_name_ (for default locale, ex: en)
code

country_translations
---------------------
id
country_id
_name_ (for non-default locales)
locale

So by default we will save translatable attributes in main table and only if there are translations we can save them in translations table.

Do you understand now what i mean?

**Comment by dimsav** [comment]
I see. What if you plan to change the default locale at some point down the road?

**Comment by Shogun147** [comment]
@dimsav - i don't think that changing default locale happens so often that it's worth it, imho. However in such case we can fallback to current method and just use translations for default locale.

**Comment by dimsav** [comment]
I agree. It seems we could add this as optional feature.

**Comment by Shogun147** [comment]
Okay, thanks!

Any idea how much time it would take to implement this and when it would be available? It doesn't seems to need much refactoring from what i understand, but you know it better of course. :)

Anyway, thanks for great work!

**Comment by dimsav** [comment]
Well this is an open source project. Feel free to implement it and submit a PR :-)

**Comment by Shogun147** [comment]
Ye, agree. :)

I will see when will be able to do it, however i think you know best approach for this package to implement such new features. :-)

**Comment by dimsav** [comment]
Give it a try. We're all here to help.

**Comment by Shogun147** [comment]
Okay :) 👍
