### ISSUE TITLE
need 'hasTranslation' validation

### ISSUE THREAD

**Issue by Cyrille37** [dimsav/laravel-translatable#368]
Hi,
Thanks a lot for this really useful package :-)

A Translatable model can be saved without its translation if translated fields are not filled ... I think it's not good because translated attributes are _finally/really_ model's attributes.

I've the translatable model News, but I do not want to record a News if no translation defined.

Here is what translatable model permits :
```
 $n = News::create();
 $this->assertNotNull( $n->id );

 $this->assertEquals( 1 , News::count() );
 $this->assertEquals( 0 , NewsTranslation::count());
 $this->assertEquals( 0, $n->hasTranslation() );
 $this->assertNull( $n->title );
```
It could be useful to have the possibility to define a validation $rule for translatable model that do not permits to save it if no translation exists ($n->hasTranslation() != 0).

Do you see ?

Cheers,
Cyrille.

**Comment by dimsav** [comment]
Interesting. So you want before saving your model to throw an exception if no translation is set?

What exception would you throw? Under what conditions would you prevent the model to be saved?

**Comment by Cyrille37** [comment]
I do not really know for a general way, but for my need ...
- It's strange to have a line in Model but none in ModelTranslation
- A validation rule that check default language translation exists if `$useTranslationFallback` is set
Sorry to don't be more creative :-)

**Comment by Gummibeer** [comment]
From the title I thought it's about a validator. But throwing an exception in the save observer is a very specific behaviour. This point is, in most situations, too late. In multi-model forms other models are already saved, I have to catch it for a redirect and so on.
So this isn't something that will improve most applications. Instead I would prefer a validator like the `exists` one. With a lot of optional parameters to define the table, column and so on.

**Comment by Gummibeer** [comment]
```php
[
// ...
'name' => 'translated:'.Country::class,
// or
'name' => 'translated:country_translations',
// ...
]
```

**Comment by Cyrille37** [comment]
Hi,

Yes @Gummibeer you've right about Exception. I talk about exception because I always use [Esensi\Model\Model](https://github.com/esensi/model) which can throw Validation Exception (for multi-models I use a DB Transaction).

A **validator** is the right solution :-)

**Comment by dimsav** [comment]
Feel free to open a PR :-)
