### ISSUE TITLE
Get translations "dirty" in observers.

### ISSUE THREAD

**Issue by krecebli** [dimsav/laravel-translatable#373]
Hi. First, thanks for such a helpful package, and happy Ramadan! :)

This issue is actually a question, but I think this is the best place to ask it.

I use an observer to log model changes for the revision by super admin. But `getDirty()` doesn't contain translated attributes. I tried to work-around this, but any trying works only if translated attributes changed. So, how can I solve this?

**Comment by dimsav** [comment]
Indeed getDirty() needs to be customized if we want to include translations. 

Feel free to open a PR with your recommendation :-)

**Comment by krecebli** [comment]
I did an implementation, but it works when if only translated attributes are changed. If there is any changed non-translated attribute, it doesn't contain dirty translated attributes. So, do I open a PR in order you can to review my implementation attempts? :)

**Comment by krecebli** [comment]
Although, it will work if `$this->saveTranslations()` will be before the `parent::save($options)`

**Comment by dimsav** [comment]
Thanks, I will review your pr

**Comment by krecebli** [comment]
not at all :)
