### ISSUE TITLE
I search only first country and show me all translations also

### ISSUE THREAD

**Issue by francisrod01** [dimsav/laravel-translatable#377]
This is a bug, yeah? 0.o

I recently used this repository to translate my records of location's addresses and I liked it very much, but I have a problem with get only one translation and all translations of location put the output.

See the code below:

```php

     * @param $placeId
     * @param $language
     * @return \Illuminate\Http\JsonResponse|string
     */
    public function show($placeId, $language = null)
    {
        /** @var Location $location */
        $location = Location::where(['place_code' => $placeId])->first();

        if (!empty($language)) {
            if ($location->hasTranslation($language)) {
                $translation = $location->getTranslation($language);
                $address = $translation->getAttribute('address');

                $location->address_components = json_decode($address);
            }
        }

        return $location;
    }
```

The code is based of `Feature list` --> Available methods.

https://github.com/dimsav/laravel-translatable#available-methods

But here, I follow my especific route `/api/restricted/locations/<placeId>/<language>`

And the screen sees more details:

![image](https://user-images.githubusercontent.com/4691768/27612894-12563374-5b6f-11e7-9db1-bcbe4b04bb95.png)

The `address` object also appears in response, but this is wrong object because is in English, but the translation searched is in portuguese.

The `Location` model:

```php

class Location extends Model
{
    use Translatable;

    protected $table = "locations";

    public $translatedAttributes = ['address'];
    public $translationModel = 'App\Models\LocationTranslation';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'place_code', 'address_components', 'geometry', 'types'
    ];

...

```

Something else to configurate and I'm not know yet?

**Comment by francisrod01** [comment]
My workaround is Laravel [eager-loading](https://laravel.com/docs/master/eloquent-relationships#eager-loading) but this is not solved because all the location are loading before relationship is loaded with `with()`.

I think in a solution but until not be able this.
I'm thinking of when I'm going to list all the locations and all of your 20 translations are loaded together. Multiply that by 10k users.

**Comment by dimsav** [comment]
Do you have this in your config?

'use_property_fallback' => true,'

**Comment by francisrod01** [comment]
Yes it is but I'd not like to override the original text.
I'd like to bring from the database the original information + a specific translation.

**Comment by Gummibeer** [comment]
Do you set the language from the url anywhere as the language to use for translations!? I don't see it and by default the App locale is `en` and this is used. So try to do an `App::setLocale($language);`

**Comment by francisrod01** [comment]
Thanks @Gummibeer and @dimsav for your help!
Now I solved using setLocale before returned the location to the API.

This way I can perform a much simpler search than the one I was performing and set the language of the application shortly before returning the data through the API.
