### ISSUE TITLE
Removing prefix on default language ?

### ISSUE THREAD

**Issue by nick2102** [dimsav/laravel-translatable#383]
Hello there , I am pretty new at laravel , and I've started my first project with translations. I can't figure out if it is possible to remove the prefix for the default language .  For example if the site def language is English the url should be example.com and if it is French example.com/fr ?

**Comment by jonasva** [comment]
I don't think this package handles any URL logic, you have to work that out yourself. Like in the [tutorial](https://laravel-news.com/how-to-add-multilingual-support-to-eloquent) in the readme.

You could do something like adding the locale (prefix) as an optional route parameter, and set your app's locale to the default locale if no the parameter was not found in the route.
