### ISSUE TITLE
Unable to use with Redis

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [dimsav/laravel-translatable#387]
I'm trying to cache a query with all posts. I tried to cache the posts like this `Post::translated()->get();` which actually caches all the data, however, when you open the page it still makes a query everytime `SELECT * 
FROM `post_translations` 
WHERE `post_translations`.`post_id` = 1 and `post_translations`.`post_id` is not null`

**Comment by dimsav** [comment]
Have you eager loaded the translations?

**Comment by Gummibeer** [comment]
closed due to inactivity
