### ISSUE TITLE
Load without $translatedAttributes

### ISSUE THREAD

**Issue by graveeel** [dimsav/laravel-translatable#389]
Hi there, 
I'm stuck getting the main Model loaded without loading the $translatedAttributes. 
I have like 20 translated attributes which I do not want to load each time. 

Is there a simple way to select the $translatedAttributes which are being mapped while selecting the main model?

Thanks, 
Graveeel

**Comment by dimsav** [comment]
Have you tried using eloquent's `whereHas()` to load the translations you need?

**Comment by graveeel** [comment]
Hi thanks for your reply, 
It's not working somehow. 
I have a List with objects which have translated attributes. 

I only what to get the object id without any translations. 

E.g.
$query = Object::select('id'); 

But the Translatable class loads afterwards and I have two queries and every attribute attached. 

![image](https://user-images.githubusercontent.com/19874902/30244350-7bb35fc2-95bc-11e7-8bd4-b640a2befc69.png)

Is there a way to run a eloquent query without the translations being added? 

Thanks, 
Graveeel

**Comment by graveeel** [comment]
Solved by config.
