### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by exabyssus** [dimsav/laravel-translatable#390]
Laravel 5.5 is about to get released and many people are already using it. Can we expect this package to get update to support the new version?

**Comment by HappyLDE** [comment]
I installed the Laravel 5.5 release and no translation available... now i'm blocked

**Comment by gabrieldasilva** [comment]
Hey! Just quick question... anyone knows if the 7.0 version of the package works with L5.5?

Know i don't have the time to test it on a clean project. Maybe I'll do it later.

**Comment by JackWH** [comment]
@gabrieldasilva It doesn't unfortunately. The version requirements in `composer.json` require `"illuminate/support": "5.4.*"` and `"phpunit/phpunit": "~5.7"`, which binds it tightly to Laravel 5.4.

I think all that @dimsav needs to do is change these version requirement bindings, and issue a new release. Perhaps don't tie up a requirement to `illuminate/support` and `phpunit/phpunit`, and instead just tie a requirement to `laravel/framework`, which already depends on these two packages?

**Comment by gabrieldasilva** [comment]
@JackWH yeah, u're right. 

Like you said I think this is not a head break update... just with the version changes may work. 

And yeah, the change on package dependencies may be good... +1 for that

**Comment by dimsav** [comment]
The update for Laravel 5.5 will be released soon :-)

**Comment by dimsav** [comment]
Done 🙂

Thanks for your patience and support  ❤️

**Comment by progsmile** [comment]
You are awesome) I was waiting for that)
