### ISSUE TITLE
How to perform validation?

### ISSUE THREAD

**Issue by mrKorg** [dimsav/laravel-translatable#391]
Hi. Thank you for the wonderful package.

I have a question, how to implement data validation for transaction Requests? 
I'd like to use messages for validation errors.

**Comment by Gummibeer** [comment]
In #368 was a similar question. But it depends on your implementation of validation, Whatyou want to validate and so on - that's why a general solution isn't this easy.

**Comment by Gummibeer** [comment]
closed due to inactivity
