### ISSUE TITLE
Question : How to use the package with Search (scout, algolia)

### ISSUE THREAD

**Issue by mydnic** [dimsav/laravel-translatable#392]
Hello @dimsav !

I'm trying to implement Laravel Scout + Algolia on a website that has translated models.

In algolia I created two indexes : one for the Product model and the other for the ProductTranslation model.

Obviously I want to search into the content, which is stored in the translations.
I can do : `ProductTranslation::search($request->q)->get();` but I want to retrieve a list of Product model, instead of ProductTranslation model.

Any help on how to achieve this ? :)

Thanks in advance

**Comment by dimsav** [comment]
Hi @mydnic !

I happen to implement algolia and laravel scout for the company I'm working lately https://metabook.gr and this is how I would index translatable models with scout:

I would add only one index that contains the translations as property:

```php
public function toSearchableArray() {
    'some_property' => 'value',
    'translations' => $this->translations->toArray(),
}
```

Feel free to replace `$this->translations->toArray()` with an array that does what you want.

**Comment by Gummibeer** [comment]
solved

**Comment by eliyas5044** [comment]
sorry for commenting in closed issue :(
if i put `translations` in searchable array, got sql error
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'translations' in 'where clause' (SQL: select count(*) as aggregate from `posts` where (`translations` LIKE %lorem%) and `posts`.`deleted_at` is null and exists (select * from `post_translations` where `posts`.`id` = `post_translations`.`post_id` and `locale` = en))
```
> post model
```
public function toSearchableArray()
    {
        return [
            'translations' => $this->translations->toArray()
        ];
    }
```
> controller
```
public function search(Request $request)
    {
        $posts = Post::search($request->get('query'))->paginate(3);

        if ($posts->isNotEmpty()) {
            return PostOneResource::collection($posts);
        }
        return response()->json('No news found, please try with different keywords.', 404);
    }
```
Thanks in advance.

**Comment by Gummibeer** [comment]
@eliyas5044 pls open a new issue. This is about implementating scout+algolia in general, you have a specific exception.

**Comment by Briareos17** [comment]
@dimsav What about searching only by specified fields of translation?

**Comment by Gummibeer** [comment]
@Briareos17 this can also be done by scout. Otherwise we also provide a scope to find the main model by the translation.

**Comment by Briareos17** [comment]
@Gummibeer Question was about how to do not return all translated fields but only specified.
I think i found a solution: overload method `toSearchableArray` and get fields with next code:

    public function toSearchableArray()
    {
        $array = $this->translations->mapToGroups(function($item, $key){
            $fields = [];

            foreach ($this->searchableAttributes as $attribute) {
                if ($this->getAttribute($attribute)) {
                    $fields[] = $this->getAttribute($attribute);
                }
            }

            return [
                $item->locale => $fields
            ];
        });

        return $array;
    }
