### ISSUE TITLE
getAttributeOrFallback() method is doing weak comparisons to assess if a value is set, causing problems with booleans and integers

### ISSUE THREAD

**Issue by JackWH** [dimsav/laravel-translatable#393]
I'm using attribute fallbacks with my models, and am having problems when the attributes are cast as `boolean` or when the attribute can be an `int` with a value of `0`.

In `Translatable.php`, the following function gets the attribute or fallback if the attribute doesn't exist:

```
    /**
     * Returns the attribute value from fallback translation if value of attribute
     * is empty and the property fallback is enabled in the configuration.
     * in model.
     * @param $locale
     * @param $attribute
     * @return mixed
     */
    private function getAttributeOrFallback($locale, $attribute)
    {
        $value = $this->getTranslation($locale)->$attribute;

        $usePropertyFallback = $this->useFallback() && $this->usePropertyFallback();
        if (empty($value) && $usePropertyFallback) {
            return $this->getTranslation($this->getFallbackLocale(), true)->$attribute;
        }

        return $value;
    }
```

I think there are three problems here:

1. The function checks `if (empty($value) ...`, which causes a `boolean` with a value of `false` or an `integer` with a value of `0` to be considered "empty". Really, these could be valid attribute values on a translated model. Shouldn't an `isset()` check or something be done instead?
2. If trying to access a property like one described above on a translated model, but no fallback translation is available, a PHP error is thrown. I would have thought that if the property didn't exist on the fallback translation (i.e. because the fallback doesn't exist), the original value should be returned back? Again, because the original value could be valid in some cases (see point 1), but also because if there's no fallback available, a PHP error is thrown instead.
3. The function is private, so I can't override it to fix the issue for my own use case

Is my understanding of this situation correct? I may be missing something here so was a bit hesitant to put in a pull request without double-checking.

**Comment by dimsav** [comment]
Thank you @JackWH for your thoughts. I suppose the reason why you're having this kind of issues is because you're storing non-string values as translations which is a case I didn't think when I was writing this code.

If you want to help, please make a test with your expectations that should pass now, because the behavior you're describing sounds like a bug to me.

**Comment by Gummibeer** [comment]
https://github.com/dimsav/laravel-translatable/releases/tag/v9.5.0
