### ISSUE TITLE
Cannot save data on default model

### ISSUE THREAD

**Issue by spyrosjevan** [dimsav/laravel-translatable#395]
Maybe i have misunderstood how to package works but what im trying to do is to add the default "article" data (gr) on the model article and the rest on the translation model. If this is the right method of use then the article model does not accept anything else but the code column like the example.

**Comment by dimsav** [comment]
Hi @spyrosjevan

You shouldn't store any translated property into the main model's table, but use the translated model/table instead.

If you read the docs you will have a better understanding of how this package works.

**Comment by dimsav** [comment]
Make sure your `article` column is not in your main model, otherwise that won't work.
