### ISSUE TITLE
Fallback to actual model value

### ISSUE THREAD

**Issue by Chrysanthos** [dimsav/laravel-translatable#397]
Let's say I have a table Countries [id, name, code(always 'en')] where names are in English. Then, the country_translations has only the translations for french. For some reason when I specify the locale to 'en' it returns empty (because country_translations does not have a record for this language).

Is there any way I can specify when the language is English to load the model's name and not search for a translation in the country_translations?

It seems like a duplication to have 2 times the same language.

**Comment by dimsav** [comment]
The idea is you don't put the english version to your main model's table but to the translation's table. This way there is no duplication.

**Comment by Chrysanthos** [comment]
Just saw that there is no column for the name field in the model's migration, only in the *_translations table. Everything makes sense now!

**Comment by saidbakr** [comment]
@Chrysanthos  Could I know your `config/transable.php` settings?. I have [the same issue](https://github.com/dimsav/laravel-translatable/issues/409). An empty `Model_translations` table leads to empty translable attributes!
