### ISSUE TITLE
is this the best way to make sure that timestamps work properly?

### ISSUE THREAD

**Issue by unitedworx** [dimsav/laravel-translatable#400]
I just realized today that timestamps didnt update in my models coz the actual text being updated was not in my main model but the model holding the translations. 

is this the best way to make sure that timestamps work properly? they work now but just want to make sure its the proper way to handle this. Didnt seem to see anything in the docs regarding this!

```
<?php namespace App;
use Illuminate\Database\Eloquent\Model;
class ProjectTranslation extends Model 
{
	 protected $touches = ['project']; //addition of this line
	 public $timestamps = false;
	 protected $fillable = array('name','description',);

	public function project() //addition of this relation
	{
		return $this->belongsTo('App\Project');
	}
}
```

**Comment by emco83** [comment]
I have the same problem with timestamps. 

My models are: Post and PostTranslation, so I've tried this in my PostTranslation:

```
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class PostTranslation extends Model
{
    use Sluggable;

    protected $touches = ['post'];
    public $timestamps = false;
    protected $fillable = ['title', 'slug', 'body'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function post() {
      $this->belongsTo('App\Post');
    }
}
```
but I'm receiving an error:

```
FatalErrorException
Call to a member function touch() on null

in HasRelationships.php (line 436)
```
How can I fix this?

**Comment by dimsav** [comment]
Why to you want to update the timestamps in the main model if only the translation is saved?

**Comment by catalinux** [comment]
@dimsav : this might be reasonable to expect because you might see the main model as the "root entity" of that domain problem. 

Shouldn't field $touches from the translation model work for such wish?

**Comment by dimsav** [comment]
@catalinux  We could do that and make it optional (enabled by default in the next major release).

**Comment by unitedworx** [comment]
@catalinux you not only need the $touches entry but the respective reverse relationship to the model this translation belongs to.

@dimsav translation is part of main model, although text is stored in an extra table I do need to know when an item was updated  and by whom ... so my sample code above is what makes this actually work! Just wanted to know if there is a simpler way on doing this

**Comment by Gummibeer** [comment]
@unitedworx No there isn't. Because of the fact that the translation model is generated by the developer I close this without any changes in the repo.
The only thing we can do is add a hint in the readme - I'm open for a PR to add this.
