### ISSUE TITLE
How to get  Country::All() translation for specific language  ? 

### ISSUE THREAD

**Issue by badrshs** [dimsav/laravel-translatable#401]
Hi , 
I have searched a lot and i couldn't find  the solution for this 

how can i get  translation   data for an item ? 

I can't do that without App::setlocale 
 for example I have Country::All() 

I need to take the fr without changing the locale for my user  
what i need to do ?

**Comment by elhelaly** [comment]
Did you try to use locale per model?
```
// It is possible to define a default locale per model by overriding the model constructor.
public function __construct(array $attributes = [])
{
    parent::__construct($attributes);
    
    $this->defaultLocale = 'de';
}
```

**Comment by dimsav** [comment]
@badrshs you can use eloquent. `BookTranslation::where('book_id', $id)->get();`
