### ISSUE TITLE
Need help with creating a post using this translatable package

### ISSUE THREAD

**Issue by emco83** [dimsav/laravel-translatable#402]
I've followed this tutorial for build a translatable logic: https://mydnic.be/post/how-to-build-an-efficient-and-seo-friendly-multilingual-architecture-for-your-laravel-application

Right now if I put manually records in the database by using a command from here:
https://github.com/mydnic/Laravel-Multilingual-SEO-Example/blob/master/app/Console/Commands/InsertDummyPosts.php

I can retrieve the translated posts succesfully, but how can I create a content end edit using the two tables method with translate package?

This is my code: 

PostsController

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\User;
use Session;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'desc')->paginate(5);
        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'title' => 'required',
        'body' => 'required',
      ]);

      $input = $request->all();
      $user = Auth::user();

      $user->posts()->create($input);

      session()->flash('created_post', 'The post has been created');

      return redirect('/en/admin/posts');

      // This wont work because it's trying to save the post in posts table, instead of post_translations table.
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function posts() {
      $posts = Post::orderBy('id', 'desc')->paginate(5);

      return view('posts', compact('posts'));
    }

    public function post($slug) {
      
      $post = Post::whereTranslation('slug', $slug)->firstOrFail();

      return view('post', compact('post'));
    }
}

```

From the code you can see the store method and that's working only if I store in one database without translatable package. I need help to change that.

The Post model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;

class Post extends Model
{
    use Translatable;

    public $translatedAttributes = ['title', 'slug', 'body'];

    protected $fillable = ['title', 'slug', 'body', 'status', 'locale'];

    public function user() {
      return $this->belongsTo('App\User');
    }

    public function posts() {
      return $this->hasMany('App\Post');
    }
}

```

The PostTranslate model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class PostTranslation extends Model
{
    use Sluggable;

    public $timestamps = false;
    protected $fillable = ['title', 'slug', 'body', 'status', 'locale'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
     public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}
```

The User model:

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function isAdmin() {
      if($this->role->name == 'Administrator') {
        return true;
      }
      return false;
    }

    public function posts() {
      return $this->hasMany('App\Post');
    }
}

```
database/migrations/2017_09_26_140138_create_posts_table.php

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('posts');
    }
}
```
database/migrations/2017_09_26_140327_create_post_translations_table.php
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePostTranslationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('post_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('post_id')->unsigned();
            $table->string('locale')->index();

            // The actual fields to store the content of your entity. You can add whatever you need.
            $table->string('title');
            $table->string('slug')->unique();
            $table->text('body');
            $table->integer('status')->default(0);

            $table->unique(['post_id', 'locale']);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('post_translations');
    }
}
```

resources/view/admin/posts/create.blade.php

```
@extends('layouts.backend')

@section('content')
  @include('includes.tinymce')
  <h1>Create post</h1>
  <form action="/en/admin/posts" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="form-group">
      <label>Title</label>
      <input type="text" name="title" class="form-control" value="{{old('title')}}">
    </div>
    <div class="form-group">
      <label>Body</label>
      <textarea name="body" class="form-control" rows="10">{{old('body')}}</textarea>
    </div>
    <div class="form-group">
      <label>Language</label>
      <select name="locale">
        <option value="en">English</option>
        <option value="fr">French</option>
      </select>
    </div>
    <div class="form-group">
      <label>Status</label>
      <select name="status" class="form-control">
        <option value="1">Published</option>
        <option value="0">Draft</option>
      </select>
    </div>
    <div class="form-group">
      <input type="submit" class="btn btn-primary" value="Create post">
    </div>
  </form>
  @include('includes.errors')
@endsection
```

Any help is appreciated. 

And another thing: How can I retrieve the local language into the links?

Lets say I have a link for creating a new page: 
`href="/admin/posts/create"`

How can I set like this?

`href="/en/admin/posts/create"`

or

`href="/fr/admin/posts/create"`

depends from the chosen language. Is there any variable I can use here?

**Comment by mydnic** [comment]
Hey,
What I personally do is use a language switcher in my admin panel as well, so lets say you're in french first:
-> /fr/admin/posts/create

You create your post, and as the app locale will be in French, the post will be saved in french.

Now that you have your post created you can visit
-> /fr/admin/posts/1/edit

And you'll be able to edit your post in french.

Now use the language switcher to in english and you'll be there:
-> /en/admin/posts/1/edit

There you'll see that the translated fields of your post will be empty (as the translation does not exists yet), and if you have non-translated attribute, the fields will be correctly filles (supposing you're using the Form helper or whatever).

Thus you can now enter the english translations into your edit form and when you hit save, as the application locale is set to EN, it will save the post in english :)

Hope it helps

**Comment by emco83** [comment]
Hi, 
Yes, I agree with that approach, but how do I save the post?

Right now from my code when I try to save the post, it display an error because its trying to save in the posts table, not post_translations. The posts table doesn't have the post fields, but only the id of the post.

So, how do I make the connection?
When I save a first post, 
the posts table will have id 1
the posts_translations will have id 1, post_id 1, locale en, title, slug and the body

When I save another post this time on French 
the posts table will have id 2
the posts_translations will have id 2, post_id 1, locale fr, title, slug and the body

That's the real problem and I don't know how to achieve with Laravel eloquent.

**Comment by mydnic** [comment]
That's because you create a new post each time
Just edit the first post in a different language, but you need to setup your edit() and update() methods in your controller and in your route etc.
Basically this whole translation architecture is made so you don't have to do anything

**Comment by emco83** [comment]
I wish I could know that in a code. :)
As I wrote before, right now I cannot save any content, because the method store is trying to store only in a posts table.

**Comment by mydnic** [comment]
uh there's something wrong with your implementation of the translation then, because the controller shouldn't do anything special
You don't even need the local in your create form

**Comment by emco83** [comment]
OK, thanks.
I hope I'll find the problem. That's why I've posted a main part of the code in case someone notice that I'm doing wrong.

**Comment by mydnic** [comment]
Can you try dumping the app locale in your controller just to be sure its there ?

Normally when you save the Post, you'll have one entry in your posts table and one entry in your post_translations table

**Comment by emco83** [comment]
I've added this line on top in PostsController
`use App;`

and inside the class the store method:

```
    public function store(Request $request)
    {
      $this->validate($request, [
        'title' => 'required',
        'body' => 'required',
      ]);
      $lang = App::getLocale();

      echo $lang;

      $input = $request->all();
      $user = Auth::user();

      $user->posts()->create($input);

      session()->flash('created_post', 'The post has been created');

      return redirect('/en/admin/posts');
    }
```

When I click save, I can see the locale. It shows 'en' and the error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'field list' (SQL: insert into `posts` (`locale`, `status`, `user_id`, `updated_at`, `created_at`) values (en, 1, 1, 2017-09-27 14:58:21, 2017-09-27 14:58:21))`

You see, it's trying to save the post inside the "posts" table, not "post_translations".

**Comment by gabrieldasilva** [comment]
Hello!

Actually theres a couple of ways to do that. It´s not mandatory to have localized URL on the admin panel. My implementation works without this and I use input field on every form that allow the user to select the locale from a drop down list.

So, the first time a post is created it will only contain one translation (default). Then at the edit view you can add as many translations as you need. I also have a array on a config file with control locales to avoid modifications on the locales array from translatable config.

I also use a PostController and PostTranslationController to manage both cases. The store method from PostController is uses to manage the creation of the psot with the initial translation. And the store method from PostTranslationController manage the creation of new translations on a post. If a translation for specific locale already exists on DB, the package is going to override the values of that record.

`
    
        $post->getNewTranslation($request['locale']);
        $post->translate($request['locale'])->title = $request['title'];
        $post->translate($request['locale'])->slug = $request['slug'];
        $post->translate($request['locale'])->description = $request['description'];
        $post->translate($request['locale'])->body = $request['body'];
        $post->save();`

Another approach could be to use a form block repeater. Every group of input belongs to a locale. I try these once and the code for the store method was a little bit confusing and large.

**Comment by mydnic** [comment]
@emco83 its normal that the post is inserted into the "posts" table. A second insert is made into the post_translation afterward.
Your error is simply because your $input variable contains a "locale" parameter so Eloquent is trying to insert that.
Just remove the "locale" input from your form :)

**Comment by emco83** [comment]
I don't get it. If I remove the $input that uses $request->all(); than how can I save the post?

Can you show me that in a code?

**Comment by mydnic** [comment]
sorry if I was not clear
You need to remove this from your view:
```
    <div class="form-group">
      <label>Language</label>
      <select name="locale">
        <option value="en">English</option>
        <option value="fr">French</option>
      </select>
    </div>
```

**Comment by emco83** [comment]
I've removed that part and now I'm getting this error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'field list' (SQL: insert into `posts` (`status`, `user_id`, `updated_at`, `created_at`) values (1, 1, 2017-09-27 17:13:05, 2017-09-27 17:13:05))`

The problem is not related with a view, it simply when I'm trying to store the values, it uses only the posts table. That's the problem and I don't know how to fix that.

**Comment by mydnic** [comment]
Let's take this step by step and lets see what kind of error you get.
I see in your Post model that the $translatedAttributes array does not include the "status" field.
So when saving the post, Eloquent and the Translatable package will try to add that to the "posts" table.

Is that column present in your database schema ? Is it a translated attribute ?

**Comment by emco83** [comment]
Yes, the "status" field is present in the database.

**Comment by mydnic** [comment]
@emco83 in which table ?

**Comment by emco83** [comment]
I've added the code for the migrations.

The "status" field is present in the post_translations table.

**Comment by mydnic** [comment]
You need to add status in the translatedAttribute array of the post model

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by emco83** [comment]
The problem is related with the "store" method. Since I have to save values in two tables, so input values has to be related with PostTranslation model.

In my other website I have news with photos. The photos are stored in a separate table and it's related by photo_id.

Here's that part of the code:

    ```
public function store(Request $request)
    {
      $this->validate($request, [
        'title' => 'required',
        'body' => 'required',
      ]);

      $input = $request->all();
      $user = Auth::user();

      if($file = $request->file('photo_id')) {

        $name = time() . '-' . $file->getClientOriginalName();

        $file->move('uploads/news', $name);

        $photo = NewsPhoto::create(['file' => $name]);

        $input['photo_id'] = $photo->id;
      }
      $user->news()->create($input);

      session()->flash('created_news', 'The news has been created');

      return redirect('/admin/news');
    }
```

NewsPhoto is a separate model and news_photos is the second table.
So, I have to figure out to achieve the same logic with the posts that uses translation.

**Comment by emco83** [comment]
The problem is SOLVED thanks to @mydnic 

In the "store" method I've changed the code with this:

      ```
$post = new Post();
      $post->title = $request->title;
      $post->content = $request->content;

      $post->save();
```

Now it's saving properly in the two tables without using complicated ->create() and relationships.
If the post is created on English language, when I change later to French, I can see the post that has to be translated on French and after that is saved properly. :)

Thank you!

**Comment by mydnic** [comment]
Happy to help ^^ Have fun !

**Comment by dimsav** [comment]
Thank you @mydnic

**Comment by amrdesign** [comment]
-     Run php artisan vendor:publish --tag=translatable
-     Open config/translatable.php where we determine what languages we are going to use. In this example we will only use English and Spanish. But you are free to use whichever and how many you want.
-     Modify locales array by adding your wanted languages codes.

// ...
'locales' => [
   'en',
   'es'
],
then you can use methode create(), it will save both translation
