### ISSUE TITLE
Need Help for null value 

### ISSUE THREAD

**Issue by shahabzebare** [dimsav/laravel-translatable#404]
I have user table 
the user translatable contain mname filed but may be the mname for some row null
there have problem for this filed in secound lang

**Comment by dimsav** [comment]
Please try to follow the instructions in the [docs](https://github.com/dimsav/laravel-translatable#docs). Also check the [tests code](https://github.com/dimsav/laravel-translatable/tree/master/tests) to see examples of using the package.
