### ISSUE TITLE
Use transaction?

### ISSUE THREAD

**Issue by bakumn** [dimsav/laravel-translatable#405]
Use transaction on insert and updade?

**Comment by dimsav** [comment]
@bakumn can you please clarify?

**Comment by Gummibeer** [comment]
I think that @bakumn recommends to use transactions for the save method to prevent an inconsistent database if one of all save queries fails.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
