### ISSUE TITLE
The translatable attributes printed out as blank

### ISSUE THREAD

**Issue by saidbakr** [dimsav/laravel-translatable#409]
I have the following model:

```
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Defect 
 */
class Defect extends Model
{
    use \Dimsav\Translatable\Translatable;
    
    public $translatedAttributes = ['title', 'description'];
 ...
```
while DefectTranslation model is:
```
namespace App;

use Illuminate\Database\Eloquent\Model;

class DefectTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = ['title','description'];
}
```
The problem: the defect_translations table is still empty and `$defect->title` returns blank. Of course the default string in the Defect is an English text.
In `app/config/app.php`:
```
'locale' => env('LOCALE','en'),
    'localeDir' => env('LOCALE_DIR','ltr'),

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale determines the locale to use when the current one
    | is not available. You may change the value to correspond to any of
    | the language folders that are provided through your application.
    |
    */

    'fallback_locale' => 'en',
```
Also `config/translatable.php` has the follwoing :

```
return [
    
    'locales' => [
        'en',
        'ar',        
        ],
    ],   
    'locale_separator' => '-',   
    'locale' => null,   
    'use_fallback' => true,   
    'use_property_fallback' => true,  
    'fallback_locale' => 'en',   
    'translation_suffix' => 'Translation',   
    'locale_key' => 'locale',    
    'to_array_always_loads_translations' => true,
];
```
I think there is a missing feature that allows to return the original attribute value if there is no translation record for it. The available feature right now, depends on being the default locale has records in the translation table.

Tabel defects structure:

```
CREATE TABLE `defects` (
  `id` int(6) NOT NULL,
  `code` char(3) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `defgroup_id` tinyint(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `defects`
--
ALTER TABLE `defects`
  ADD PRIMARY KEY (`id`),
  ADD KEY `index2` (`defgroup_id`);
```
Table defect_translations structure:
```
CREATE TABLE `defect_translations` (
  `id` int(7) UNSIGNED NOT NULL,
  `defect_id` int(6) NOT NULL,
  `title` varchar(350) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `locale` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `defect_translations`
--
ALTER TABLE `defect_translations`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `defect_id` (`defect_id`,`locale`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `defect_translations`
--
ALTER TABLE `defect_translations`
  MODIFY `id` int(7) UNSIGNED NOT NULL AUTO_INCREMENT;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `defect_translations`
--
ALTER TABLE `defect_translations`
  ADD CONSTRAINT `defect_translations_ibfk_1` FOREIGN KEY (`defect_id`) REFERENCES `defects` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
```

Laravel version: 5.4

**Comment by saidbakr** [comment]
I followed up the source code of the package and I suppose the following bug:
In `src/Translatable/Translatable.php` Line 190` it returns `null`. However, it should return `$this->getAttributeValue($attribute)`. The full, original, method code is:

```
/**
     * @param string $key
     *
     * @return mixed
     */
    public function getAttribute($key)
    {
        list($attribute, $locale) = $this->getAttributeAndLocale($key);

        if ($this->isTranslationAttribute($attribute)) {
            if ($this->getTranslation($locale) === null) {
                return null; //Issue is here.
            }

            // If the given $attribute has a mutator, we push it to $attributes and then call getAttributeValue
            // on it. This way, we can use Eloquent's checking for Mutation, type casting, and
            // Date fields.
            if ($this->hasGetMutator($attribute)) {
                $this->attributes[$attribute] = $this->getAttributeOrFallback($locale, $attribute);

                return $this->getAttributeValue($attribute);
            }

            return $this->getAttributeOrFallback($locale, $attribute);
        }

        return parent::getAttribute($key);
    }
```
**It should be like**
```
public function getAttribute($key)
    {
        list($attribute, $locale) = $this->getAttributeAndLocale($key);

        if ($this->isTranslationAttribute($attribute)) {
            if ($this->getTranslation($locale) === null) {
                return $this->getAttributeValue($attribute);
            }

            // If the given $attribute has a mutator, we push it to $attributes and then call getAttributeValue
            // on it. This way, we can use Eloquent's checking for Mutation, type casting, and
            // Date fields.
            if ($this->hasGetMutator($attribute)) {
                $this->attributes[$attribute] = $this->getAttributeOrFallback($locale, $attribute);

                return $this->getAttributeValue($attribute);
            }

            return $this->getAttributeOrFallback($locale, $attribute);
        }

        return parent::getAttribute($key);
    }
```
The above  modification of `getAttribute()` method solves the issue. While my current transtable configurations are still the same as described previously.

**Comment by drbyte** [comment]
Quick tip when posting suggested code changes on github: you can specify a language when posting your code, and if you use `diff` as the language, it'll display your changes inline ... which makes it more readable for people reviewing the suggestions.
ie: instead of just using 3 ``` marks, follow those marks with the language, either 'php' or `diff` for example. Here's your suggestion above, as a diff:

```diff
/**
     * @param string $key
     *
     * @return mixed
     */
    public function getAttribute($key)
    {
        list($attribute, $locale) = $this->getAttributeAndLocale($key);

        if ($this->isTranslationAttribute($attribute)) {
            if ($this->getTranslation($locale) === null) {
-                return null; // ISSUE IS HERE 
+                return $this->getAttributeValue($attribute); // SUPPOSED SOLUTION
            }

            // If the given $attribute has a mutator, we push it to $attributes and then call getAttributeValue
            // on it. This way, we can use Eloquent's checking for Mutation, type casting, and
            // Date fields.
            if ($this->hasGetMutator($attribute)) {
                $this->attributes[$attribute] = $this->getAttributeOrFallback($locale, $attribute);

                return $this->getAttributeValue($attribute);
            }

            return $this->getAttributeOrFallback($locale, $attribute);
        }

        return parent::getAttribute($key);
    }
```

**Comment by saidbakr** [comment]
@drbyte Thank you very much for the tip. However, I could only able to turn it to ` ```php ` but I could not able to figure out how to get `- +` diff as you regarded.

**Comment by drbyte** [comment]
(You have to add the - and + symbols yourself. And then github shows them in the corresponding colors.)

**Comment by dimsav** [comment]
@saidbakr thank you for your feedback. There is a reason why this returns null if the record is found in the translations table: The reason is we define the fallback using a locale in the configuration. 

How should the code know what locale is being used in the main (`Defect`) table?
What should happen if we suddenly want an different fallback locale we configure on the fly? (ie. the company expands)

On the other side, maybe I'm thinking in favor of edge cases instead of trying to simplify and help the developers using this package, so I'm open to change it.

**Comment by dimsav** [comment]
@drbyte thank you for the useful tips! My greetings sir :-)

**Comment by saidbakr** [comment]
@dimsav  I think that the main is always the values found in the original table, in my case *defects* table. I think that it more reliable and more easier to be understood "If there is no , *not empty attribute value*, foreign key of the main record in its translation table, so it should return the main value from the original table".

**Comment by tomasvanrijsse** [comment]
@saidbakr I think I see where you are doing things different from the 'laravel-translable'-way.
The packages assumes that translatable fields are only stored in the `defect_translations` table. So in your case you should migrate the `title` field from `defects` to the `defects_translations` table.
Two additional migrations would solve your issue

1. Copy the values for translated columns
`\DB::insert("INSERT INTO defect_translations (defect_id,title,description,locale) SELECT id,title,description,'en' FROM defects");`
2. Remove the original column from `defects`
