### ISSUE TITLE
nothing showed until I select language

### ISSUE THREAD

**Issue by summermick** [dimsav/laravel-translatable#416]
my middleware:
```php
public function handle($request, Closure $next)
    {
        App::setLocale(session('locale'));
        config(['translatable'=>session('locale')]);
        return $next($request);
    }
```
I found default locale not working before I select a language.

**Comment by Gummibeer** [comment]
First: to format multiline code in markdown/github pls use the gravis three times - also with possible language after this like
```
```php
```

```php
public function handle($request, Closure $next) {
    App::setLocale(session('locale'));
    config(['translatable'=>session('locale')]);

    return $next($request);
}
```

Where do you specify your default locale? And what do you get from a `dump(App::getLocale())` - is it your default locale or anything else?

**Comment by Gummibeer** [comment]
closed due to inactivity
