### ISSUE TITLE
json data in translatable table causes mysql error

### ISSUE THREAD

**Issue by rain-maker** [dimsav/laravel-translatable#418]
Hello, there seems to be trouble with json field if it's  created in translatable table 

//migration data
class CreateTestBottles extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bottles', function(Blueprint $table)
        {
            $table->increments('id');
            $table->string('code');
            $table->timestamps();
        });
        
        Schema::create('bottle_translations', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('bottle_id')->unsigned();
            $table->string('name')->nullable();
            $table->json('content')->nullable();
            $table->string('locale')->index();
        
            $table->unique(['bottle_id','locale']);
            $table->foreign('bottle_id')->references('id')->on('bottles')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bottles');
        Schema::dropIfExists('bottle_translations');
    }
}

models
class Bottle extends Model
{
    //
    use \Dimsav\Translatable\Translatable;
    
        public $translatedAttributes = ['name','content'];
        protected $fillable = [
            'code'
        ];
    
}

class BottleTranslation extends Model
{
    //

    public $timestamps = false;
    protected $fillable = ['name','content'];
}

// if trying to create data
$insert_data = [
                        "code"=>"test",
                        "ru"=>["name"=>"Обо мне"],
                    ];
$bottle = Bottle::create($insert_data);
     

![image](https://user-images.githubusercontent.com/405800/33189285-4d269454-d0b2-11e7-8dd3-85de88ce6165.png)

**Comment by Gummibeer** [comment]
Your Exception doesn't have anything to do with he json field or anything else. Try to find a `bottle_translations` by `bottle_id` with a value of `null and not null`. ;) It's the same like `if(true === false)` - it simply can't work. And in addition to this a stack trace would help to know where it tries to find the translation without an available id.

Something that is missing is also the `$cast` property to cast the value of `content` to JSON.
https://laravel.com/docs/5.5/eloquent-mutators#array-and-json-casting

**Comment by rain-maker** [comment]
Thanks, but why then if i remove this field from table or change it to  **text** type  everything work's fine  and this error won't show up?
