### ISSUE TITLE
When the locale changes, it will again show the translation of the default location in config (translatable.php).

### ISSUE THREAD

**Issue by nekooee** [dimsav/laravel-translatable#419]
Hi
When the locale changes, it will again show the translation of the default location in config (translatable.php).
sample when in **translatable.php** I set :
'locale' => 'en',
and in view:
App::setLocale('fr');
echo $attribute->name;
echo name in 'en'.
Only the following code can get the correct translation:
$attribute->translate('fr')->name

What is the reason?

**Comment by nekooee** [comment]
any one can help me?

**Comment by Gummibeer** [comment]
If you override this config you have to change it everytime. Otherwise it won't access the laravel locale. If you keep this config value `null` it will access the laravel value also for default - so just set the laravel default locale in `config/app.php` and everything should be fine.

**Comment by nekooee** [comment]
@Gummibeer  Thankyou. 
Yes, I should have set `null` for locale in translatable.php.  (`'locale' => ''`) #

**Comment by Gummibeer** [comment]
@dimsav this should be solved.

**Comment by akizor** [comment]
I would suggest updating the Readme with this kind of setting. I was struggling a bit until I reached this issue. Setting `locale` setting to a value in `translatable.php` will force Eloquent models to bind to that translation regardless of `App::getLocale` when using `whereTranslation` query to find model by translated attribute (eq: slug attribute).

**Comment by Gummibeer** [comment]
@akizor PR is open, is this enough? I think it's better in the config itself cause the [configuration](https://github.com/dimsav/laravel-translatable#configuration) part of the readme is very short and doesn't explain any options.

**Comment by akizor** [comment]
@Gummibeer You are right, it's better on the configuration. Most devs will rather look into config file directly if the docs doesn't satisfy. Thank you.

**Comment by Gummibeer** [comment]
#470 is merged into master
