### ISSUE TITLE
How to extend Laravel-Translatable to translate pivot values

### ISSUE THREAD

**Issue by tomasvanrijsse** [dimsav/laravel-translatable#420]
I've read issue #303 and was thinking about an approach to tackle pivot values.
We have implemented the Entity-Attribute-Value database design for products and their properties.
Our simplified schema looks like this

**Products** *Entity*

| ID | name |
| --- | --- |
| 1 | Fancy Bike |
| 2 | Fancier Bike |

**Properties** *Attribute*

| ID | name |
| --- | --- |
| 77 | Wheel size |
| 78 | Color |

**Product Properties** *Value*

| ID | product_id | property_id | value |
| --- | --- | --- | --- |
| 101 | 1 | 77 | 23 inch |
| 102 | 1 | 78 | red |
| 103 | 2 | 77 | 23 inch |
| 104 | 2 | 78 | silver |

Using the pivot table as a many-to-many relation gives us a syntax like 

```
Class Product {
  function properties(){
    $this->belongsToMany(Property::class)->withPivot('value');
  }
}

//somewhere else
foreach($product->properties as $property) {
  echo $property->value;
  // echoes red, silver etc.
}
```

To us the syntax in that foreach-loop makes sense.  Using a separate model for the pivot table however would force awkward syntax like `$product->value->property`. Therefore we would like to keep the pivot functionality as it is.

Ideally the pivot table would look like this

**Product Properties** *Value*

| ID | product_id | property_id | value | locale |
| --- | --- | --- | --- | --- |
| 101 | 1 | 77 | 23 inch | en |
| 102 | 1 | 78 | red | en |
| 103 | 1 | 77 | 58,4 cm | nl |
| 104 | 1 | 78 | rood | nl |

Do you concur that this schema would be a good solution?
How should laravel-translatable be extended to make this scenario work?

**Comment by AshrafHefny** [comment]
@tomasvanrijsse , @Gummibeer  you can use  `using()` over the `belongsToMany()`  relation
Assuming your models as the following:
```
Class Product {
  function properties(){
    $this->belongsToMany(Property::class)->withPivot([
                                             'prodict_id',
                                             'property_id'
                                             ])
                                          ->using(ProductProperties::class);
  }
}

Class Property {
}

Class ProductProperties {
    use Translatable;
    $fillable = ['prodict_id','property_id'];
    $translatedAttributes = ['value']
}

Class ProductPropertyTranslation {
    $fillable = ['value'];
}
```
So then you can normlly call the `translated value column` as the following:
```
app()->setLocale('en');
$product = Product::with('properties')->find($id);
foreach ($product->properties as $property){
    echo $property->value;
}
