### ISSUE TITLE
Choose to include or no translated fields to model in dimsav/laravel-translatable and fractal

### ISSUE THREAD

**Issue by ahmadbadpey** [dimsav/laravel-translatable#423]
I'm using [dimsav/laravel-translatable][1] laravel package to make an api (written in [dingo/laravel][2] and [spatie/laravel-fractal][3]) translatable.

Suppose to save a translatable model I used this : 

    $warehouse = Warehouse::create([
        'type' => 'technical',
        'city' => 'manchster',
        'en'   => ['name' => 'warehouse 1','desc'=>'this is Description'],
        'fa'   => ['name' => 'انبار 1','desc'=>'توضیحات انبار']
    ]);

As you can see I sent translated fields as `en` and `fa` arrays.

Now all things that I want to do is when fetching a model , it returned as same format automatically. 

I readed [this Issue][4] that is similar to my Question that suggested to use `$warehouse->getTranslationsArray();` method to return translated fields. but this can return **only** translated fields while I want response format was like this (included other fields that do not be translate): 
    
    [
        'type' => 'technical',
        'city' => 'manchster',
        'en'   => ['name' => 'warehouse 1','desc'=>'this is Description'],
        'fa'   => ['name' => 'انبار 1','desc'=>'توضیحات انبار']
    ]

Of course we know that it converts to a json formatted text like this : 

        {
            'type' : 'technical',
            'city' : 'manchster',
            'en'   : {'name' : 'warehouse 1','desc':'this is Description'},
            'fa'   : ['name' : 'انبار 1','desc':'توضیحات انبار'}
        }

Another problem is that beacause I used **fractal** transformers to return **warehouse** models I want to be able to choose that to return translated fields or no. 

`WarehouseTransformer` is like this : 

    class WarehouseTransformer extends TransformerAbstract
    {
       
        protected $availableIncludes = [
            'translations'
        ];
    
        
        public function transform(Warehouse $warehouse)
        {
            $transforms = [
                'warehouse_id'          => $warehouse->warehouse_id,
                'type'                 => $warehouse->type,
                'city'           => $warehouse->city,
            ];
    
           
            return $transforms;
        }
    
        
        public function includeTranslations(Warehouse $warehouse)
        {
            $translations = $warehouse->translations;
    
            /***
            I WANT ATTACH ARRAY OF TRANSLATIONS RELATION TO CURRENT MODEL HERE.
            ****/
        }
    }

After that any time I request for example `/warehouse/1` it return :

    [
      'type' => 'technical',
      'city' => 'Manchester',
      'name' => 'warehouse 1', //BASED ON CURRENT LOCALE
      'desc' => 'this is Description' //BASED ON CURRENT LOCALE
    ]

And if I request `/warehouse/1?include=translations` it return : 
    
        [
            'type' => 'technical',
            'city' => 'manchster',
            'en'   => ['name' => 'warehouse 1','desc'=>'this is Description'],
            'fa'   => ['name' => 'انبار 1','desc'=>'توضیحات انبار']
        ]

But from now on, I do not know what to do? 

  [1]: https://github.com/dimsav/laravel-translatable
  [2]: https://github.com/dingo/api
  [3]: https://github.com/spatie/laravel-fractal
  [4]: https://github.com/dimsav/laravel-translatable/issues/273

**Comment by makz** [comment]
Also interested in that issue! Is someone has solution?

**Comment by DevMakoto** [comment]
my posible solution

```
 public function getNameAttribute()
    {
        $array = [];

        $translations = $this->getTranslationsArray();

        foreach ($translations as $key => $translation) {
            foreach ($translation as $key_trans => $value_trans) {
                $array[$key_trans][] = [
                    $key => $value_trans,
                ];
            }
        }

        return $array['name'];
    }
```

**Comment by Gummibeer** [comment]
@ahmadbadpey sorry but I don't get your problem.
Do you want to remove the `name` & `desc` attribute if you do not request `translations` relation? Or do you want to have the same structure everytime - so if I don't request `translations` I just get the current locale but as `'en' => ['name' => 'warehouse 1','desc'=>'this is Description']`?

The array structure you want is, like you found available via `getTranslationsArray()`.

**Comment by DevMakoto** [comment]
my desirable array

```
"data": [
    {
      "type": "release",
      "id": "1",
      "attributes": {
        "slug": "1-tempora-consectetur",
        "title": "Tempora consectetur.",
        "title_original": "津田 七夏",
        "date": "1985-05-10",
        "image": "https://lorempixel.com/640/480/?66898",
        "description": {
          "en": "Ing. Eduardo Armendáriz Segundo",
          "es": "Mr. Kennedi Nikolaus PhD",
          "jp": "渚 くみ子"
        }
      },
      "relationships": {
        "release_type": {
          "data": {
            "type": "release_type",
            "id": "7"
          }
        }
      }
    }
  ],
```

use 
```

public function getNameAttribute()
    {
        $array = [];

        $translations = $this->getTranslationsArray();

        foreach ($translations as $key => $translation) {
            foreach ($translation as $key_trans => $value_trans) {
                if ($key_trans == 'name') {
                    $array[$key] = $value_trans;
                }

            }
        }

        return $array;
    }
```

solved my problem, i use laravel/dingo and laravel/scout
