### ISSUE TITLE
when creating a new translation it doesn't automatically reference model_id

### ISSUE THREAD

**Issue by verybigelephants** [dimsav/laravel-translatable#425]
hi, i don't know what i am doing wrong or there's a bug in the library

my model's only translatable attribute is "title"

```
$instance=Benefit::find($instance_id); //i get a normal instance, all is fine

$translation=$instance->translateOrNew('newlanguage');
$translation->title='testing';
$translation->save();
```

when i do this i get
```
 SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "benefit_id" violates not-null constraint
  DETAIL:  Failing row contains (349, null, designed for testing, it).
```
should not this get assigned by default? or do i have to retype the $instance_id by force? documentation doesn't mention anything like this

using php 7.1 and postgres 9.4

**Comment by dimsav** [comment]
Please have a thorough look at the [documentation](https://github.com/dimsav/laravel-translatable/blob/master/readme.md).

**Comment by Gummibeer** [comment]
closed due to inactivity
