### ISSUE TITLE
Loading available locales from DB

### ISSUE THREAD

**Issue by safir187** [dimsav/laravel-translatable#427]
Hi, I'm quite new to this package. Is there a tidy way of loading locales from a table, instead of hard coding them into the config file?

**Comment by graveeel** [comment]
Basically there no difference. I mean if you have to add new locales you have to add them either way or?

**Comment by Gummibeer** [comment]
But if you have a database translation tool and your customer/user employees a new translator they don't want to wait until you have added the new locale to the config file. So it could make sense to have them in database.

Related to the question:
The easiest solution I could imagine would be a service provider/middleware that overrides the config value `config('translatable. locales', $dbLocales)`.

**Comment by safir187** [comment]
@graveeel if you have to add it you have to add it somewhere. but if it's in the database you can build a nice interface in the admin panel to add new languages instead of changing the code.

**Comment by safir187** [comment]
@Gummibeer and i have to delete the locales from the config so it falls back to `$dbLocales`, right?

**Comment by Gummibeer** [comment]
@safir187 no, you can keep default ones - your Service-Provider/Middleware will override these locales in runtime.

1) load config - with Default ones
2) override config with Database values
3) use the package Translation methods

Another Idea would be to cache the Database result in a Special File or normal laravel cache to increase performance and Update the Cache in Change from your Admin-Panel.

But how far I see it in the package Code the config values aren't cached/copied. So ist will Access the current config values everythime needed. And laravel config values can be changed in runtime.
