### ISSUE TITLE
All translations of the same post are rendered.

### ISSUE THREAD

**Issue by OGhawsi** [dimsav/laravel-translatable#428]
I have returned all the posts from the table which work fine but the problem is it displays empty rows in view
her is my controller:
`
  public function index()
    {
        $posts = Post::latest()->get();
        return view('admin.posts.index',compact('posts'));
    }

`

**And here is the result which:**
![image](https://user-images.githubusercontent.com/30488194/35096379-98e12afc-fc69-11e7-8067-704954f22c1f.png)

![image](https://user-images.githubusercontent.com/30488194/35096472-f56dcee2-fc69-11e7-8a0f-3542f3399430.png)

**I don't want to show empty rows which are actually posts related to other translation**

**Comment by gabrieldasilva** [comment]
Hi @OGhawsi 

You can do something like this:

`$posts = Post::translatedIn('my-locale')->latest()->get()`

With this you can stablish an scope that select only the posts translated on a specific locale. Then you run agreggations around this filter. 

I, usually use `app()->getLocale()` to reference the actual locale on the reques lifecycle.

Also, remember to eager load the translation relationship. Every time you use a magic property, if the translation is not loaded, the package executes a query. So you end up with the n+1 problem. You can try this by calling any translated magic property inside of foreach statement and then printing the DB Query log with:

`DB::enableQueryLog();` And `DB::getQueryLog()`

**Comment by OGhawsi** [comment]
Solved with same technique...
Thanks
