### ISSUE TITLE
Which relationship to use with translations?

### ISSUE THREAD

**Issue by OGhawsi** [dimsav/laravel-translatable#429]
I have two models **Tag** and **Post** each has a translation of their own like **PostTransaltion** and **TagTransaltion**. 

Tag and Post have many to many relationship in general.

Now as I am using translations how should I make the relationship.

Thanks in Advance.

**Comment by dimsav** [comment]
From my perspective, the relationship between tag and post shouldn't change just because you added translations to those models.

**Comment by Gummibeer** [comment]
closed due to inactivity
