### ISSUE TITLE
getting timestamps as Carbon

### ISSUE THREAD

**Issue by safir187** [dimsav/laravel-translatable#430]
seems like when you access translation timestamps they are fetched as String. it would be nice to have them as Carbon so we can use Carbon features without having to cast strings to carbon.

**Comment by dimsav** [comment]
It's up to you to define the structure of your translations table :-)

**Comment by safir187** [comment]
i'm not sure you got what the problem is. when you access a timestamp column directly on a model it returns a  carbon instance. but when i set updated_at for example as translatable and try to get it through magic properties, it returns a string.

**Comment by dimsav** [comment]
If you feel there is an improvement we could made to the code, please open a PR.
