### ISSUE TITLE
Best way to select only specific attributes

### ISSUE THREAD

**Issue by vyobukhov** [dimsav/laravel-translatable#431]
For example, I have Country model with attributes:
- id
- name (varchar 255)
- short_description (varchar 255)
- description (large text 5000+ symbols)
- additional_description (one more very large text)

I don't want to load and return to user large texts from description and additional description when user only browses a list of countries. So what is the best way to show only id, name and short_description in collection (array) but still load all the fields for a single resource?

I expected something like:
```PHP 
Country::withTranslation()->get(["id", "name", "short_description"]);
```
or
```PHP 
Country::listsTranslations("name", "short_description"); 
```

**Comment by rain-maker** [comment]
https://github.com/dimsav/laravel-translatable/issues/236 here is the fix in the end, developer is not working on any easier solution, as it seems.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
