### ISSUE TITLE
Fallback locales

### ISSUE THREAD

**Issue by mokhosh** [dimsav/laravel-translatable#433]
I'm fetching all posts for the administrator to see them. But only the ones that are in admin's locale are being shown.
If I want the admin to be able to see some translation where his own locale is not available, the only option now is fallback_locale, but what if it's not available in the fallback_locale either?
can we make this an array? so if the first fallback is not available it falls back to the next? or even set it to "all" so it uses the same array as "locales"?

say we have a multi language news site where every post must be translated to all locales. we should have a way of giving a list of posts with "some" translation to the editor, so they can translate them to their language.

**Comment by dimsav** [comment]
Have you tried using just eloquent for that? For example:

```php
$news = News::with('translations')->get();
foreach ($news as $article) {
    dd($article->translations->toarray());
}
```

**Comment by safir187** [comment]
Yes It's just that there's nothing magic about looping and checking conditions to get a fallback translation.
Thanks anyway.

**Comment by drbyte** [comment]
@safir187  if you could wish the code to look any way you wanted, to accomplish what you wrote about above, what would it look like?

**Comment by safir187** [comment]
@drbyte it would be the same api as we use now: `$post->title`. the only difference is, now we first look for a translation is app's locale, if it's not available we check the config, if use_fallback is true, we look for a translation in the fallback locale which is a single string, and we stop there. if there's no translation in these two locales nothing is returned. i suggest we make it an array or a wildcard to use the locales array. then we cascade further down, or all the way down the array to look for translations.

**Comment by Gummibeer** [comment]
@mokhosh I would like to don't bring it in breaking changes. But in general this should be solvable with 3-5lines.

1) make fallback everytime an array `array_wrap`
2) foreach the fallback
3) first found translation is returned

step 1 is important to allow `fallback = 'de'` and `fallback = ['de', 'en']`.

**Comment by Gummibeer** [comment]
I already had this idea and yes, this should performe better! 🚀
My idea would be something like this:

```
foreach locales as locale
  if translations.has(locale)
    return translations.get(locale)

throw new UntranslatedException
```

@mokhosh What do you think!?

**Comment by mokhosh** [comment]
Sounds about right. Thank you.
About the exception, just for the sake of consistency, what's the current behaviour? dosn't it just return empty string or null?

**Comment by Gummibeer** [comment]
Could be - I think `null` is current. The exception was just for pseudo-code.

What I've seen is that fallback is used in two cases and under different circumstances.
1) translation as model - fallback is used if primary translation doesn't exist.
2) translation attribute - fallback is used if primary attribute is empty (translation could exist but translation is empty

The second one can produce several errors. Translation of numerics, booleans or just that translation is empty cause it's empty.

So if we rework the fallback behavior should we fix this?

**Comment by mokhosh** [comment]
Yeah sounds more consistent and intuitive. One might intentionally want to leave the translation blank for some languages.

Then again, in multi-admin situations and problems with messy people, we might want to give them the option in all possible cases. Can we make this a boolean argument in both cases?

**Comment by Gummibeer** [comment]
You mean a config switch that decides if to return anything of the existing translation or check the attribute value to be not empty!?
This would prevent this change from BC but will introduce some more complexity. 🤔

**Comment by mokhosh** [comment]
No, I meant a boolean argument passed to the method that will return the values. It will fallback on null by default and return empty strings if available in the db, but you can pass an argument to tell the method to fallback on empty strings too.

I imagine this could give reasonably expected freedom, and easier transition to new version for those who are relying on the current behaviour.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
