### ISSUE TITLE
Can i use this package for RestFul APIs?

### ISSUE THREAD

**Issue by mimrank** [dimsav/laravel-translatable#434]
Hi, how it will return JSON data in single object with translated key inside of a child array of translations.
I am trying, but its not work

`// models/Country.php
namespace App\Models;

use Dimsav\Translatable\Translatable;
class Country extends Eloquent {
    
    use Translatable;
    
    public $translatedAttributes = ['name'];
    protected $fillable = ['code'];
    
    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    // (optionaly)
    // protected $with = ['translations'];

}

// models/CountryTranslation.php
namespace App\Models;

class CountryTranslation extends Eloquent {

    public $timestamps = false;
    protected $fillable = ['name'];

}`

`In Conroller
$countries = Country::translatedIn('fr')->get();
return response()->json($countries);
`
Its return data in 

`
{
  "code": "uk",
  "name": "England",
  "translations": [
    {
      "name": "England",
      "locale": "en"
    },
    {
      "name": "Angleterre",
      "locale": "fr"
    }
  ]
}
`
But i require it in this form
`
{
  "code": "fr",
  "name": "Angleterre"
}
`

**Comment by Gummibeer** [comment]
What do you want to achive? Which array-structure should your response look like?
Your example looks right - if you want to hide the `translations` sub-array you can hide it. Since L5.3 it's possible to hide keys on the fly: https://laravel.com/docs/5.3/eloquent-serialization#hiding-attributes-from-json

**Comment by mimrank** [comment]
is there any other way to do this?

**Comment by mimrank** [comment]
I hide the `translations` but its only show default fallback language of en.

**Comment by Gummibeer** [comment]
> // Returns all countries having translations in english
> Country::translatedIn('en')->get();
https://github.com/dimsav/laravel-translatable#available-scopes

This scope doesn't translate your models, it just filters to the countries that have a translation for `fr`. To translate the attributes you have to set any value that's used by `Translatable::locale()`
https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L731-L739
If you want to keep it basic laravel style just do `app()->setLocale('fr')` in a middleware or serviceprovider or anywhere else before the controller.

**Comment by mimrank** [comment]
@Gummibeer I set the locale in middleware but still receive the same result.

**Comment by rommelandrea** [comment]
Same problem. Any solution?

**Comment by Gummibeer** [comment]
@mimrank have you tried `getTranslationsArray`?
