### ISSUE TITLE
Nothing to publish for tag [translatable].

### ISSUE THREAD

**Issue by bouldrini** [dimsav/laravel-translatable#437]
I installed version 5.0 using composer.

Im am not able to copy the configuration file using
php artisan vendor:publish --tag=translatable

Nothing to publish for tag [translatable].

What to do to get the config file ?

**Comment by dimsav** [comment]
Please use the latest version. 

If for some reason you need to use an old version, this is the docs of version 5.6: https://github.com/dimsav/laravel-translatable/blob/4534a17da5494ac27cf5ce743e228533c66b7275/readme.md

**Comment by bouldrini** [comment]
thank you very much. I appreciate the support.
