### ISSUE TITLE
Translations not being retrieved by default

### ISSUE THREAD

**Issue by alvarezskinner** [dimsav/laravel-translatable#438]
Hi all,

First of all thanks so much for this package to all contributors, amazing the tons of work it saves and how good it works! Thanks!

Sorry if this is not the right place to ask/report this, this is my first time reporting something, I assume its a by design scenario, but still want it to raise it.

I have the following models:

- Cuisine
- CuisineTranslation

I have added the trait to the Cuisine Model and the translatedAttributes property as well to indicate the column that is being translated.

The whole translation bit is working fine, tables are getting the values they must when creating the objects the thing is the following:

I create a new object by doing:

`$dish = new Dish()`

If I dump out the $dish object I see the object definition but not the translations, unless I retrieve the column by doing `$dish->name` or I do a `toArray()` on it, translations will not be retrieved, which I assume it is because of the setting `to_array_always_loads_translations` in the config file set to true.

So my question or what I want to report, to understand it is intended or not, is if there is any way to force the translations to be retrieved when getting the translatable model?

Once again, sorry if this is not the right channel, if it's not please let me know I will delete this.

Regards and thanks once again!

**Comment by gabrieldasilva** [comment]
Hi! @alvarezskinner I´ve been working with this package for almost a year and the only way is to eager load the translations relationship. You could use the with() method from query builder or you can also use the ->load() method once you retrieve the model object

You also can add 

`protected $with = ['translations'];`

In your model to eager load this relation on every query.

**Comment by alvarezskinner** [comment]
Thanks @gabrieldasilva appreciate the help, didn't think about piping the `with()` method, that will work!
