### ISSUE TITLE
How to save one to many  relationship 

### ISSUE THREAD

**Issue by prashant19914** [dimsav/laravel-translatable#439]
I'm trying to save multiple records in a one to many relationship. I have two models as following.

```php
class Product extends Model
{
    protected $primaryKey = 'product_id';
    public $timestamps = FALSE;

    public function Size(){
        return $this->hasMany('App\Size');
    }
}
```

**Comment by prashant19914** [comment]
class Size extends Model
{
    public $timestamps = FALSE;
    protected $fillable = ['product_id','size'];

    public function Product(){
        return $this->belongsTo('App\Product');
    }
}

**Comment by dimsav** [comment]
Please read the [laravel docs](https://laravel.com/docs/5.6/eloquent-relationships)
