### ISSUE TITLE
Magic properties not working

### ISSUE THREAD

**Issue by skarampatakis** [dimsav/laravel-translatable#447]
Hi, 
Thank you for your very useful module for Laravel. I have been used it in all my recent projects. 

So far I could succesfully acces the translated properties of my models by utilizing the magic properties. 

But on my latest project I just can't. The only way to make it work is to force the the translate() method. 

So this works
```php
$model->relatedModelwithTranslation->translate('en")->name
```
while this won't
```php
$model->relatedModelwithTranslation->name
```

My application locale seems to be set correctly. Any hint on this?

**Comment by dimsav** [comment]
Can you please help by debugging this? 

Also you don’t mention what is the difference between this project and the other ones.

**Comment by skarampatakis** [comment]
Hi @dimsav,
It seems that it was a configuration problem as I misunderstood the "locale" configuration property usage. 

I compared the translatable configuration files across my projects and then I saw that I had forced ```"locale" = "el"```. I changed to null and everything now works as expected. 

Thank you for your interest and for your package!
