### ISSUE TITLE
Using Fill to insert new translations

### ISSUE THREAD

**Issue by rafailml** [dimsav/laravel-translatable#449]
Hi guys,
I'm wondering can I use Fill method like that (from documentation):
```
$country->fill([
    'en'  => ['name' => 'Greece'],
    'fr'  => ['name' => 'Grèce'],
]);
```
The problem is that nothing happens. Nothing is updated and if I have new translation it's not inserted in database.

Now I'm doing something like that to work:
```
                foreach ($request->input('translations') as $code => $translation){
                    $country->translateOrNew($code);
                    $country->translate($code)->name = $translation['name'];
                    $country->save();
                }
```

Is there a way to do that shorter with fill method?

**Comment by bloggervista** [comment]
have u updated mass assignable fields ?

Its $protected = [] in Model :)

**Comment by Gummibeer** [comment]
no response from author since 03.04.2018
@dimsav this issue could be **closed**.

**Comment by Gummibeer** [comment]
closed due to inactivity
