### ISSUE TITLE
SVG Flag images  Downloaded instead of served !!

### ISSUE THREAD

**Issue by houcinecherif** [dimsav/laravel-translatable#450]
Hi
I have somme issues when deployng the application on the server, the svg flags werer downloaded instead of served as images ! the content-type retoured is "image/svg" instead of "image/svg+xml" , should i edit the controller function : 
 /**
     * File flag action.
     *
     * @param $cca3
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function file($cca3)
    {
        return response()->file($this->getFlagPath($cca3));
    }
Thanks

**Comment by dimsav** [comment]
Hi, are you sure your issue is in the right repo?

**Comment by bloggervista** [comment]
Wrong Number Haha
