### ISSUE TITLE
Please make sure you have run "php artisan config:publish dimsav/laravel-translatable" and that the locales configuration is defined.

### ISSUE THREAD

**Issue by summermick** [dimsav/laravel-translatable#451]
`Please make sure you have run "php artisan config:publish dimsav/laravel-translatable" and that the locales configuration is defined.`

I'm using laravel 5.5 with Translatable 8.* and the compiler keeps telling me that.

so the problem wouldn't occur until I switch languages.

**Comment by summermick** [comment]
so I tried to debug this and found that it happens when there is no translation
i.e.  table country has an entry id=1 but table country_translations has no translation for country_id=1.

**Comment by Gummibeer** [comment]
This can't be cause the exception is thrown before the used locales from database are loaded https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L394

**Comment by Gummibeer** [comment]
no response since 22days
@dimsav this issue could be **closed**.

**Comment by summermick** [comment]
the issue caused by the fallback is not working

**Comment by Gummibeer** [comment]
The mentioned exception is thrown here:
https://github.com/dimsav/laravel-translatable/blob/1ab239b6ccc008b82f7c3ee394d6e63f31e38fbc/src/Translatable/Translatable.php#L390-L397

The only case that this exception is thrown is when the `locales` config array is empty. So if you don't published config or haven't put in any locales.
This method is independent of any existing or not existing database entries. If you have done all these things but still get this exception it would help to get more information:
* config
* executed code
* model setup
and so on.
