### ISSUE TITLE
[question] Relations for translation table

### ISSUE THREAD

**Issue by Iworb** [dimsav/laravel-translatable#452]
I have an project where `users` could post `articles` on different languages. Also, user could translate `article` of another user.
Example: user **A** post news in English and users **B** and **C** translate them to German.
So I have tables like this for articles:
```php
Schema::create('articles', function (Blueprint $table) {
    $table->bigIncrements('id');
});
```
And this for translations:
```php
Schema::create('article_translations', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->bigInteger('article_id')->unsigned();
    $table->integer('user_id')->unsigned();
    $table->string('slug')->unique();
    $table->text('title');
    $table->text('description');
    $table->text('body');
    $table->string('locale')->index();
    $table->timestamps();
    $table->softDeletes();
    $table->unique(['article_id','locale']);
    $table->foreign('article_id')->references('id')->on('articles')->onDelete('cascade');
    $table->foreign('user_id')->references('id')->on('users')->onDelete('restrict');
});
DB::statement('ALTER TABLE article_translations ADD FULLTEXT full(title, description, body)');
```
My models looks like this:
```php
// app\Article.php
<?php

namespace App;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class Article extends Model {

	use Translatable;

	public $timestamps = false;

	public $translatedAttributes = [
		'user_id',
		'title',
		'slug',
		'description',
		'body',
		'created_at',
		'updated_at',
		'deleted_at'
	];

	protected $fillable = ['user_id', 'title', 'slug', 'description', 'body'];
}
```
```php
// app\ArticleTranslation.php
<?php

namespace App;

use App\User;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class ArticleTranslation extends Model {

	use Sluggable;
	use FullTextSearch;

	protected $fillable = ['title', 'slug', 'description', 'body'];
	protected $searchable = ['title', 'description', 'body'];

	/**
	 * Return the sluggable configuration array for this model.
	 *
	 * @return array
	 */
	public function sluggable() {
		return [
			'slug' => [
				'source'    => 'title',
				'maxLength' => 255
			]
		];
	}

	public function user() {
		return $this->belongsTo(User::class, 'user_id');
	}
}
```
Sluggable and FullTextSearch just a traits for further work.
**Question**: As you may see, each translation related to different user. How to get translated articles with users? It retieves empty user atm, but I'm pretty sure bindings should be fine.
**UPD**: [Here's](https://github.com/Iworb/laravel-blog) complete example of my application.

**Comment by Gummibeer** [comment]
Can you take a look in your database if `user_id` has any value? If I take a look in your current setup you miss the `user_id` (and some other columns) in the `$fillable` property on the `ArticleTranslation` model. This could be the reason why the user relation is empty.

After this you can simply do `ArticleTranslation::where('user_id', Auth::id())->get()` or limit it also by `article_id` or whatever you want. You can also do the same starting from the `Article` model by using the `whereHas` query builder method. https://laravel.com/docs/5.6/eloquent-relationships#querying-relationship-existence
