### ISSUE TITLE
Model::translatedIn(LaravelLocalization::getCurrentLocale())->get(); doesn't return correct translations

### ISSUE THREAD

**Issue by NikolayKolibarov** [dimsav/laravel-translatable#477]
I have two locales at the moment - en and bg (bulgarian).
When I use Model::translatedIn('bg')->get(); I expect to get the bulgarian translations. However I get the translations for the default locale. It used to work a while ago. However I can't get it to work now. Someone experiencing the same problem?

**Comment by Gummibeer** [comment]
Your expectations are wrong - the scope returns just all models with a translation in the given locale.
You have to set your app/translator locale to get the attributes in requested locale.

**Comment by NikolayKolibarov** [comment]
Thanks for the heads up @Gummibeer! 
When I change the locale in app/translatable from 'en' to 'bg', I get the translations in bulgarian even if the current locale is 'en'. I want to get the translations for the current locale.

My idea is the following: Get all models with translations for the current locale using $models = Model::translatedIn(LaravelLocalization::getCurrentLocale()). 
Afterwards I want to access the translated properties for the current locale simply like so: 
$model->title. 
Is that accomplishable?

**Comment by Gummibeer** [comment]
Yes - set the config locale to `null` (see new hint in config introduced in #470 ).
This will force this package to use the current app/translator locale.

**Comment by NikolayKolibarov** [comment]
Worked like a charm! Thanks for the help @Gummibeer!
