### ISSUE TITLE
Get by slug and locale

### ISSUE THREAD

**Issue by maxi032** [dimsav/laravel-translatable#478]
I am trying to get a page by slug and a certain locale so according to the documentation this should work but it gets me the record in the fallback locale 
<pre>
Page::whereHas('translations', function ($q) use ($slug, $locale) {
    $q->where('locale','=', $locale)->where('slug','=', $slug);
})->first();
</pre>

This does: <code>select * from `pages` where exists (select * from `page_translations` where `pages`.`id` = `page_translations`.`page_id` and `slug` = 'contact-us' and `locale` = 'en') limit 1</code>

This may have something to do with mysql 5.7 and strict mode=true

**Comment by Gummibeer** [comment]
It's just the query that the page should have this translation. Which translation is displayed depends on your config or current app locale.
#470

**Comment by maxi032** [comment]
I am requesting for the locale in en. What I get is the result in default locale (not en)

**Comment by Gummibeer** [comment]
But is your config locale `null` and your current app/translator locale `en` or not? This is what counts for the displayed translation. In your query you just limit the `page` results - but in no way the translations.

Your query does:
> Give me the first page that has an englisch slug equal to `$slug`

After this the normal trait logic runs to get the corresponding translation.

**Comment by maxi032** [comment]
My app locale is fr and my app translatable locale is fr. 
The problem is that in this query: 
<pre>select * from page_translations where pages.id = page_translations.page_id and slug = 'contact-us' and locale = 'en'</pre> I get Unknown column 'pages.id' in 'where clause' although the column exists.

**Comment by maxi032** [comment]
From the documentation:

<strong>How can I select a country by a translated field?</strong>
For example, let's image we want to find the Country having a CountryTranslation name equal to 'Portugal'.
<pre>
Country::whereHas('translations', function ($query) {
    $query->where('locale', 'en')
    ->where('name', 'Portugal');
})->first();
</pre>
This is exactly what I want to do but with Page instead of Country

**Comment by Gummibeer** [comment]
Yes, this is what you've posted in the initial comment and this works. Your problem now is that you also want the translation to be in `en`. So you can set your app locale or use the `translate()` method.

```php
$page->translate('en')->name;
```
