### ISSUE TITLE
Only load translation for default locale?

### ISSUE THREAD

**Issue by shahkhalid-me** [dimsav/laravel-translatable#480]
I just want to load categories with only there default locale translation. Don't need to load all translations for a category. 

```
$categories = Category::all();
 return $categories;
```

**Output  :** 
```
Array[1][
  {
    "id": 1,
    "created_at": "2018-06-08 05:16:18",
    "updated_at": "2018-06-08 05:16:21",
    "title": "Test",
    "slug": "test",
    "translations": Array[200][
      {
        "id": 1,
        "title": "Test",
        "slug": "test",
        "category_id": 1,
        "locale": "en"
      },
      {
        "id": 2,
        "title": "Test Ur",
        "slug": "test-ur",
        "category_id": 1,
        "locale": "ur"
      }
      .
      .
      .
      .
    ]
  }
]
```

I just want this.

```
Array[1][
  {
    "id": 1,
    "created_at": "2018-06-08 05:16:18",
    "updated_at": "2018-06-08 05:16:21",
    "title": "Test",
    "slug": "test"
  }
]
```

**Comment by Gummibeer** [comment]
https://laravel.com/docs/5.6/eloquent-serialization#hiding-attributes-from-json

```php
$categories->makeHidden('translations');
```

**Comment by shahkhalid-me** [comment]
But the SQL query will still load all translations. I just want to load the one the default one.

**Comment by Gummibeer** [comment]
https://github.com/dimsav/laravel-translatable/blob/5f19c5b9253ea49baa935135ae2ffd37f81bc5d4/src/Translatable/Translatable.php#L301-L310
Does not support this atm - but it's still just one query.

**Comment by raiika** [comment]
If you only want to load the default locale you could call their "scopeWithTranslation" method and change the config translatable.php from 

    "locale" => null 

to

    "locale" => "your_default_locale"

and in controller

    Model::withTranslation()->get();

**Comment by Gummibeer** [comment]
Can you test the new `translation` relation in the linked PR? If it works for you I would be happy to know - otherwise where it's failing.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
