### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by nnasirzada** [dimsav/laravel-translatable#481]
I'm trying to run the following migration:
```
public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->decimal('price', 8, 2);
            $table->enum('discount_type', ['fixed', 'percent']);
            $table->decimal('discount_amount', 8, 2);
            $table->timestamp('discount_starts_at')->nullable();
            $table->timestamp('discount_ends_at')->nullable();
            $table->decimal('shipment_fee', 8, 2);
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('product_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('product_id');
            $table->string('description');
            $table->string('name');
            $table->string('slug');
            $table->string('meta_description');
            $table->string('meta_keywords');
            $table->string('meta_title');
            $table->string('locale')->index();

            $table->unique(['product_id', 'locale']);
            $table->foreign('product_id')->references('id')->on('products')->onDelete('set null');
            $table->foreign('locale')->references('code')->on('languages')->onDelete('restrict');
        });
    }
```
But I'm getting this error:
```   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `ecommerce`.`#sql-4214_99` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `product_translations` add constraint `product_translations_product_id_foreign` foreign key (`product_id`) references `products` (`id`) on delete set null) ```

Both products.id and product_translations.product_id columns have the same data type: unsigned int (10)

I did research but couldn't fix the issue. Is there anything I'm missing or doing wrong?

**Comment by nnasirzada** [comment]
@Gummibeer two migrations didn't fix the issue. I have also tried to manually add FK using raw query but it didn't work either. I'm getting the same error message.

**Comment by Gummibeer** [comment]
https://stackoverflow.com/q/8070336

It looks like your DB is flagged as corrupt and won't do anything more until this is fixed.
I would bet that your migration failed on the first run because the referenced `products` table didn't exist and not it's flagged as corrupted and you can do whatever you want and it will fail.

**Comment by nnasirzada** [comment]
@Gummibeer thank you for the link. It really helped me. After reading the accepted answer, I figured out what causes the error. For those, who have faced the same error:
First, I ran the following query: `show engine innodb status`. Under **Status** column, I found that message: 
```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
2018-06-22 16:30:53 3e0c Error in foreign key constraint of table `ecommerce`.`product_translations`:
Alter  table `ecommerce`.`product_translations` with foreign key constraint failed. You have defined a SET NULL condition but column 'product_id' is defined as NOT NULL in ' foreign key (`product_id`) references `products` (`id`) on delete set null' near ' on delete set null'.
```
The message itself is self-explanatory. In **product_translations** table, I changed `$table->unsignedInteger('product_id')` to `$table->unsignedInteger('product_id')->nullable();` and it solved the error.

**Comment by kevindesousa** [comment]
Hello, 
I have the same problem, i dont understand...

`Schema::create('shops', function (Blueprint $table) {
            $table->bigIncrements('id_shop');
            $table->string('domain_real');
            $table->string('domain_sandbox');
            $table->string('status');
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('shop_translations', function (Blueprint $table) {
            $table->bigIncrements('id_shop_translation');
            $table->integer('id_shop')->unsigned();
            $table->string('name');
            $table->string('description');

            $table->string('locale')->index();

            $table->unique(['id_shop','locale']);

            $table->foreign('id_shop')->references('id_shop')->on('shops')->onDelete('cascade');
            $table->softDeletes();
        });`

I have this error : `SQLSTATE[HY000]: General error: 1005 Can't create table `sportsvillage`.`shop_translations` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `shop_translations` add constraint `shop_translations_id_shop_foreign` foreign key (`id_shop`) references `shops` (`id_shop`) on delete cascade)`

But InnoDB works...

**Comment by Gummibeer** [comment]
@kevindesousa the first thing I see is that `shops. id_shop` and `shop_translations.id_shop` have different types - `bigint` vs `int`.

But this is in no way related to this package - it's MySQL and/or laravel/eloquent. If this doesn't fix it I don't have any other idea.

**Comment by kevindesousa** [comment]
Thanks @Gummibeer , I resolved the problem : 
```
$table->bigInteger('id_shop')->unsigned();
```
