### ISSUE TITLE
How to choose lang when use create() method

### ISSUE THREAD

**Issue by salipro4ever** [dimsav/laravel-translatable#485]
In case, it is a instance, i can assign a language to save:
```php
$greece->translate('en')->name = 'No name';
```
When use mass create() method, is there any way to do the same thing? Example:
```php
MyModel::translate('en')->create([...])
```

If use `Filling multiple translations` doc, i must change format of data. I dont want that.

**My temporary solution:**
```php
App::setLocale('jp');
MyModel::create([...])
App::setLocale('en');
```

**Comment by Gummibeer** [comment]
This puts all data on the models during `create()` https://github.com/dimsav/laravel-translatable/blob/5f19c5b9253ea49baa935135ae2ffd37f81bc5d4/src/Translatable/Translatable.php#L280-L296

So you can use one of the following ways:

```php
MyModel::create([
    'en'  => ['name' => 'Greece'],
    'fr'  => ['name' => 'Grèce'],
]);
```

```php
MyModel::create([
    'name:en' => 'Greece',
    'name:fr' => 'Grèce',
]);
```

```php
$model = new MyModel();
$model->setDefaultLocale('jp')->fill($data)->save();
$model->setDefaultLocale(null);
```

```php
App::setLocale('jp');
MyModel::create([...])
App::setLocale('en');
```
