### ISSUE TITLE
Fallback locale

### ISSUE THREAD

**Issue by bibiseb** [dimsav/laravel-translatable#489]
Hello,

I imported some countries to test your package. I only imported in english. Considering the doc at https://github.com/dimsav/laravel-translatable#fallback-locales I set the use_fallback configuration key to true. Then I wrote this code:

`dd(Country::where('code', 'be')->first()->translate('fr')->name);`

translate('fr') returns null. I was hoping that it would return the english translation.

Is it the expected behavior ?

**Comment by Gummibeer** [comment]
It is, you have to use `translateOrDefault()` to use the config value. `translate()` disables the fallback.

**Comment by bibiseb** [comment]
Thanks 👍
