### ISSUE TITLE
Get package's internal managed fields for a validation

### ISSUE THREAD

**Issue by SamdeVega** [dimsav/laravel-translatable#492]
Hello,

I'm developing a blog and found me with the next situation:

**y**: Can happen
**n**: Can't happen

| post_id  | slug                  | locale     | result |
|----------|---------------|------------|---|
| 1             | hellow-world   | en           | y |
| 1             | hellow-world   | es           | y |
| 2             | hellow-world   | de          | n |

I made a custom validator wich checks for a composite unique rule for slug+locale making posible to occur the insert of 2nd register after the 1st, but it also allows to insert the 3rd.
I noticed that I have to check that FK post_id is indeed same as previous existing registers for allowing insert.
Laravel-Translatable manages this field in background, so I can't get the value of the FK field through the Request object in validation.
How can I get package's internal managed fields like mentioned FK? or what workaround should I approach for making my validation?

Thanks.

**Comment by Gummibeer** [comment]
How do you save the translations? Do you save them by putting them on the Main-Model? If yes there is your FK as PK.
The package doesn't use any magic - it's just using normal eloquent relationship.

**Comment by Gummibeer** [comment]
And do you use the default `unique` rule?
https://laravel.com/docs/5.6/validation#rule-unique
**Adding Additional Where Clauses**
```php
'email' => Rule::unique('post_translations')->where(function ($query) use ($request) {
    return $query->where('locale', $request->get('locale'))->where('post_id', $request->get('post_id'));
})
```
*Just a fast try*

**Comment by SamdeVega** [comment]
I made a custom validator extending from Laravel's default one.
In it, I iterated over Request elements and stored those in an array wich is passed to the where clause, looking for that combination.
The problem that I found is that I can't get the post_id request parameter in my custom validator.

I will try that workaround declaring Rule with eloquent syntax instead of a custom validator.

Thanks for your answers.

**Comment by Gummibeer** [comment]
To get access to it you will have to pass the request into your validator.
But after reading again I think my code doesn't do what you want!?

If you have the request but don't know how to get the `post_id` it depends on where you have it? Is it an input field or do you just have it in the URL as route parameter?

**Comment by Gummibeer** [comment]
If it's just a route param you can do `$request->route('post')` - if you have model bindings (explicit or implicit) you will get the Post model instance and not just the ID.

**Comment by SamdeVega** [comment]
The `post_id` is the fk wich is generated when I call the create method in `PostController`, wich uses `Post` and also `PostTranslation` models through the package like it is explained in docs.

I don't have it in a form field or URL when I am goint to create a new post so I have to find a way for checking if a combination of `slug` + `locale` with other `post_id` than the one wich it is going to be created exists.

And for updating, I think that I have to check if a combination of `slug` + `locale` with the exception of the `post_id` that I am going to update exists.

Maybe this is not the correct way to proceed, I am not sure, but it sounds logical in my thoughts.

**Comment by Gummibeer** [comment]
During create you don't have to handle a post id. Everything will be new - so there can't be a translation with this post_id.

During update you will have the id in route or input (otherwise you can't update). So the only thing is your validaton logic where I just give ideas/hints (like above) but this isn't part of this package so you will have to find out yourself.
