### ISSUE TITLE
Any video tutorial?

### ISSUE THREAD

**Issue by wajid8703** [dimsav/laravel-translatable#493]
I am facing some issues during work with this package.
it would b easy for me if you could send me any video tutorial link for this package?

Thanks

**Comment by Gummibeer** [comment]
There isn't one - where do you struggle?

**Comment by wajid8703** [comment]
@Gummibeer  Actually, i am looking for a plugin or package for the solution of dynamic data translation. i am making a website which has two language English and Arabic, i am using only one one input field of english to store data in DB...is there any solution that i save only one language data and translate DB data into arabic by using plugin?.....i shall be very thankful to you if you could help me

**Comment by Gummibeer** [comment]
Just add the translation trait and config (like described in readme) to your model and save the english and arabic field values as translation.
Everything is described in the readme - if you have a specific problem I can help you more.

**Comment by wajid8703** [comment]
how it handles the dynamic data translation?...will it create own tables for the Arabic language or it will translate the incoming data into Arabic?

**Comment by Gummibeer** [comment]
This package needs a second translation table with all translations in it.
English & Arabic in your case.

If you want a package that does this in one column take a look into https://github.com/spatie/laravel-translatable - but in both cases you have to provide both values.

If you want automatic translation search for a Google/Bing etc. Translation library.

**Comment by wajid8703** [comment]
ok thanks friend for your time and help....it means i have to add data of both languages english and arabic into db and it will be populated according to the selected language.
