### ISSUE TITLE
Storing / updating differnet data in database.

### ISSUE THREAD

**Issue by alisherkasimovv** [dimsav/laravel-translatable#495]
This is first time when I am using Translatable on Laravel, so I have problems with storing / updating data in database.
For example, I have table <code>information</code>, which has fields to be translated into three languages. Also in this table there are fields which are not translatable like <code>phone</code>, <code>email</code> and so on.
On <code>Information</code> model I defined all properties:
```php
protected $fillable = [
    	'name',
    	'brief',
    	'about_company',
    	'address',
    	'phone',
        'email',
        'image',
        'slug'
    ];

    public $translatedAttributes = ['name', 'brief', 'about_company', 'address', 'slug'];
```
Then I created <code>InformationTranslation</code> model and wrote this:
```php
public $timestamps = false;
protected $fillable = ['name', 'brief', 'about_company', 'address', 'slug'];
```
On <code>InformationController</code> controller I tried to get the data and update the database.
```php
public function update(Request $request, $id)
{
	$this->validate($request, [
	    'name'    => 'required',
            'address' => 'required',
            'phone'   => 'required'
	]);
		
	$info = Information::find($id);

	$info->translate('en')->name = $request->get('name_en');
        $info->translate('ru')->name = $request->get('name_ru');
        $info->translate('uz')->name = $request->get('name_uz');
        $info->translate('en')->brief = $request->get('brief_en');
        $info->translate('ru')->brief = $request->get('brief_ru');
        $info->translate('uz')->brief = $request->get('brief_uz');
        $info->translate('en')->about_company = $request->get('about_company_en');
        $info->translate('ru')->about_company = $request->get('about_company_ru');
        $info->translate('uz')->about_company = $request->get('about_company_uz');
        $info->translate('en')->address = $request->get('address_en');
        $info->translate('ru')->address = $request->get('address_ru');
        $info->translate('uz')->address = $request->get('address_uz');
	$info->phone = $request->get('phone');
	$info->email = $request->get('email');
	$info->image = $request->get('image');

	$info->save();
	return redirect()->route('information.index');
	}
```
But, when I try to submit all filled data in a web-page it is not working. It only refreshes page and that's it. Also I tried multiple filling method like:
```php
$data = [
    'code' => 'it',
    'en' => [
      'title' => 'en title',
      'description' => 'en descrive'
      .....
    ]
];
```
But this method did not work either.
What can I do? Or I should divide all translatable and <i>not</i> translatable data into two tables?

This all I have done according to this [tutorial]( https://mydnic.be/post/how-to-build-an-efficient-and-seo-friendly-multilingual-architecture-for-your-laravel-application )

**Comment by alisherkasimovv** [comment]
Yes, I have created two tables according to installation process. I have two tables: One of them is main namely <code>informations</code>, and second for translations <code>informations_translations</code>. But on main table I have fields for untranslatable data, like I said above (phone, email, image).

Now,I tried this:
```php
$credintal->fill([
			'name:en' => $request->get('name_en'),
			'name:ru' => $request->get('name_ru'),
			'name:uz' => $request->get('name_uz'),
			'brief:en' => $request->get('brief_en'),
			'brief:ru' => $request->get('brief_ru'),
			'brief:uz' => $request->get('brief_uz'),
			'about_company:en' => $request->get('about_company_en'),
			'about_company:ru' => $request->get('about_company_ru'),
			'about_company:uz' => $request->get('about_company_uz'),
			'address:en' => $request->get('address_en'),
			'address:ru' => $request->get('address_ru'),
			'address:uz' => $request->get('address_uz'),
			'phone' => $request->get('phone'),
			'email' => $request->get('email'),
			'image' => $request->get('image'),
      ])->save();
```

**Comment by Gummibeer** [comment]
The translations table should be `information_translations` if your model is named `InformationTranslation`.

And you even don't get an exception? That's strange ...

Can you put in some dumps in the `save` method of the translatable trait to debug what it's doing!? So to check which `if` case it enters and what it tries to save?
This would help to know where it starts failing.

**Comment by alisherkasimovv** [comment]
Yes, there are no any exceptions.
And, I found my mistake. There is problem with routing. When I am pressing button Submit application cannot enter <code>update()</code> method. I tried everything, but for now I have this problem...
