### ISSUE TITLE
How we can lazy load all  translations to current model? 

### ISSUE THREAD

**Issue by Victorlerner** [dimsav/laravel-translatable#497]
Hi,
How we can lazy load all  translations to current model? 
now i had 2 queries http://prntscr.com/k7hjst it's is possible to have 1 sql queries?
for example if I have 10 post now it have make 20 queries, i thinks it's is big speed issues. 
http://prntscr.com/k7hloh

**Comment by Gummibeer** [comment]
Just as every other eloquent relationship:
```php
$modelWithTranslations = Model::with('translations')->get();
// or
$model = Model::all();
$model->load('translations');
```

And that's it! :)

**Comment by Victorlerner** [comment]
so I have this code now

```
	$categories = 	$category->with('translations')->get()->groupBy( 'parent_id' );
		foreach ($categories as $category){
			dump($category->translations->title);
		}

```
but it get me this error Property [translations] does not exist on this collection instance.
in Category.php I have this

```
	public function CategoryTranslation()
	{
		return $this->hasMany('Corp\CategoryTranslation');
	}


```
can you help with this?

**Comment by Gummibeer** [comment]
Have you added the trait? You don't have to add this relation by your own - it is added by the trait:
https://github.com/dimsav/laravel-translatable/blob/5a63ed1d0b872f6cd52d436262952eef0041d6ce/src/Translatable/Translatable.php#L138-L144
