### ISSUE TITLE
Deleting models does not delete translations. any ideas?

### ISSUE THREAD

**Issue by unitedworx** [dimsav/laravel-translatable#498]
I noticed that Deleting models does not delete translations. any ideas? why?

I would assume that onDelete cascade on the translated table would handle this???

here is my migrations

```php
<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTypesTable extends Migration
{
    public function up()
    {
        Schema::create('types', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->integer('parent_id');
            $table->string('slug');
            $table->float('sort');
        });
    }

    public function down()
    {
        Schema::dropIfExists('types');
    }
}
```

```php
<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTypeTranslationsTable extends Migration
{
    public function up()
    {
        Schema::create('type_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('type_id')->unsigned();
            $table->string('locale')->index();
            $table->string('name');
            $table->unique(['type_id', 'locale']);
            $table->foreign('type_id')->references('id')->on('types')->onDelete('cascade');
        });

        \DB::statement("INSERT INTO type_translations (type_id, locale, name) SELECT id, 'en', name FROM types");

        Schema::table('types', function (Blueprint $table) {
            $table->dropColumn('name');
        });
    }

    public function down()
    {
        Schema::drop('type_translations');
        Schema::table('types', function (Blueprint $table) {
            $table->string('name');
        });
    }
}
```

**Comment by Gummibeer** [comment]
You can take a look here: https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html 
But `ON DELETE {reference_option}` is supported since "ever".

Do you use soft deletes? It's not in your migration but I don't know if your model uses the trait?

**Comment by unitedworx** [comment]
not using soft deletes! which trait are you referring for in my models? 

not sure if on delete is supported for ever since on my production server (mysql 5.1) my tables dont seem to contain on delete (if I peak on table structure) where local/development versions do contain it (mysql 5.6) I think its a mysql version related issue than anything else. just trying to confirm before trying to upgrade mysql to newer version on production.

**Comment by Gummibeer** [comment]
Ok, I wasn't aware that you use `MySQL 5.1`. You should upgrade in every case - I don't find it but I'm pretty sure that `Laravel v5` requires at least `MySQL v5.6`.
And upgrading to `v5.7` shouldn't be a problem. Just a switch to `v8` could make some trouble.

**Comment by Gummibeer** [comment]
I will close this - reopen if the error keeps up after MySQL upgrade.

**Comment by unitedworx** [comment]
I am on laravel 5.1 and surely does not complain about mysql version :) I just asked my dedicated server guys to upgrade to 5.7 and see how it goes. I need to figure out some migrations to get this back in there since dumps from production to local have killed this for me locally as well :( so I will need to come up with migrations to delete orphan translation data and get on delete cascade back in there! I have this issue with 5-6 projects. I will manage :) ! good that I have discovered this sooner than later!

**Comment by Gummibeer** [comment]
It doesn't complain and I don't find a minimum MySQL version in the docs - but all discussions I found recommend 5.6 and above.
I think laravel doesn't have a minimum MySQL version because it depends on what you use. JSON field type requires 5.7 for example.

I even wasn't aware that there is MySQL below 5.6 out there. 😂
