### ISSUE TITLE
translatedIn not working

### ISSUE THREAD

**Issue by sythasiek** [dimsav/laravel-translatable#512]
I have 3 language like en,ch, jp but when can't get translate  using translatedIn
This my Page Model
```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;
class Page extends Model
{
   use Translatable;

   public $translatedAttributes = [
        'title',
        'site_title',
        'slug','photo', 
        'site_description', 
        'description',
    ];
}
```

This my PageTranslation Model
```php
namespace App;

use Illuminate\Database\Eloquent\Model;

class PageTranslation extends Model
{
    public $timestamps = false;
}
```

I call it in Controller like this 
```php
public function getPages()
{
    $page = Page::translatedIn('ch')->get();

    return view('backend.pages.page', ['pages' => $page]);
}
```

**Comment by Gummibeer** [comment]
The `translatedIn()` scope doesn't set the current locale. It just returns all models that have a translation with the given locale. So if you want to display all translations in `ch` I recommend you to set your current app locale or if you need this to stay what it is update the config value.
https://github.com/dimsav/laravel-translatable/blob/633b24127bacc97bc780e3baf1482a6c8b12eb40/src/config/translatable.php#L34-L46

**Comment by Gummibeer** [comment]
#477

**Comment by sythasiek** [comment]
Thank for you help :)
