### ISSUE TITLE
database structure options

### ISSUE THREAD

**Issue by gareth-ib** [dimsav/laravel-translatable#514]
Great project!
I think it would be nice for organization purposes if the db structure could be mod'd a bit to get the translated data outside of the central normal data schema. As well as have languages into their own tables. Which would cut down on overall data and index size.
Maybe as an optional structure, so the people who are fine with the current style can leave it.

**multiple schemas**
```
translate_en.city ( city_id, name )
translate_en.country ( country_id, name )
translate_es_mx.country ( country_id, name )
translate_es_co.country ( country_id, name )
```
**separate schema with separate tables**
```
translations.city_en ( city_id, name )
translations.country_en ( country_id, name )
translations.country_es_mx ( country_id, name )
translations.country_es_co ( country_id, name )
```

Also potential different language encoding issues would be solved by this

**Comment by Gummibeer** [comment]
I've no idea what your problem or goal is!?
But I can ensure that we won't support multiple database table structure setups.
But if you want to keep languages in another table and use foreign keys you can use the locale as a string foreign key or try to use IDs as as locale. It should work but I'm not sure.
I hope that this helps!?

And regarding to encoding issues: I don't know any language that's not UTF8 compatible!?

**Comment by gareth-ib** [comment]
yeah I dunno about language encoding issues, was just a side thought

**Comment by gareth-ib** [comment]
as far as the goal.. the goal is to not flood the main schema with translation tables. And also to make the data size smaller. Putting a field as a string in every row would be giant.

so comparing the current link table concept there is now being..
**main table**
```
myschema.countries ( id )
```
**translation data tables**
```
myschema.country_translations ( country_id, name, locale )
```
so there's already that string field in every row, and the index to make it searchable.
as opposed to the samples I posted above remove that string table from every row and index.

so instead of this from the docs...
```sql
SELECT * from myschema.countries
JOIN myschema.country_translations as t on t.country_id = countries.id 
WHERE locale = 'en'
GROUP BY countries.id -- not sure if this group by is needed
ORDER BY t.name desc
```
would be more like..

```sql
SELECT * from myschema.countries
JOIN translations.country_en as t on t.country_id = countries.id 
ORDER BY t.name desc
```

**Comment by Gummibeer** [comment]
Ok, this won't gonna happen. And to honest: the size difference isn't real. An ID column could be filled up to X chars as int. The locale column will be forever limited, in most cases 2 or 5 chars (few locales have 6). And as I wrote above it should be possible to change the locale column to int and use foreign keys from a languages table.

But if you don't want the translation tables to stay in your main scheme you can put it into another one (translations). Just use the `$connection` property of the translation model.

**Comment by gareth-ib** [comment]
ah I see.. you don't understand how to use schemas ( "Schemas" in PG, "Databases" in MySQL )? That seems to be a pattern with MySQL users.
A model is defined what schema it belongs to by just putting it in the table name. It's not a separate connection.

Would be something along the lines of...

```php
namespace App\Models\Translate\En;
use Illuminate\Database\Eloquent\Model;
class Country extends Model {
	protected $table = 'translations_en.country';
}
```

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
