### ISSUE TITLE
Identifier too long

### ISSUE THREAD

**Issue by jbkhellas** [dimsav/laravel-translatable#515]
Καλησπέρα!
First of all, a big thank you for this package, it has helped me a lot!
Its pretty easy to use and to modify yet i ran into one problem.
Trying to create a table for the translations of a model using this:
`

Schema::create('property_category_translations', function(Blueprint $table)
        {

            $table->increments('id');

            $table->integer('property_category_id')->unsigned();

            $table->string('title');

            $table->string('locale')->index();

            $table->unique(['property_category_id','locale']);

            $table->foreign('property_category_id')->references('id')->on('property_categories')->onDelete('cascade');
        });`

I get a response: 
`
SQLSTATE[42000]: Syntax error or access violation: 1059 I
dentifier name 'property_category_translations_property_category_id_locale_unique' is too long (SQ
L: alter table 'property_category_translations' add unique 'property_category_translations_propert
y_category_id_locale_unique'('property_category_id', 'locale'))
`

Any insights?
Thank you in advance!

**Comment by Gummibeer** [comment]
This isn't related to this package but you can use the second parameter of the `unique()` method to define a custom name.
https://laravel.com/docs/5.6/migrations#creating-indexes
> Laravel will automatically generate a reasonable index name, but you may pass a second argument to the method to specify the name yourself:
