### ISSUE TITLE
Dynamic fallback langs

### ISSUE THREAD

**Issue by tokomeno** [dimsav/laravel-translatable#516]
Hello, I can't find in docs, is it possible to have dynamic fallback langs, for example, I have two lang on my website English and Franch. 

When English translations of an article will not be presented in the database to be a callback lang French but when French translations will not be presented to be callback English. To switch between this two lang that article show page won't be empty.

**Comment by Gummibeer** [comment]
The config key `translatable.fallback_locale` is used to get the fallback locale - so you can do `config('translatable.fallback_locale', 'new_fallback')`.

The following method could be a starting point to customize the fallback finding. But the `$locale` parameter isn't available everytime. So you should use `app()->getLocale()` to get your current locale and could return the corresponding fallback via a simple switch-case or anything else.
https://github.com/dimsav/laravel-translatable/blob/633b24127bacc97bc780e3baf1482a6c8b12eb40/src/Translatable/Translatable.php#L345-L353

**Comment by tokomeno** [comment]
Thanks worked just fine
