### ISSUE TITLE
Please support for laravel 5.7

### ISSUE THREAD

**Issue by eliyas5044** [dimsav/laravel-translatable#520]
Thanks for your awesome package. Please support for `laravel: ^5.7.*`

**Comment by Gummibeer** [comment]
#518 is already open. Today I've holiday so I can't release. @dimsav could or we wait until tomorrow. 😉
My opinion: don't use a super fresh release in production.

**Comment by Gummibeer** [comment]
[v9.2.0](https://github.com/dimsav/laravel-translatable/releases/tag/v9.2.0) is released now.
