### ISSUE TITLE
Model Events Not working

### ISSUE THREAD

**Issue by ruzgarhasan** [dimsav/laravel-translatable#524]
I also save translations when I save an item, but. If there is no change in translation, Model Events is not triggering. What can I do to make it happen?
```php
class ArticleTranslation extends Model
{
    use \App\Traits\Routable;
}
```

```php
trait Routable
{

    protected static function boot() {
        parent::boot();
        self::saved(function($item){
            #Not Working
       });
}
```

**Comment by Gummibeer** [comment]
First never boot a trait by `boot` method but use the special boot-trait one https://laravel-news.com/booting-eloquent-model-traits

And why should there be a save event, on the translation model, if there is no change? The `saved` event is triggered on the main model - following the normal eloquent logic.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
