### ISSUE TITLE
Object::create problem

### ISSUE THREAD

**Issue by OtiZ2** [dimsav/laravel-translatable#526]
This happen if i try create new row with create metod

> Class 'App\ProductTranslationTranslation' not found
> 660:      /**
> 661:         * Create a new model instance for a related model.
> 662:         *
> 663:         * @param  string  $class
> 664:         * @return mixed
> 665:         */
> 666:        protected function newRelatedInstance($class)
> 667:        {
> 668:            return tap(new $class, function ($instance) {
> 669:                if (! $instance->getConnectionName()) {
> 670:                    $instance->setConnection($this->connection);
> 671:                }
> 672:            });

```php
$data = array(
	'name:en'   =>  'name en',
	'name:sk'   =>  'name sk',
	'name:cz'   =>  'name cz',
);

$product = new Product;
$product->create($data);
```

My Product model
```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use \Dimsav\Translatable\Translatable;


class Product extends ObjectModel
{

    use Translatable;

    public $translationModel = 'App\ProductTranslation';

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	public $translatedAttributes = [
		'name', 'text'
	];
    protected $fillable = [
        'reference', 'supplier_reference', 'id_manufacturer', 'id_supplier', 'price',
    ];

}
```

**Comment by Gummibeer** [comment]
1. Your defined `$translationModel` property is the same like the default - you can drop it
2. I recommend to use `ProductTranslation::class` instead of a hardcoded string

But so far I got into the code it could be that there is a bug - you could try to prefix the class-name by a `\` to get a FQCN.

**Comment by OtiZ2** [comment]
1. ok i drop it.
2. Where should i use it ?

**Comment by Gummibeer** [comment]
I've added a unittest for this in #527 and it passed.
Can you please provide a whole stack-trace to this exception!?

**Comment by OtiZ2** [comment]
https://pastebin.com/RbADwejC

**Comment by OtiZ2** [comment]
Ok, i got it. There is not bug.
I just extends model ProducTranslation with my ObjectModel wich describe basic mode Product.

Thank you very much for helping. You are the best!
