### ISSUE TITLE
i cannot able to store translated value in database 

### ISSUE THREAD

**Issue by Arslan1122** [dimsav/laravel-translatable#529]
```php
Route::get('create', function() {
        $article = new App\Event();
        $article->save();
         $article->translateOrNew('ar')->name =  "Home";
        $article->translateOrNew('ar')->description = "Home";
        $article->save();
    });
```

it doesnot store arabic in database it stores as Home in database.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
