### ISSUE TITLE
Make multilevel menu or category from database with translation

### ISSUE THREAD

**Issue by rperednikas** [dimsav/laravel-translatable#531]
Hello, 
I've tried different ways to make multi level support in code, but it didn't work:

e.x
route::get({slug})->....
route::get({parent},{slug})->....

but code only understand route::get({slug}), on route::get({parent},{slug}) throws 404 error any help?

**Comment by Gummibeer** [comment]
Sorry but I've absolutely no idea of what you are trying and how this package is related to it?

**Comment by rperednikas** [comment]
Controller
```
public function show($slug){
        $pages = Page::whereTranslation('slug', $slug)->firstOrFail();
        if ($pages->translate()->where('slug', $slug)->first()->locale != app()->getLocale()) {
            return redirect()->route('pages.show', $pages->translate()->slug);
        }
        return view('FrontEnd.show', compact('pages'));
    }
    public function show2level($parent, $slug){
    return $this->show($parent . '/' . $slug);
    }

```
 Routes

```
Route::get('/{slug}', ['uses' => 'PageController@show']);
Route::get('/{parent}/{slug}', ['uses' => 'PageController@show2level']);
```

Live website:
I wanna get full data to this url
http://incognitusshop.com/lt/privatiems-klientams/vartojimo-paskola
But it only understands
http://incognitusshop.com/lt/privatiems-klientams
http://incognitusshop.com/lt/vartojimo-paskola

It need to be
http://{website}/{locale}/{slug}
if have parent use this
http://{website}/{locale}/{parent}/{slug}

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
