### ISSUE TITLE
Changing model name

### ISSUE THREAD

**Issue by mrcatman** [dimsav/laravel-translatable#532]
I'm using non-standard model name ("CaseModel") because "case" is a reserved word in PHP. My model looks like:

```
namespace App;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class CaseModel extends Model
{
    use Translatable;
    public $table = "cases";
    public $translationModel = 'App\CaseTranslation';
    public $translatedAttributes = ['link','title','description'];
}
```
But when I try to save a model, an error appears:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'case_translations.case_model_id' in 'where clause' 
```

How can I change "case_model_id" to "case_id" here?

**Comment by Gummibeer** [comment]
Hey @mrcatman ,

This method returns the foreign key used by the relationship. So you can modify `$translationForeignKey`.

https://github.com/dimsav/laravel-translatable/blob/cf6c8dcdbb5bbe1166d252952281a34b45c10ac7/src/Translatable/Translatable.php#L134-L145

**Comment by fawel11** [comment]
Great!

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
