### ISSUE TITLE
Cannot override default languaes

### ISSUE THREAD

**Issue by criting** [dimsav/laravel-translatable#535]
Hello! I cannot seem to override the default languages. My friend and I are working on a project and everything works perfect on his end, however, when I pull the project, I see these languages as default ones:

  0 => "en"
  1 => "fr"
  "es"
    0 => "MX"
    1 => "CO"

In the translatable file, the languages are edited like this 

 'locales' => [
        'bg' => 'Български',
        'en' => 'Английски'
    ],

**Comment by Gummibeer** [comment]
The first idea, if it works on your friends setup, do you have a cached config?
`artisan config:clear`
