### ISSUE TITLE
Use polymorphic relationship instead of one to many

### ISSUE THREAD

**Issue by jordantsap** [dimsav/laravel-translatable#536]
I have a lot of models like company, product, event, group and types of each,  and i want to connect all together with dimsav/translatable as model, named "translatable" or othen suggested, decause i dont want to have somany models.
So my question is:
Can i use one model as name "translatable" or there is naming issue?

**Comment by Gummibeer** [comment]
The main issue will be that you will have a lot of nullable fields in this table.

The polymorphic relation isn't a goal of this package. If we would add this it will be just a duplicate of spaties package.

**Comment by jordantsap** [comment]
I decided to adjust namespace accordingly in order to make it possible and not have so many models inside the models folder
