### ISSUE TITLE
Conditionally enabling translations for models / multi tenancy

### ISSUE THREAD

**Issue by garygreen** [dimsav/laravel-translatable#537]
In a multi-tenancy application, you may find a need to disable translations for a certain model.

What's the best way to do this? Currently I'm conditionally building an array of translatable attributes by overriding the `__get` method, but this seems a bit hacky.

```php
class Post extends Eloquent
{
	use Dimsav\Translatable\Translatable;

	public function __get($prop)
	{
		// Conditionally enable translations for only certain retailers.
		// This is more of a hack, as the translatable package doesn't
		// have a defined way of conditionally enabling translations.
		if ($prop == 'translatedAttributes') {
			if (Auth::user()->fromRetailer('blah')) {
				return [];
			}
	
			return ['title'];
		}

		return parent::__get($prop);
	}
}
```

This is still problematic because you can technically still attempt to add translations for this model as it uses the trait.

So is there a recommended way to conditionally disable translation for a certain model altogether?

**Comment by garygreen** [comment]
Of course, the logic for deciding when translations are enabled should be left up to the app to decide, whether that be in a policy/controller/validator, as you said. However, it's currently pretty difficult to turn off the translator altogether when needed - you need to overrload so many methods.

For example, I've just come across a problem where even if you return `$translatedAttributes` as an empty array, if you attempt to save a model without any locales set in your config, you'll get an exception.

It would be useful to have some kind of `translationsDisabled()` method that completely turns off all translation based stuff. Or at least assume that translations is disabled if the `translatedAttributes` is an empty array.

Currently, the alternative is to override a lot of methods, which seems hacky. Or two, just always add translations for the default locale, which means potentially adding duplicate information across your models just for the sake of it.

**Comment by Gummibeer** [comment]
> Or two, just always add translations for the default locale, which means potentially adding duplicate information across your models just for the sake of it.

How does it come that a single translation would duplicate your saved data? 🤔
I think that there is the problem. 🙄

**Comment by garygreen** [comment]
Our table structure is like:

```
posts
-------
id    name
```

For the translations:

```
post_translations
id     post_id     name
```

In the case of a post model that doesn't require translations, it's easier to save directly to the posts table, to avoid additional complexity in managing translations/loading additional models. This may seem like duplicate of the table structure in a sense, but if only 20% of clients use the translations, it doesn't make sense to always have to save the translated attributes in the additional table when translations are essentially disabled.

Hopefully that makes sense.

**Comment by Gummibeer** [comment]
But here you have your original "failure". I know that some users of this package want this and build ways to get this but this isn't how it works.
Without any overloading this shouldn't work at all!? It's not meant to have the same column on two models/tables. At the end this adds your unwanted complexity. :/
What I would do in your case would be to save the translation, like meant by this package, only in the translation model and use redis (or whatever cache you use) to save this value as `post:{id}:default_title`.
To do this I would use the `creating` observer event and `getTitleAttribute()` accessor method. This will allow you, without any package override logic, to save the additional query if not needed (by some conditions in the accessor) but also deliver the translations if wanted.

Would this work for you?

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
