### ISSUE TITLE
dynamic languages

### ISSUE THREAD

**Issue by wisepotato** [dimsav/laravel-translatable#54]
So, love the package. But I have dynamic languages... Currently I am using a closure for the available languages in the config, but this is less than ideal.

Would this not be a nice addition to the package, to make a language table? It could also include a column for 'active', which could help in real-world applications.

Or atleast make it easier to use dynamic languages, couldnt think of a great way to implement this....

**Comment by daverdalas** [comment]
@wisepotato If you are still looking for a solution for your problem or someone in the future will look, you can see my fork: https://github.com/daverdalas/laravel-translatable
