### ISSUE TITLE
to_array_always_loads_translations doesn't work

### ISSUE THREAD

**Issue by llioor** [dimsav/laravel-translatable#540]
Hi,
I set `to_array_always_loads_translations = false` in config.
I run `php artisan config:cache` to load the new value.

Still when I get the model
`$bonus = Bonus::where('type', $type)->firstOrFail();`
When I log
`Log::info('bonus', [$bonus->toArray()]);`

I have the `translations` array will all languages.
I checked and I don't have "with" or any function which will load the translations automatically.
This is the Bonus model:
```php
class Bonus extends Model
{
    use SoftDeletes, Uuids, Translatable;

    const BONUS_TYPE_VERIFIED = 'verified';

    public $incrementing = false;
    protected $fillable = [
        'amount',
        'times',
        'type'
    ];

    public $translatedAttributes = ['title', 'description'];
    public $translationModel = BonusTranslation::class;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public static function getTypes()
    {
        return [
            self::BONUS_TYPE_VERIFIED
        ];
    }
}
```

and this is the translations model:
```php
class BonusTranslation extends Model
{
    use Uuids;

    public $timestamps = false;

    protected $fillable = ['title', 'description'];
}
```

Can someone help? I don't want to see translations in any request, I want to have it only when I ask for it with `withTranslation` or `with('translations')` ...

Thank you in advance!

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
