### ISSUE TITLE
Feature request: Filling/upsdating multiple translations at once

### ISSUE THREAD

**Issue by Chris1234567899** [dimsav/laravel-translatable#541]
I'd like to add or update multiple translations at once in my model.

The easiest way would be using the translations array in the input that is as well in the output like:
`"translations":[
    {
      "locale": "es",
      "title": "Test spanish",
      "model_id": 1
    },
    {
      "locale": "en",
      "title": "Test english",
      "model_id": 1
    }
  ]`

An option would be doing this in the save method of the model and just setting a optional boolean in the model like 
`protected $overwriteTranslations=true`
or something alike.
What do you think?

**Comment by Gummibeer** [comment]
This package already offers multiple ways to do this.

add the locale to the field key:
```php
$model->update([
  'title:es' => 'Test spanish',
  'title:en' => 'Test english',
]);
```
or use the locale as array-key:
```php
$model->update([
  'es' => [
    'title' => 'Test spanish',
  ],
  'en' => [
    'title' => 'Test english',
  ],
]);
```

**Comment by Chris1234567899** [comment]
Ah thanks, for some reason I thought this would only work during creating a new model. I'll close the issue then.

**Comment by Gummibeer** [comment]
No, also for update - the only thing that won't work this way is a sync. So if you want to delete translations that aren't in the new array of translations you have to use `deleteTranslations()`.
https://github.com/dimsav/laravel-translatable#available-methods
