### ISSUE TITLE
Number zero will wrong translated

### ISSUE THREAD

**Issue by approached** [dimsav/laravel-translatable#543]
Hi all

I have to two languages and the fallback language is english. This package can not translate a zero as number(string).

Database:
![screen shot 2019-01-24 at 11 40 05](https://user-images.githubusercontent.com/3439330/51672884-e22e8600-1fcc-11e9-90a1-e3416d275335.png)

Tinker:
```
>>> app()->setLocale('de');
=> null
>>> AttributeValue::find(14)->value;
=> "naanaa"
```

If i change the zero number it will be work.

**Comment by Gummibeer** [comment]
duplicates #393

**Comment by Gummibeer** [comment]
https://github.com/dimsav/laravel-translatable/releases/tag/v9.5.0
