### ISSUE TITLE
Bug with locale code "id" (Indonesian) or whatever locale that has the same code that a model attribute

### ISSUE THREAD

**Issue by mariavilaro** [dimsav/laravel-translatable#546]
I just found a bug in this code (Translatable.php):

    public function fill(array $attributes)
    {
        foreach ($attributes as $key => $values) {
            if ($this->isKeyALocale($key)) {
                $this->getTranslationOrNew($key)->fill($values);
                unset($attributes[$key]);
            } else {
                list($attribute, $locale) = $this->getAttributeAndLocale($key);
                if ($this->isTranslationAttribute($attribute) and $this->isKeyALocale($locale)) {
                    $this->getTranslationOrNew($locale)->fill([$attribute => $values]);
                    unset($attributes[$key]);
                }
            }
        }
        return parent::fill($attributes);
    }

When the locale code is "id", one of the attributes of the model is "id", so isKeyALocale('id') returns true and $this->getTranslationOrNew($key)->fill($values); throws the error `Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::fill() must be of the type array, string given`. I think this would happen always that a Model attribute is called like a locale code.

It's easy solvable with this code:

    if ($this->isKeyALocale($key) && is_array($values)) {
        $this->getTranslationOrNew($key)->fill($values);
        unset($attributes[$key]);
    }

But I have a question before making a pull request: when is this code called? When is $key a locale and $values an array? In my current use of Translatable, this code never runs.

**Comment by Gummibeer** [comment]
This code should run if you pass a multidimensional array like:
```php
[
  'de' => [
    'name' => 'Deutschland',
  ],
  'en' => [
    'name' => 'Germany',
  ],
]
```

I would be happy to see a PR for this. If you do all existing tests should pass and it would be great to have a new test that tests your described bug.

**Comment by mariavilaro** [comment]
Ahhhh ok, I never did this. Ok I will work in the PR!

> But a simple `is_array()` check could also lead to errors. It's possible to have attributes that can hold arrays as value (`collection`/`json`)

Yes you are right... But at least with the "is_array" check we can solve the current problem (that is... indonesian - id, and we know that the id attribute is never translatable). And I guess that is not very common for an app to have translatable attributes named as current locale codes that can hold arrays. What do you think?

**Comment by Gummibeer** [comment]
That's why I think about a fixed `is_array() && $name == 'id'`.
This would solve the Indonesian problem and prevent errors with other options.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
