### ISSUE TITLE
Force to  return translated field in forced locale in main query resutl for a specific query

### ISSUE THREAD

**Issue by fawel11** [dimsav/laravel-translatable#548]
`Subject::whereIn('id', [1,2,3])->withTranslation('bn')->get();`

``[[{"id":8,"subject_name":"Moral Education","translations":[{"id":10,"subject_id":"8","subject_name":" Moral Education","locale":"en"}]}]`

I want to force return main subject_name in bn (if found) for the query:
like:
``[[{"id":8,"subject_name":"subjent name in bn","translations":[{"id":10,"subject_id":"8","subject_name":" Moral Education","locale":"en"}]}]`

I want bn for specific query while global locale is en.

**Comment by Gummibeer** [comment]
Hey, atm you can solve this by setting the config locale or the app translator locale before the query.
But feel free to add this feature to the scope and pass an optional argument.
If you add this feature in a PR please provide also a new unittest for this feature. 😊

**Comment by fawel11** [comment]
What config should i change before the query?
Your next 2 sentence is not understood yet!
What do you mean by PR?

**Comment by Gummibeer** [comment]
This method returns the locale used fur everything:
https://github.com/dimsav/laravel-translatable/blob/f27eda99a5f90579ccd40ccf9d827a04d131db55/src/Translatable/Translatable.php#L783-L791

PR is a Pull Request to let you add changes to this package.
https://help.github.com/articles/about-pull-requests/

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
