### ISSUE TITLE
Saving in translated model instead of saving in original model

### ISSUE THREAD

**Issue by LaithAmmouri** [dimsav/laravel-translatable#560]
Hi,

I'm having an issue in saving data in my original model, when I wanna save in (SchoolGrade) "Original model" by using a helper function, the data is saved in the translation model (SchoolGradeT).

The codes:

**Original Model Code:**
```php
<?php

/**
 * Created by Reliese Model.
 * Date: Thu, 17 Jan 2019 11:22:32 +0000.
 */

namespace App;

use Illuminate\Database\Eloquent\Model as Eloquent;
use Dimsav\Translatable\Translatable;
use App\TranslationModels\SchoolGradeT;

/**
 * Class SchoolGrade
 * 
 * @property int $id
 * @property string $name
 * @property int $school_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * 
 * @property \App\School $school
 *
 * @package App
 */
class SchoolGrade extends Eloquent
{
    use Translatable;
    use \Backpack\CRUD\CrudTrait;
    use \Illuminate\Database\Eloquent\SoftDeletes;

    public $translatedAttributes = ['name'];

    protected $casts = [
		'school_id' => 'int'
	];

	protected $fillable = [
		'name',
		'school_id'
	];

    protected $visible = [
        'id',
        'name',
        'school_id'
    ];

    /**
     * OVERRIDES Dimsav\Translatable\Translatable getAttributeOrFallback function
     * Returns the attribute value from fallback translation if value of attribute
     * is empty and the property fallback is enabled in the configuration.
     * in model.
     * @param $locale
     * @param $attribute
     * @return mixed
     */
    private function getAttributeOrFallback($locale, $attribute)
    {
        $translation = $this->getTranslation($locale);

        if ((!$translation instanceof Model ||
                empty($translation->$attribute)) &&
            $this->usePropertyFallback()) {
            $translation = $this->getTranslation($this->getFallbackLocale(), false);
        }

        if ($translation instanceof Model) {
            return $translation->$attribute;
        }

        if ($translation === null && isset($this->attributes[$attribute])) {
            return $this->attributes[$attribute];
        }

        return null;
    }

	public function school()
	{
		return $this->belongsTo(School::class);
	}

    public function translatables()
    {
        return $this->hasOne(SchoolGradeT::class, 'school_grade_id');
    }
}
```

**Translation Model Code:**
```php
<?php

/**
 * Created by Reliese Model.
 * Date: Thu, 14 Feb 2019 11:11:46 +0000.
 */

namespace App\TranslationModels;

use Illuminate\Database\Eloquent\Model as Eloquent;

/**
 * Class SchoolGradeT
 * 
 * @property int $id
 * @property int $school_grade_id
 * @property int $language_id
 * @property string $locale
 * @property string $name
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 * @property \App\Language $language
 * @property \App\SchoolGrade $school_grade
 *
 * @package App
 */
class SchoolGradeT extends Eloquent
{
    use \Backpack\CRUD\CrudTrait;

    protected $visible = ['school_grade_id', 'name'];
    protected $fillable = ['name', 'language_id', 'locale', 'school_grade_id'];
    public $timestamps = true;

	public function language()
	{
		return $this->belongsTo(\App\Language::class);
	}

	public function school_grade()
	{
		return $this->belongsTo(\App\SchoolGrade::class);
	}
}

```

**Helper Function Code:**
```php
    public static function fillGrades($schoolId){

        $grades = [
            '1st grade',
            '2nd grade',
            '3rd grade',
            '4th grade',
            '5th grade',
            '6th grade',
            '7th grade'
        ];
        
        foreach ($grades as $name) {
            SchoolGrade::create([
                'name' => $name,
                'school_id' => $schoolId,
            ]);
        }

        return true;
    }
```

**API Call Code:**
```php
    Route::get('test/{id}', function ($id) {

        return response()->json(
            [
                'status' => "success",
                'data' => \App\Helpers\Helper::fillGrades($id),
            ],
            200
        );
    });
```
Thanks in advance, highly appreciated!

**Comment by LaithAmmouri** [comment]
If I use this code in the helper instead of the written code it will work, but I can't update every single function in my project like this, any solutions?
```php
    public static function fillGrades($schoolId){

        $grades = [
            '1st grade',
            '2nd grade',
            '3rd grade',
            '4th grade',
            '5th grade',
            '6th grade',
            '7th grade'
        ];
        
        foreach ($grades as $name) {
            $schoolGrade = new SchoolGrade();
            $schoolGrade->translatedAttributes = [];
            $schoolGrade->name = $name;
            $schoolGrade->school_id = $schoolId;
            $schoolGrade->save();
        }

        return true;
    }

```

Thanks in advance!

**Comment by Gummibeer** [comment]
@LaithAmmouri if I get what's your problem it isn't one.
This package isn't made/thought to have the translated attribute value duplicated. This would be against multiple principles.
So instead of supporting you by misusing this package - I would like to understand why you think you would have to have the value duplicated and find a solution without duplication.

#80

**Comment by LaithAmmouri** [comment]
@Gummibeer the problem is that when I want to save the values in the original model, it's saving in the translation model, there is no duplication, it just ignores the original model and immediately assume that I want it to save in the translation model, that's why I'm getting the following error:

Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field &#039;language_id&#039; doesn&#039;t have a default value (SQL: insert into `school_grade_ts` (`locale`, `name`, `school_grade_id`, `updated_at`, `created_at`) values (ar, 1st grade, 380, 2019-03-07 10:48:20, 2019-03-07 10:48:20)) in file /Users/hwkuser/projects/platform-backend/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664.

**Comment by Gummibeer** [comment]
```php
public $translatedAttributes = ['name'];
protected $fillable = ['name', 'school_id'];
```

If the `name` is translatable it's saved on the `SchoolGradeT` model - so there is no reason to define it fillable on the base model.
If you want to save `name` on the base model there is no reason to define it translatable.
To have it in booths and your expectation that it's saved in the base model would lead to duplication.
The next is: your error complains about `language_id` - from should this value come? Do you have n observer that resolves the `locale` to a language and attaches it if the `language_id` is empty? Or how do you want to save translations successful? This package doesn't need and can't work with a language model.
Your `translatables` relation on the base model is also a duplication of the `translations` one. https://github.com/dimsav/laravel-translatable/blob/f1d5569b6c89da1e89dbe48b9bcbb9e54b0afa2c/src/Translatable/Translatable.php#L158-L161

I see what you are doing in the `getAttributeOrFallback` method - but first you could reduce it by calling the original method and if it returns `null` do your own one.
https://andy-carter.com/blog/overriding-extending-a-php-trait-method
```php
use Translatable {
    getAttributeOrFallback as translatableGetAttributeOrFallback;
}

private function getAttributeOrFallback($locale, $attribute)
{
    $value = $this->translatableGetAttributeOrFallback($locale, $attribute);

    if(value !== null) {
        return $value;
    }

    if (isset($this->attributes[$attribute])) {
        return $this->attributes[$attribute];
    }

    return null;
}
```

The next thing is that you should adjust the `setAttribute` method to fill the value in the original model. And add an saving observer to the translation model to set the `language_id` if not already done.

But why do you need 3 fallbacks? `getTranslation` uses, if configured, 2 fallbacks already.
https://github.com/dimsav/laravel-translatable/blob/f1d5569b6c89da1e89dbe48b9bcbb9e54b0afa2c/src/Translatable/Translatable.php#L61-L81

If your locale is `de_AT` and your configured fallback is `en` it tries to load these translations:
1. `de_AT`
2. `de`
3. `en`

You add the fourth value - from the original model. For what? Even this value belongs to an language - so you can save it as a translation and configure your fallback locale to this language.

Like said in #80 using the translated values on your base model introduces a lot of complexity and problems.
