### ISSUE TITLE
Extra Fields or Properties For Translated Text

### ISSUE THREAD

**Issue by drizzersilverberg** [dimsav/laravel-translatable#562]
I am working for a project that has translations for a text in some languages. I want to add extra column like `voice` field that store audio for each translated texts. 

Is it possible I can store value in extra field?

So i can set and get the audio corresponding to the languages used.

**Comment by Gummibeer** [comment]
The translation model isn't limited to a single translatable field. You can define multiple fields in `$translatedAttributes` and add these columns to your translation model. This way you can define two columns - one with the text and one with the file path to your audio file.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
