### ISSUE TITLE
Can't translate to Portuguese

### ISSUE THREAD

**Issue by GoncaloRod** [dimsav/laravel-translatable#563]
I'm trying to implement translation between English and Portuguese.
My application locales are `'locales' => ['en', 'pt']` and when I'm storing data into DB I do it like this `$project = Project::create(['en' => ['name' => $request->name_en], 'pt' => ['name' => $request->name_pt]]);` but it only stores the `en`. I tried to change from `pt` to `es` and it worked like it should. Can anyone help me with this?

**Comment by Gummibeer** [comment]
Just to be sure you don't have a model attribute called `pt`? #546

Otherwise I don't have a clue what's wrong. As long as the package and trait is installed correctly.

**Comment by GoncaloRod** [comment]
No, I don't have any model attribute called `pt`

**Comment by GoncaloRod** [comment]
Ok, I got it 😅 I forgot that every time you change something in a configuration file you need to run `php artisan cache:clear`
