### ISSUE TITLE
Has this package a possibility to get translations of related models

### ISSUE THREAD

**Issue by tvitas** [dimsav/laravel-translatable#565]
Has this package a possibility to get translations of related models:
`$city = City::with('country')->where('id', 4)->get();`
`$city->translate('en');`

Expecting translated: $city->name and $city->country->name. Got  $city->title only :)

**Comment by Gummibeer** [comment]
The moment you access `$city->country->name` it loads the translation. If you want to preload it you can do so by also calling `$city->country->translate('en')`.
For which case do you need this? Do you want to serialize the model with the translation? Or display them in a blade view?

**Comment by tvitas** [comment]
@Gummibeer thanks for explanation. I need serialize it  with translation and apply mapInTo(), e. g.
`$city->mapInTo(Transformer::class)`, but, maybe, this method is wrong by 'design'.
