### ISSUE TITLE
how i can custom $translatedAttributes from outside model

### ISSUE THREAD

**Issue by longlevan9x** [dimsav/laravel-translatable#571]
Ex:
I set in my model
```php
public function setTranslatedAttributes($translatedAttributes) {
    $this->translatedAttributes = $translatedAttributes;
    return $this;
}
```
and I use, but not work.
`(new Category())->setTranslatedAttributes(['name'])`

you can support me or fix it.

**Comment by Gummibeer** [comment]
What do you mean with "but not work"?
Do you use the adjusted category model instance? Or do you create a new one?
The translated attributes property isn't static. So you have to adjust it on every instance.

Even if I don't get why/for what you need this? Every change to this array requires at least one database adjustment. So you can't add new attributes on runtime without migrating the database.

What's your usecase?

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
