### ISSUE TITLE
get all and Fallback if translation is missing #23

### ISSUE THREAD

**Issue by badrshs** [dimsav/laravel-translatable#577]
Hi , i want to select all and then fallback the missing translation , i did some research on documentation but couldn't find any solution . 
let's say my default language is en and i want to select all slider with fr locale from database but  also fallback the missing to en  

 $value = \App\Sliders::translatedIn("fr",true)->get()

$value should return all fr translation + fallback the missing 

any solution please ?

**Comment by Gummibeer** [comment]
You would need a custom scope which allows multiple locales:
```php
return  \App\Sliders::whereHas('translations', function (Builder $q) use ($locale) {
        $q
                ->where($this->getLocaleKey(), '=', $locale)
                ->orWhere($this->getLocaleKey(), '=', $defaultLocale);
});
```

After this the normal logic will takeover and translate all in `fr` if possible or `en` as fallback. The code is just copied from the current scope - so could be that you have to play-around a bit to make it work. You could also use `whereIn` and list locales as an array.

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
