### ISSUE TITLE
Wrong column name

### ISSUE THREAD

**Issue by rafailml** [dimsav/laravel-translatable#579]
I have table 'newsletter_places' and corresponding 'newsletter_places_trs'.

I'm trying to create new record with 
`$nlPlace = NewsletterPlaces::create();`

And I'm getting error:

> Unknown column 'newsletter_places_trs.newsletter_places_id' in 'where clause' (SQL: select * from `newsletter_places_trs` where `newsletter_places_trs`.`newsletter_places_id` = 1 and `newsletter_places_trs`.`newsletter_places_id` is not null)

It search for `newsletter_places_trs`.`newsletter_places_id` instead of `newsletter_places_trs`.`places_id`

migration code of CreateNewsletterPlacesTable
```
Schema::create('newsletter_places', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->softDeletes();
        });
```

migration code of CreateNewsletterPlacesTrsTable
```
Schema::create('newsletter_places_trs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('place_id')->unsigned()->index();
            $table->string('locale', 2)->index();
            $table->string('name', 100);
            $table->timestamps();

            $table->unique(['place_id', 'locale']);
            $table->foreign('place_id')->references('id')->on('newsletter_places')->onDelete('cascade');
        });
```

And the models:
```
class NewsletterPlaces extends Model
{
    use \Dimsav\Translatable\Translatable;
    use SoftDeletes;
    
    public $translatedAttributes = ['name'];
}
```

```
class NewsletterPlacesTr extends Model
{
    protected $fillable = ['name'];
}
```

What I'm doing wrong here?

**Comment by Gummibeer** [comment]
You have to define `$translationForeignKey`

https://github.com/dimsav/laravel-translatable/blob/c03c2e1a92075c40c5efd8dd400c1bd501e71986/src/Translatable/Translatable.php#L108-L115

**Comment by rafailml** [comment]
@Gummibeer  Thank you!
