### ISSUE TITLE
Problem with relations

### ISSUE THREAD

**Issue by hamidst** [dimsav/laravel-translatable#580]
Hi
I have a problem when i want to get my model with relations:
```php
Option::where('id', 1)->with(['optionValues'])->first()->toArray();
```
Above line of code works just fine and i have option values in my array.
BUT this line is not returning options values at all
```php
Option::where('id', 1)->with(['optionValues'])->first()->translate()->toArray();
```
It just returns the option table fields and its translations but not `option_values` fields.
Thank you

**Comment by Gummibeer** [comment]
Hey,
because `translate()` returns the translation model and not the main one.
https://github.com/dimsav/laravel-translatable/blob/c03c2e1a92075c40c5efd8dd400c1bd501e71986/src/Translatable/Translatable.php#L60

**Comment by hamidst** [comment]
So this package is not practical at all!
Pleas write this in your documentation.
It wasted two hours of my time.

**Comment by Gummibeer** [comment]
It is, it can auto translate so you don't have to call any method.
And it's already in the documentation:
```php
// This returns an instance of CountryTranslation of using the default locale.
// So in this case, french. If no french translation is found, it returns null.
$translation = $germany->translate();
```

So everything is right, we also provide a scope to load the translation.
