### ISSUE TITLE
Translations not used when using $object->toJson();

### ISSUE THREAD

**Issue by jcwatson11** [dimsav/laravel-translatable#64]
In any model, if you call toJson() on your object, the underlying Eloquent Model will not get the translated attributes.

I have composed and tested a fix. All you have to do is add the following method override to your Translatable trait:

```
/**
 * Convert the model instance to an array.
 *
 * @return array
 */
public function toArray()
{
    $attributes = $this->attributesToArray();

    foreach($this->translatedAttributes AS $field)
    {
        $attributes[$field] = $this->getTranslation()->$field;
    }

    return array_merge($attributes, $this->relationsToArray());
}
```

Since the underlying model uses toArray() in order to convert something to JSON first, this will cover both cases where you need an array, and cases where you need a JSON object.

**Comment by EcoFreak** [comment]
Why is didin't you include this in version 4 for Laravel 4?

**Comment by dimsav** [comment]
@EcoFreak it is already implemented in v4.4 :)

**Comment by EcoFreak** [comment]
I had the composer requirement set to an earlier version. I've tried it and it returns me the object with an array attribute named "translations" instead of including only the values of the current language.Can you help?

**Comment by dimsav** [comment]
Please check the tests and the readme file to see how to implement.
