### ISSUE TITLE
[5.0] Transtable is DOWN with the last Laravel updates.

### ISSUE THREAD

**Issue by jonathanpmartins** [dimsav/laravel-translatable#77]
For example if I try to do
```
php artisan
```
It breaks down with the follow error:

exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /storage/framework/compiled.php:3561
Stack trace:
#0 /vendor/dimsav/laravel-translatable/src/Translatable/TranslatableServiceProvider.php(9): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /vendor/dimsav/laravel-translatable/src/Translatable/TranslatableServiceProvider.php(9): Dimsav\Translatable\TranslatableServiceProvider->package('dimsav/laravel-...', 'translatable', '/var/www/html/n...')
#2 [internal function]: Dimsav\Translatable\TranslatableServiceProvider->boot()
#3 /storage/framework/compiled.php(414): call_user_func_array(Array, Array)
#4 /storage/framework/compiled.php(914): Illuminate\Container\Container->call(Array)
#5 /storage/framework/compiled.php(906): Illuminate\Foundation\Application->bootProvider(Object(Dimsav\Translatable\TranslatableServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Dimsav\Translatable\TranslatableServiceProvider), 35)
#7 /storage/framework/compiled.php(907): array_walk(Array, Object(Closure))
#8 /storage/framework/compiled.php(1176): Illuminate\Foundation\Application->boot()
#9 /storage/framework/compiled.php(730): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(174): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(88): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}

If I comment out (//'Dimsav\Translatable\TranslatableServiceProvider',) from service providers array, the problem disappears. But than I loose translatable... :/

I think that the problem begins where the latest laravel/laravel commit removes all folders from "config" folder. config/packages/dimsav/laravel-translatable/config.php, remains that. But I think the framework dont get it anymore.

**Comment by jonathanpmartins** [comment]
I think this is a great tool for translatable instegration. https://github.com/orchestral/config

**Comment by anzeznidarsic** [comment]
any progress on this change? L5 is coming out next week

**Comment by dimsav** [comment]
Guys don't forget that the work provided for this open source project is fully voluntary. 

PR are welcome.

**Comment by anzeznidarsic** [comment]
I'll play around on this one and PR.

**Comment by dimsav** [comment]
Ok I updated the thing. Can you guys test?

@jonathanpmartins @anzeznidarsic @nWidart

**Comment by anzeznidarsic** [comment]
On first couple of tests it seems it's working perfectly.
