### ISSUE TITLE
Events nos firing when only translation is saved

### ISSUE THREAD

**Issue by dpgover** [dimsav/laravel-translatable#82]
Hi,

If the model gets a modified translation, but it is not dirty, "parent::save" is not executed. So that means that the saved event won't fire.

My software uses those events for cache clearing, so if I change a translation on a model, the cache doesn't get invalidated.

I think the possible options are:
- Always call "parent::save"
- Execute the event using "registerModelEvent"

Thanks.

**Comment by dimsav** [comment]
I don't think always executing parent::save is a good idea. 

We could fire a saved event if translations are saved.

**Comment by dpgover** [comment]
Yes, the second option is the best, without a doubt.

**Comment by dimsav** [comment]
Can you do a pull request? Time is a bit short at the moment

**Comment by dpgover** [comment]
For me too the time is short. I can do a pull request, only I cannot make the proper tests.

I tested the solution in my own project and it is working fine.

If you can accept that, I'll try to make the pull request today.

**Comment by dimsav** [comment]
Sure, do the pull request to branch version-4 and I'll add the tests.

**Comment by dpgover** [comment]
Done. The pull request is up
