### ISSUE TITLE
Default translations on translated model

### ISSUE THREAD

**Issue by arall** [dimsav/laravel-translatable#83]
Can I somehow use a model field (`name`) as default translation fallback instead a row on translations table?

For example:

#### Table countries

id     | name      | iso
------|------------| ----------
1 | Greece | gr

#### Table country_translations

id     | country_id | name | locale
------|------------| ----------| ----------
1 | 1 | Griechenland | de

#### Code 
```php
$country = Country::where('iso', '=', 'gr')->first();
echo $country->translate('en')->name; // Greece

App::setLocale('en');
echo $country->name;     // Greece
```

**Comment by dimsav** [comment]
You can do this:

```php
App::setLocale('en');

$country = Country::where('iso', '=', 'gr')->first();
echo $country->translate()->name; // Greece
```

**Comment by arall** [comment]
Thanks @dimsav.

To avoid all views modification, I will write accessors on models, like this:

```php
public function getNameAttribute()
{
    return $this->translate()->name;
}
```

Any idea to write less code?

**Comment by dimsav** [comment]
Have you tried this without any accessor? Should work too.

```php
App::setLocale('en');

$country = Country::where('iso', '=', 'gr')->first();
echo $country->name; // Greece
```

**Comment by arall** [comment]
Yes, that what I tried first. It prints null.

Any ideas? Perhaps I have to set something on config file?

**Comment by dimsav** [comment]
Have you set the property `$translatedAttributes`?

```php
class Country {
 
    public $translatedAttributes = array('name');

}
```

**Comment by arall** [comment]
Yes I did.

Also, if I do `$country->translate()->name` prompts me the error: `Trying to get property of non-object`.

Now I'm 100% sure that I'm doing something wrong... but what?

**Comment by arall** [comment]
@dimsav I guess that my problem explanation is not clear enought.

I don't have any other translations on `country_translations` table. The main language should be english, and the default translations is setted on models table, `countries`.

I don't want to move all the model fields (`name`) to `country_translations` table, with `en` locale.

If I run the following code

```php
App::setLocale('en');
$country = Country::where('iso', '=', 'gr')->first();
echo $country->name;
```

... it doens't print anything. I figured out that `getTranslation` function from `Translatable` is triggered, and the functions result is a NULL. So if I run this code:

```php
App::setLocale('en');

$country = Country::where('iso', '=', 'gr')->first();
echo $country->translate()->name; // Greece
```

... the error `Trying to get property of non-object.` makes sence, since its trying to get `name` property from a NULL.

Hope the issue is more clear now.

**Comment by dimsav** [comment]
I am sorry but this is not how this package works. If you want to translate the country's name, you have to explicitly move it to the translation table and remove it from the model.

**Comment by arall** [comment]
@dimsav Ok, thanks.

I will try to fork and code it.

Thanks for your time, and for the package, its awesome.

**Comment by dimsav** [comment]
You are welcome :)
