### ISSUE TITLE
discover first language

### ISSUE THREAD

**Issue by erickmonteiro** [dimsav/laravel-translatable#86]
Hello, I am using 3 languages in my project:
- Portuguese (pt-br)
- English (en-us)
- Spanish (es-es).

My administrative area is multi-language, and each User can create your post in your language and then someone else translate into your language.

I have translated my posts, how can I find out which was the first language used to create a specific post?

example:
echo Post :: find (1) -> was_created_by_language; // pt-br
echo Post :: find (2) -> was_created_by_language; // en-us

**Comment by dimsav** [comment]
You could add timestamps to translations and see which translations was added first for a specific post id.

If you want to get the language after fetching the data from the database, you could do something like that:

```php

class Post extends Eloquent
{

    getWasCreatedByLanguageAttribute()
    {
        foreach ($this->translations as $translation)
        {     
            $first = $first and $first->created_at < $translation->created_at 
                ? $first
                : $translation;
        }                          
        return $first; 
    }


}
```
