### ISSUE TITLE
Can I fallback to the original text

### ISSUE THREAD

**Issue by elhelaly** [dimsav/laravel-translatable#87]
When I try to get translation of attribute that not added translation to it yet, null returned
Can I return the original text instead of null ?

**Comment by dimsav** [comment]
Hi,

please see here how to fallback to the translation of another language:
https://github.com/dimsav/laravel-translatable/blob/master/tests/TranslatableTest.php#L214-L219

**Comment by elhelaly** [comment]
Thanks for your quick reply
I don't mean fallback to a translation
for example, If I have code like this
```
$country->translate('en')->name
```
and I didn't add any translation to the name of the country neither in English nor in any language else
In this case null returned, I think if original text returned it will be better 
I searched in package to replace null with original text and I found it here:
https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L116
I suggest replacing this line with
```
return parent::getAttribute($key);
```
And I suggest add config option like not found fall-back to select return null or original text

**Comment by dimsav** [comment]
I am afraid you have a wrong db schema. The table country does not have a `name` column. The country name is store ONLY in the translations table.

**Comment by maherelgamil** [comment]
@dimsav  you don't understand @elhelaly 

he need to show key if no translation for this key (simply)

**Comment by dimsav** [comment]
@maherelgamil I don't think this should be the package's default behaviour. You can create a helper method for that.

```php
return $country->translate('en')->name ?: 'name';
```
