### ISSUE TITLE
Using scope with a translatable model

### ISSUE THREAD

**Issue by jbajou** [dimsav/laravel-translatable#88]
Hello,

I'm trying to retrieve only a name (dependent on the locale) and an id from a translatable model using the scope feature of Laravel.

My model (Location)  as a field called 'name' which is translatable (and therefore located in location_translations (model: LocationTranslation).

The following code (from models/Location.php) can not work because name is not in locations but in location_translations:
```
    public function scopeSelect($query, $title = 'Select') {
    	$selectVals[''] = $title;
	    $selectVals += $this->lists('name', 'id');
    	return $selectVals;
	}
```

Any idea ?

**Comment by dimsav** [comment]
List scope coming in next update.

**Comment by jbajou** [comment]
Any idea on when the next update will be released ?
(efxaristo polu)

**Comment by dimsav** [comment]
already done!
να σαι καλά :)

**Comment by jbajou** [comment]
Impressive! (But i don't see your commit. I guess you've update the 5.x branch right ?)

**Comment by dimsav** [comment]
Nope. v4.5

https://github.com/dimsav/laravel-translatable/releases/tag/v4.5

**Comment by jbajou** [comment]
Bravo re file!

I'll try that tomorrow! Thanks a lot, and congrats for the package, that's
very useful!




*Jerome Bajou *Chief Executive Officer

*Direct line:* +33 1 83 62 26 28
*Hotline:* +33 1 83 64 25 52
*Email**:* jerome.bajou@blue-mango-business.co.uk
*Site: *http://www.blue-mango-business.co.uk

**Comment by jbajou** [comment]
Hello,

Could you provide us with an example on how to retrieve only id and name (name beeing translated) using the scope functionality ?

Thanks

**Comment by dimsav** [comment]
Please check the code in the Translatable trait. There is a comment describing how to do this...
