### ISSUE TITLE
Fallback locale not working.

### ISSUE THREAD

**Issue by quiquegarcia** [dimsav/laravel-translatable#91]
I been testing fallback locale and I figured out that's not working until in my model I initialize the variable public $useTranslationFallback = true; or refactor the next function:

```php
private function useFallback()
{
    return $this->getFallbackLocale() != null ? true : false;
}
```
This maybe should be in the config or document it? What am I doing wrong?

**Comment by dimsav** [comment]
Are you talking about the scope method?

**Comment by quiquegarcia** [comment]
The getTranslation() method I think.
For example: I have my locale to App::setLocale('fr'), but in my translations table I had only 'es' and 'en'.  My fallback_locale = 'es', so doing a $model->name must return a string with 'es' translation, right?; instead returns NULL until I do something like this:

``` php
//In my course.php
$this->useTranlationFallback = true;

//In my CourseController.php
App::setLocale('fr');
$course = Course::where('iso','=','MX')->first();
return $course->name;

**Comment by dimsav** [comment]
> This maybe should be in the config or document it? What am I doing wrong?

@quiquegarcia you are right this should move to the config.

**Comment by dimsav** [comment]
@quiquegarcia done [here](https://github.com/dimsav/laravel-translatable/commit/1e57cb252e9752b118c4f2b6fb4bba0719864d5e) 

Documentation coming soon :)

**Comment by quiquegarcia** [comment]
Great work!

Recently I updated my project to Laravel 5, laravel-translatable continues working very well.

Thank you!
