### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by broszies** [dimsav/laravel-translatable#92]
composer require dimsav/laravel-translatable

results in 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dimsav/laravel-translatable ~4.5 -> satisfiable by dimsav/laravel-translatable[v4.5].
    - Conclusion: remove illuminate/support v5.0.0
    - dimsav/laravel-translatable v4.5 requires illuminate/support ~4.0 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10,
(snip)
 - Can only install one of: illuminate/support[v5.0.0, v4.2.9].
 - Installation request for illuminate/support == 5.0.0.0 -> satisfiable by illuminate/support[v5.0.0].

Installed is the most recent version of laravel 4.2.

Any ideas?

Wolf

**Comment by dimsav** [comment]
`Conclusion: remove illuminate/support v5.0.0` you have laravel 5 installed.

**Comment by dimsav** [comment]
Deleting the vendor dir and the composer.lock might help.

**Comment by broszies** [comment]
Thanks, but that didnt work. I´ll keep trying.

**Comment by sdebacker** [comment]
With Laravel 5, what I did is adding ```"dimsav/laravel-translatable": "dev-master"``` to composer.json and the run ```composer udpate```

**Comment by dimsav** [comment]
I thought we were talking about L4.2.

@sdebacker Of course, laravel translatable v5 is not released yet.
