### ISSUE TITLE
How to save translations

### ISSUE THREAD

**Issue by broszies** [dimsav/laravel-translatable#93]
Hi,
sorry again for asking a n00bish question:

How do I actually save translations based on the locale?
I can set the locale for the edit-form, right? 

The instructions say the code should be like this;

 $country->translate('en')->name = 'abc';
 $country->save();

However, how can i dynamically hand over the locale, so that I do not have conditional statements in the Controller? 

Either in the simple version:
 $input = Input::all();
 Category::create($input);

(in this case the translations do not get saved because the translator doesnt find the fields of the translation table for some reason)

Or in the spelled out version, 

 $category = new Category;            
 $category->parent_id    = Input::get('parent_id');
 $category->translate('en')->name = Input::get('name');  // can I replace "en" with "$locale" here?
 $category->translate('en')->description  = Input::get('description');
 $category->save();

Again, sorry for maybe not seeing the obvious. Can someone give me a code snippet for the controller that saves translations to the translations table based on the session locale?

Regards

Wolf

**Comment by dimsav** [comment]
Hi @broszies 

check please the [test](https://github.com/dimsav/laravel-translatable/blob/master/tests/TranslatableTest.php#L166-L181) code for saving translations.

**Comment by broszies** [comment]
Thank you, and sorry for bothering you with a long mail!
