### ISSUE TITLE
L5 compatibilty

### ISSUE THREAD

**Issue by freekmurze** [dimsav/laravel-translatable#94]
Hi,

what's the status on compatibility with Laravel 5?

I just tried to integrate your package into a Laravel 5 app. Setting a translated field fails:

```
Psy Shell v0.3.3 (PHP 5.6.3-1+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> $article = new App\Models\Article();
=> <App\Models\Article #0000000065c2d1f30000000009016c5c> {
       translatedAttributes: [
           "name",
           "text",
           "url"
       ],
       incrementing: true,
       timestamps: true,
       exists: false,
       snakeAttributes: true,
       manyMethods: [
           "belongsToMany",
           "morphToMany",
           "morphedByMany"
       ]
   }
>>> $article->translate('en')->name = 'test';
PHP warning:  Creating default object from empty value on line 1
```

Could this warning have something to do with the fact that my models are namespaced?

**Comment by sdebacker** [comment]
With version 4.5+ of Laravel Translatable, when there is no translation, translate() return null in place of an empty object. So before calling ```$article->translate('en')```, you should check with ```$article->hasTranslation('en)```

**Comment by freekmurze** [comment]
@sdebacker you're right, there is no translation for a new article in my example above. It's not clear to me how a new translation should be created in version 4.5+ of Translatable. Can you give me a hint

```
Psy Shell v0.3.3 (PHP 5.6.3-1+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> $article = App\Models\Article::create([]);
=> <App\Models\Article #000000004738352e00000000517fe60c> {
       translatedAttributes: [
           "name",
           "text",
           "url"
       ],
       incrementing: true,
       timestamps: true,
       exists: true,
       snakeAttributes: true,
       manyMethods: [
           "belongsToMany",
           "morphToMany",
           "morphedByMany"
       ]
   }
>>> $article->hasTranslation('nl');
=> false
>>> $article->translate('nl')->name = 'test';
PHP warning:  Creating default object from empty value on line 1
```

**Comment by sdebacker** [comment]
```php
$data = [
    'nl' => [
        'title' => 'Titel'
    ],
    'fr' => [
        'title' => 'Titre'
    ],
]
```
then
```php
$article->fill($data);
```

**Comment by freekmurze** [comment]
Thanks for your suggestion, unfortunately another warning appears...
```
Psy Shell v0.3.3 (PHP 5.6.3-1+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> $article = App\Models\Article::create([])
=> <App\Models\Article #000000004fa443ed0000000062ca65bb> {
       translatedAttributes: [
           "name",
           "text",
           "url"
       ],
       incrementing: true,
       timestamps: true,
       exists: true,
       snakeAttributes: true,
       manyMethods: [
           "belongsToMany",
           "morphToMany",
           "morphedByMany"
       ]
   }
>>> $data = ['nl' => ['name' => 'Titel'],'fr' => ['name' => 'Titre']];
=> [
       "nl" => [
           "name" => "Titel"
       ],
       "fr" => [
           "name" => "Titre"
       ]
   ]
>>> $article->fill($data)->save();
PHP warning:  preg_replace(): Parameter mismatch, pattern is a string while replacement is an array in /home/vagrant/laravel5.spatie.be/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 686
```

**Comment by dimsav** [comment]
@freekmurze it is easy to help you with just these dumps. Paste some nicely formatted code if you want to help us help you.

The package (v5 was just released) is 100% tested with L5. Maybe checking the [tests](https://github.com/dimsav/laravel-translatable/tree/master/tests) will help you sort things out.

**Comment by freekmurze** [comment]
@dimsav Check at the test was certainly very helpfull. Looking at them I discovered that new translations should be saved with the ```translateOrNew```-method eg.:

```$article->translateOrNew('en')->name = 'new english article'```

It might be helpfull to add an example of this method in README of the package.

**Comment by dimsav** [comment]
PR are welcome :)

**Comment by arielcr** [comment]
I was dealing with the same issue, @freekmurze solution with `translateOrNew`worked out perfectly!

Also think it might be helpful to include the method in the README.

Awesome package BTW!

**Comment by dimsav** [comment]
The readme was updated with translateOrNew in v5.1
