### ISSUE TITLE
ISO 639-1 & ISO 3166-1 alpha-2

### ISSUE THREAD

**Issue by tintamarre** [dimsav/laravel-translatable#98]
Hello,

In your example on your README.md, you use `countries`.`iso` field as reference for the [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). It's not very explicit since what is named locale in `country_translations`.`locale` is also an reference to a code ISO ([ISO 639 1](http://en.wikipedia.org/wiki/ISO_639-1)).

For the sake of clarity, I think it would be useful if your `countries`.`iso` field was called something more explicit (like `countries`.`country_iso` or `countries`.`country_code`).

Thx. 
Martin

**Comment by aglipanci** [comment]
@tintamarre I think the country table is used only for the sake of explanation, so that it's not really an issue.

**Comment by dimsav** [comment]
@tintamarre as @aglipanci said, `iso` is just an example of how to use the package. Feel free to use whatever you want :)

**Comment by dimsav** [comment]
If you think that `countries`.`code` would be ok, I would be ok if you send a PR to change this.

**Comment by tintamarre** [comment]
I know it's just an example, but it confuses me at first ... I thought it would confuse other people. I will send a PR with `countries`.`code`.
