### ISSUE TITLE
Error config:publish dimsav/laravel-translatable in L5

### ISSUE THREAD

**Issue by tintamarre** [dimsav/laravel-translatable#99]
In L5 `php artisan config:publish dimsav/laravel-translatable` and `php artisan vendor:publish dimsav/laravel-translatable` don't work.

$ php artisan config:publish dimsav/laravel-translatable
```
exception 'InvalidArgumentException' with message 'Command "config:publish" is not defined.
```

$ php artisan vendor:publish dimsav/laravel-translatable
```
exception 'RuntimeException' with message 'Too many arguments.'
```

**Comment by aglipanci** [comment]
@tintamarre in Laravel 5 you just have to do php artisan vendor:publish without the package name and it will automatically generate the missing config files for vendors.

**Comment by tintamarre** [comment]
Indeed. Thx ! :-)
